### ISSUE TITLE
UX design for HTML5 translation utility

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rosetta#1]
This issue is to track what we want the UI (used by the translator) to look like. We'll probably explore this via creation of wireframes.

**Comment by pixelzoom** [comment]
@ariel-phet Has anyone at PhET researched tools for creating UX wireframes?

**Comment by emily-phet** [comment]
Not to my knowledge, but I can ask the Inclusive Design Research Centre folks how they create theirs during our next meeting (next week).

**Comment by ariel-phet** [comment]
I mean, we use illustrator for mockups obviously, but do you mean a program in which you can make interactive mockups?

The UX that did the teachwithphet design used a program called Invision

http://www.invisionapp.com/

Seems like it might be worth checking out

**Comment by pixelzoom** [comment]
At 2/3/15 dev meeting, it was decided that I should do a paper design, rather than spend time fiddling with wireframe tools. (Now where did I put my pencil?...)

**Comment by pixelzoom** [comment]
Met with @ariel-phet on 2/17/15 and we sketched out some things. I sent him a PDF scan of my notes and sketches.  He's planning to flesh out, possibly with wireframe tools.

**Comment by pixelzoom** [comment]
Assigning this to @ariel-phet since he said he was going to produce (or assign) the first round of mockups, based on our 2/17/15 design meeting.

**Comment by ariel-phet** [comment]
duplicate of #8 closing
