### ISSUE TITLE
Investigate direct interaction with GitHub for pushing translated string files

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#10]
During the 3/12/2015 we were discussing whether we needed to have a local repository in order to push things to GitHub, or whether we could just push directly.  Pushing directly has the advantage of simplicity - we don't have to set up a local repo, make sure it is up to date, etc.  However, having a local repo may make it easier to handle merges, rebases, and such.  We should investigate which approach looks better and make a recommendation.

**Comment by aaronsamuel137** [comment]
We're using github API for this. Closing
