### ISSUE TITLE
Possible to right align the text in the About dialog for RTL locales?

### ISSUE THREAD

**Issue by arouinfar** [phetsims/rosetta#102]
The left alignment of the text in the about menu makes it a bit tricky to read when viewing in a RTL locale. The readability would be greatly improved if the text could be right aligned instead. Is it possible to automatically right align this text for RTL locales? 

<img width="668" alt="screen shot 2015-11-13 at 1 17 51 am" src="https://cloud.githubusercontent.com/assets/8419308/11141631/6331ae02-89a4-11e5-9473-d5e03106ea67.png">

**Comment by aaronsamuel137** [comment]
Some strings in this dialog are not translatable, so it's not clear what the best thing to do here is. Seems like a good issue to discuss at developer meeting.

**Comment by arouinfar** [comment]
Here's a quick mockup of what the About menu would look like if right aligned:
![image](https://cloud.githubusercontent.com/assets/8419308/11156006/5c0e8c0a-8a06-11e5-9254-b021adca8b23.png)

Illustrator has some RTL funkiness that resulted in the Persian strings being pasted in backwards (e.g. credits becomes stiderc), but this should get the point across. 

From the perspective of native Persian speakers (my husband & sister-in-law, both physicists), this option is much easier to read. Personally, I don't think the non-translatable strings look that strange right aligned. It's probably best to optimize the alignment for the locale, if reasonable to implement.

**Comment by pixelzoom** [comment]
We are currently not doing any direction-specific layout. This would be something new. If it applies to the About dialog (which few people are likely to look at), wouldn't it also apply to control panels and other more visible parts of the UI?

**Comment by samreid** [comment]
@jonathanolson said this would be a nice enhancement and not too much work.

@jbphet said if we are going to do this, shouldn't we do this for every simulation component, such as buttons, checkboxes, etc?

@pixelzoom says the about dialog is not too commonly used, so may not be worth the time.  If we are going to do this, we should do something general that involves a general layout manager that works for other types of components.

@jonathanolson says that sounds great, but it is a longer-term solution.

Here are some guesses as to how long it will take:
@jonathanolson: for VBoxes, automatically change align: left to align: right.  Would handle the AboutDialog ok, but maybe not other cases.
@samreid guesses: Impossible to give a time estimate until we decide what this should look like in several simulations.

Perhaps the best first step would be for @arouinfar to look through 10+ sims and say how the content of the sim should change, if at all.

@ariel-phet where do you want to go with this?

**Comment by pixelzoom** [comment]
11/17/15 dev meeting notes:
• We don't currently have a way to determine direction based on locale.
• It would be better to solve this in a general way, rather than for this 1 dialog.
• A general solution will be a significant amount of work (can't estimate yet).

We would like input from @ariel-phet on whether to defer this, or to work on (and with what priority).

**Comment by ariel-phet** [comment]
Although I agree with @arouinfar that this would be an improvement, there is just really no bandwidth to address the issue. 

Please correct me if I am wrong, but this is the same situation as Java sims correct, we had no way to deal with adjusting layout there?

**Comment by ariel-phet** [comment]
Assigning to @pixelzoom just for an answer from devs

**Comment by samreid** [comment]
The Java sims did not have support for changing the layout based on RTL vs LTR languages.

@ariel-phet said we do not have time to investigate this at the moment.  Let's create an issue about dealing with RTL layout in the future, we may get to it in a year or so, and close this issue.

**Comment by samreid** [comment]
Reopening until a new issue is created.  @pixelzoom can you pick an appropriate repo and open a related issue?

**Comment by pixelzoom** [comment]
> Please correct me if I am wrong, but this is the same situation as Java sims correct, we had no way to deal with adjusting layout there?

Correct, we hadn't implemented anything for Java/Flash sims.

@ariel-phet said on Skype call that we'll revisit at some point in the future. 

We'll track the more general issue in https://github.com/phetsims/joist/issues/308.

**Comment by arouinfar** [comment]
Thanks for discussing this issue! @pixelzoom made an excellent point.
> wouldn't it also apply to control panels and other more visible parts of the UI?

There are actually quite a few layout tweaks that could be made, so I now see how it's a bit like opening Pandora's box. I first noticed the alignment issue in the About dialog because it has quite a large amount of text relative to other places in the sim. 

I will comment on the general issue with some recommendations, since they are fresh on my mind now.
