### ISSUE TITLE
RTL Strangeness with Parentheses

### ISSUE THREAD

**Issue by arouinfar** [phetsims/rosetta#103]
When testing the Persian translation of Molecules & Light we stumbled into an issue with molecularNamePattern. It makes the most sense for the symbolic representation of the molecule to come <i>after</i> its name. (Which equates to the <i>left</i> of the name in RTL locales.) In the screenshot below, Carbon Monoxide is correctly displayed. However, the other chemical symbols are not being handled properly. It looks like everything that precedes the subscript in the symbol gets moved to the left, but the rest is stuck to the right.
![image](https://cloud.githubusercontent.com/assets/8419308/11141440/ac3a2554-89a2-11e5-900c-4f44f1db9915.png)
<img width="319" alt="screen shot 2015-11-13 at 12 11 02 am" src="https://cloud.githubusercontent.com/assets/8419308/11141434/993f592e-89a2-11e5-9860-80c0c9a50565.png">

A similar thing happened in credits.SoftwareDevelopment in Hooke's Law. For some reason the ".)" at the end of "(PixelZoom, Inc.)" gets inappropriately moved to the left of @pixelzoom's name.
<img width="764" alt="screen shot 2015-11-13 at 1 10 09 am" src="https://cloud.githubusercontent.com/assets/8419308/11141500/555154e6-89a3-11e5-8e69-39bda429090b.png">
<img width="759" alt="screen shot 2015-11-13 at 1 08 47 am" src="https://cloud.githubusercontent.com/assets/8419308/11141485/262f7cce-89a3-11e5-9b33-a7af61f33269.png">
<img width="745" alt="screen shot 2015-11-13 at 1 06 58 am" src="https://cloud.githubusercontent.com/assets/8419308/11141466/ffbac3fa-89a2-11e5-8ac8-16678b41f788.png">

Not sure if this is a related issue, but I've also discovered that '\n' must be entered as 'n\' to properly function in an RTL environment.

**Comment by aaronsamuel137** [comment]
I've done a little investigating here. It looks like these issues are not just specific to testing, but will affect the built version too.

The issues in the control panel seem related to the subscript text. Those are the buttons that suffer from this issue.

The issues in the credits seem related to mixing RTL and LTR strings.

**Comment by aaronsamuel137** [comment]
Looks like the SubSupText is split into multiple scenery Nodes. I expect this has something to do with why the rtl embedding is not happening correctly.

**Comment by arouinfar** [comment]
I was wondering about the status of this issue. Currently, it is blocking the submission of the Persian translation of Molecules & Light. If it's not something that can be addressed for awhile (which is understandable given current priorities), the string will be switched back to {0} ({1}). It's not an ideal way to display the information, but it's better than the current behavior of ({1}) {0}. 

I'd like to also point out that an Arabic translation has already been published with ({1}) {0}. 
https://phet.colorado.edu/sims/html/molecules-and-light/latest/molecules-and-light_ar.html
![image](https://cloud.githubusercontent.com/assets/8419308/12043360/db6e8f7c-ae41-11e5-8371-2224c45ca0ad.png)

**Comment by jbphet** [comment]
@arouinfar - I think this may have been resolved.  I just looked at the Persian translation that is currently live on the PhET site, and it looks great (to my untrained eye).  Is this still a problem?  If not, please feel free to close.

**Comment by arouinfar** [comment]
@jbphet I do not think the issue has been resolved. The [Arabic translation](https://phet.colorado.edu/sims/html/molecules-and-light/latest/molecules-and-light_ar.html) of MAL uses the `molecularNamePattern` of `({1}) {0}` which does not display correctly. In particular, water is handled pretty egregiously:
![image](https://user-images.githubusercontent.com/8419308/32805249-1dd1cc46-c946-11e7-82dd-6634b0be9b4a.png)


To avoid layout issues, the [Farsi translation](https://phet.colorado.edu/sims/html/molecules-and-light/latest/molecules-and-light_fa.html), kept the original pattern of `{0} ({1})` which isn't the most semantically correct ordering, but is far more interpretable:
![image](https://user-images.githubusercontent.com/8419308/32805174-f01aaebc-c945-11e7-9ec7-ec95e24ea67e.png)

**Comment by arouinfar** [comment]
Parentheses in the About dialogue now appear to be handled correctly, however.
![image](https://user-images.githubusercontent.com/8419308/32805488-ced4fc98-c946-11e7-989a-ec5ac5f8e328.png)

**Comment by jbphet** [comment]
Thanks for the update @arouinfar - I'll put this on the list of issues to try to address during the chipper:2.0 effort.

**Comment by jbphet** [comment]
This has been addressed with work done for #100 and #139.  Closing.
