### ISSUE TITLE
Add HTML5 Translation Utility User Guide link to HTML5 translation page

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/rosetta#104]
We should add a link to the user guide to the HTML5 translation page: https://phet.colorado.edu/translate/

Basically, add a line for 'User Guide' and put a line break after. 
The guide is located at https://docs.google.com/document/d/11BLxC7eDct6eifH1-nR6tWaxlnGeNEn2SPquT-lIUgY/edit#heading=h.cthiox7kfgfc

Here is a mockup: [Translate_Screen.pdf](https://github.com/phetsims/website/files/38174/Translate_Screen.pdf)

**Comment by ariel-phet** [comment]
The above was requested by @oliver-phet - seems like a nice addition

Assigning to @jbphet but could be done in conjunction with @phetsims/matt-p 

The pdf mockup has some odd lines in it, please ignore and just notice placement of the link

**Comment by jbphet** [comment]
This was added a while back, and I just checked that it's working and that the correct document is being linked.  All looks good.  Closing.
