### ISSUE TITLE
Install Rosetta on the Website VM

### ISSUE THREAD

**Issue by mattpen** [phetsims/rosetta#112]
@jbphet and I discussed this today.  This would be nice to have in order to run tests and experiments on the rosetta app without side-effects.  I've started installing it but have run into a few snags.  There are a lot of configuration issues (database connection, github repos, port redirection) that make this difficult.  

Progress made so far:
- installed node, npm, and required packages.
- cloned babel, chipper, and rosetta to /data/share/phet/phet-repos
- copied init.d/rosetta script and ran update-rc.d
- created rosetta.log
- created phet-admin user, setup build-local.json, provided permission for running rosetta
- created rosetta db (may not be necessary, on figaro we are using the website DB)

Current state:
The application will run, but must be started manually.  The application is not being recognized on the standard http/https ports, which causes a problem using the website authentication.  The app is not recognizing any sims or translation files, this might be caused by a different root path for the sims on the VM.

I'm assigning this to myself to continue work on in the future.  As rosetta is in a fairly steady state at the moment, the development time costs currently exceed the benefit.

**Comment by mattpen** [comment]
@jbphet - I made some progress on this today.  I configured varnish and Apache to be able to deliver the app on a local wifi network.  The app now works over localhost on the VM.  There are still some missing parts to make it work on a client, namely updating the cert on the VM to allow authenticated connection.  This is the error I'm getting now:

    Translation Utility Error
    Unable to obtain user credentials
    If this problem has occurred multiple times and is preventing you from working on translations, please contact phethelp@colorado.edu, and include all information on this page.
    Timestamp: 1453830733216
    Details: Error: CERT_HAS_EXPIRED

I'm working with @jonathanolson to get the VM image uploaded to a shareable location as part of [website/291](https://github.com/phetsims/website/issues/291)

**Comment by mattpen** [comment]
I renewed the self-signed SSL certs and the app is launching properly now.  I've tested viewing a translation with both babel-master and babel-tests.  I have not tried updating or creating a translation. 

There are two items left that I haven't solved yet:
1. The init.d script is not running correctly, the app needs to be started manually.
2. The output is only going to stdout, not to rosetta.log.  I think fixing (1) might fix this as well.

@jbphet - Are these items needed for the VM?

**Comment by jbphet** [comment]
We could live without init.d, and just start this manually.  As far as writing to the log, would ```node rosetta.js > rosetta.log``` have the same effect?

**Comment by mattpen** [comment]
@jbphet - yes, that works just fine.  I set up a command in bashrc to launch it quickly: 
    
    alias rosetta-start="(cd /data/share/phet/phet-repos/rosetta/ ; nohup sudo -u phet-admin node rosetta > rosetta.log &)"

I'm going to upload it to phet-dev today.

**Comment by mattpen** [comment]
I tried to upload this tonight, my upload speeds at home are very slow (estimated 48 hours for the VM).  I'll upload it while I'm on campus tomorrow.

**Comment by mattpen** [comment]
@jbphet - The VM with rosetta installed is now available at /data2/phet-vm/PhET_VM.ova

I added some instructions for installing the VM in the [web intern doc](https://github.com/phetsims/phet-info/blob/master/web-dev-intern-setup.md#setup-the-vm).  If you need any help with setup I'd be happy to assist.

The website is already installed on the VM, but I think the state is currently on the dev branch, if you want to publish master I can help with that as well.

**Comment by mattpen** [comment]
rosetta is working on the vm and ox-dev.
