### ISSUE TITLE
translation test fails when translating strings that contain the percent symbol

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#115]
A user of the translation utility reported that when working on a translation of Beer's Law Lab they entered a string for the pattern ```{0}%```, then pressed the "Test" button, and the simulation got stuck in the startup screen.  I reproduced this with the console open, and here is the error output that was seen:

```
Uncaught URIError: URI malformed(anonymous function) @ beers-law-lab_en.html:451(anonymous function) @ beers-law-lab_en.html:461
beers-law-lab_en.html?strings={"BEERS_LAW_LAB%2Fpattern.0percent"%3A"{0}%"}:469 Uncaught TypeError: window.phet.chipper.strings.get is not a function(anonymous function) @ beers-law-lab_en.html?strings={"BEERS_LAW_LAB%2Fpattern.0percent"%3A"{0}%"}:469h @ beers-law-lab_en.html?strings={"BEERS_LAW_LAB%2Fpattern.0percent"%3A"{0}%"}:463o @ beers-law-lab_en.html?strings={"BEERS_LAW_LAB%2Fpattern.0percent"%3A"{0}%"}:463h @ beers-law-lab_en.html?strings={"BEERS_LAW_LAB%2Fpattern.0percent"%3A"{0}%"}:463o @ beers-law-lab_en.html?strings={"BEERS_LAW_LAB%2Fpattern.0percent"%3A"{0}%"}:463h @ beers-law-lab_en.html?strings={"BEERS_LAW_LAB%2Fpattern.0percent"%3A"{0}%"}:463o @ beers-law-lab_en.html?strings={"BEERS_LAW_LAB%2Fpattern.0percent"%3A"{0}%"}:463h @ beers-law-lab_en.html?strings={"BEERS_LAW_LAB%2Fpattern.0percent"%3A"{0}%"}:463o @ beers-law-lab_en.html?strings={"BEERS_LAW_LAB%2Fpattern.0percent"%3A"{0}%"}:463h @ beers-law-lab_en.html?strings={"BEERS_LAW_LAB%2Fpattern.0percent"%3A"{0}%"}:463o @ beers-law-lab_en.html?strings={"BEERS_LAW_LAB%2Fpattern.0percent"%3A"{0}%"}:463h @ beers-law-lab_en.html?strings={"BEERS_LAW_LAB%2Fpattern.0percent"%3A"{0}%"}:463o @ beers-law-lab_en.html?strings={"BEERS_LAW_LAB%2Fpattern.0percent"%3A"{0}%"}:463h @ beers-law-lab_en.html?strings={"BEERS_LAW_LAB%2Fpattern.0percent"%3A"{0}%"}:463(anonymous function) @ beers-law-lab_en.html?strings={"BEERS_LAW_LAB%2Fpattern.0percent"%3A"{0}%"}:463
```

...and here's a screenshot, which might be a little easier to read:
![bll-translation-error](https://cloud.githubusercontent.com/assets/3082831/12626566/8521fdea-c4f6-11e5-9a9d-4edc34432b84.PNG)

**Comment by jbphet** [comment]
It's fairly unsurprising that this is an issue, since the percent symbol is used in URLs to escape unusual characters.  It's just a use case that never occurred to us and wasn't found during testing.  The solution would be to correctly escape the percent sign.

**Comment by jbphet** [comment]
@ariel-phet suggested that I assign this to @arouinfar initially to find out if this might be the cause of some of the issues that she saw when working on translating simulations to Farsi.  Once this is answer, the issue should be assigned back to me to fix.

**Comment by ariel-phet** [comment]
@arouinfar pinging on this issue

**Comment by arouinfar** [comment]
@jbphet @ariel-phet I don't recall running into any issues/failures when testing sim translations (other than reaching the URL character limit in Hooke's Law which has since been addressed). We did have one failure on submission related to a simultaneous commit from @samreid in babel or rosetta... can't remember off the top of my head which repo it was. Looking at Beer's Law Lab specifically, the pattern.0percent string was left untranslated.

**Comment by jbphet** [comment]
This problem also afflicts Bending Light.

**Comment by jbphet** [comment]
This problem appears to have been due to a redundant call to ```decodeURIComponent``` in the string.js plugin.  Assigning to @jonathanolson for review.  If it looks good, please assign back to me since the affected sims will need to be redeployed in order to fix this issue.

**Comment by jbphet** [comment]
@jonathanolson - can you also look at chipper-string-setup.js?  It is potentially doing the same thing.

**Comment by samreid** [comment]
I'm taking a look into this, self-assigning for now.

**Comment by samreid** [comment]
Running http://localhost/beers-law-lab/beers-law-lab_en.html?strings={%22BEERS_LAW_LAB%2Fpattern.0percent%22%3A%22{0}%%22}

Produces this problem:
initialize-globals.js:124 Uncaught URIError: URI malformed
beers-law-lab-config.js:44 Uncaught TypeError: phet.chipper.getCacheBusterArgs is not a function

**Comment by samreid** [comment]
In https://github.com/phetsims/rosetta/issues/115#issuecomment-175829290 @jbphet said:

> The solution would be to correctly escape the percent sign.

This assessment seems to be correct because the buggy query parameter reported above `{"BEERS_LAW_LAB%2Fpattern.0percent"%3A"{0}%"}` is malformed due to the % sign not having digits following.  The `%` should be encoded as `%25`.

It is unclear why @jbphet removed the decoding step in string.js instead of adding the encoding step.  He said:

> This problem appears to have been due to a redundant call to decodeURIComponent in the string.js plugin. 

Can you elaborate?

**Comment by jbphet** [comment]
Sure.  In ```initialize-globals.js``` there is a block of code, right around line 122 as of this writing, that looks like this:
```js
      for ( var i = 0; i < params.length; i++ ) {
        var nameValuePair = params[ i ].split( '=' );
        queryParamsMap[ nameValuePair[ 0 ] ] = decodeURIComponent( nameValuePair[ 1 ] );
      }
```
Note the call to ```decodeURIComponenent```.  In that same file, the ```getQueryParameters``` method is defined as follows:
```js
    window.phet.chipper.getQueryParameter = function( key ) {
      return queryParamsMap[ key ];
    };
```
So the ```getQueryParameters``` method is just returning values from ```queryParamsMap``` map, which have already been run through ```decodeURIComponent```.  Then, in the ```string.js``` file, there was the following line of code, around line 144 on the current master version:
```js
var queryParameterStrings = parse( decodeURIComponent( phet.chipper.getQueryParameter( 'strings' ) || '{}' ) );
```

Here, ```decodeURIComponent``` is being called a second time on the value of the 'strings' query param, but that method was already called on all query parameters in ```initialize-globals.js```.  Since the string that is problematic is one to control the order of an expression with a per cent sign in it, in this case "{0}%", ```decodeURIComponent``` sees the per cent sign, tries to interpret the data behind it, and errors out.  This is the call that I believe is redundant.

I removed the call to ```decodeURIComponent``` from the portion of ```strings.js``` shown above and voilà, the problem went away.  I tested this change using Rosetta and was able to reverse the pattern (I changed it to "%{0}"), and it had the intended effect in the simulation.

@samreid - we can Skype if you'd like more detail on this.

**Comment by jbphet** [comment]
For future reference, if you need to test this issue, here is the URL that includes a ```strings``` query parameter with an encoded version of the string "{0}%":

http://localhost:8080/beers-law-lab/beers-law-lab_en.html?ea&brand=phet&strings=%7B%22BEERS_LAW_LAB%2Fpattern.0percent%22%3A%22%25%7B0%7D%22%7D

I just spoke with @samreid via Skype, and he was trying to use the strings query parameter shown in the original problem description at the top of this issue for testing.  That one is already partially decoded - I guess by virtue of being spit out through console.log - so it doesn't work to duplicate the issue.

@samreid and I reviewed this together and he now agrees that the ```decodeURIComponent``` call that I pointed out above in ```string.js``` is indeed redundant, and agrees with the decision to remove it.

**Comment by jbphet** [comment]
The only two currently published sims that have the per cent symbol in their English language strings file are Beer's Law Lab and Bending Light.  This issue could be fixed for these simulations by performing a maintenance release for these simulations where they are updated to the latest version of chipper.  However, it's hard to know whether updated the chipper SHA would introduce any other issues, so it would take some initial dev time (probably about an hour for both) and possibly some QA time to make sure that the change can be made with no detrimental effects on the sim.

As @samreid points out, other sims are potentially vulnerable to this issue if a translator decides to put a per cent sign into a string that doesn't currently have one.  This seems like an unlikely scenario to me and, IMO, doesn't warrant maintenance releases for other simulations.  Future deployments that include the fix above will not have this problem.

**Comment by pixelzoom** [comment]
And the same problem in  chipper-string-setup.js?

**Comment by jbphet** [comment]
I created a separate issue for ```chipper-string-setup.js``` so that it didn't get lost in the shuffle of this one.

**Comment by jbphet** [comment]
Assigning to @ariel-phet to decide whether it's worth the time to redeploy BLL and BL.

**Comment by ariel-phet** [comment]
@jbphet @jonathanolson looks like a maintenance release is being done from the commits aove. That seems fine to me. Assigning back to @jbphet

**Comment by jbphet** [comment]
@jonathanolson and I worked together to do maintenance releases on Beer's Law Lab and Bending Light that includes the fixes for this.

**Comment by jbphet** [comment]
Assigning to @oliver-phet so he can let the original reporter of this issue (if he knows who it is) that it is resolved.  If not, he should just close.
