### ISSUE TITLE
make the "Chains" simulation available for translation to team members

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#116]
So that we have a way of testing the translation utility, we should make it possible in Rosetta for PhET team members to select the "Chains" simulation for translation.  This simulation should _not_ be visible to non-PhET team members.  This will enable us to test the translation process without affecting any of the "real" simulations.

This idea was discussed in the 1/28/2016 developer meeting, and we are fairly certain that supporting this will require no changes to the web site - we just have to make sure that the Chains simulation is never configured to be visible on the site.  Assigning to @mattpen initially to confirm this assumption, he should comment on whether this is correct and assign back to me.

**Comment by mattpen** [comment]
@jbphet - I'm not sure how you are planning to control the sim visibility in rosetta, so I can't say with absolute certainly.  But it is correct that if visible=false in the website database then the sim won't appear anywhere on the site publicly.

**Comment by jbphet** [comment]
The plan is to only show the Chains simulation as a selection for translation if the user's login profile lists them as a team member.

**Comment by mattpen** [comment]
If the change is in the Rosetta code there aren't any side effects on the website that I am aware of.

**Comment by jbphet** [comment]
As of this writing, chains is visible in Rosetta to **all** translators.  This is not a huge problem, but there are a lot of translators who are translating it just because it's there.  It would be good to hide this from who are not team members.

We discussed this in the 9/29/2016 developer meeting and decided so assign it to @zepumph to implement.

**Comment by jbphet** [comment]
"Example Simulation" is also currently visible and should be hidden for non-PhET team people.

**Comment by zepumph** [comment]
After talking with @jbphet yesterday I'm going to unassign myself from this until the installer builder port is working fully. Since it is so close I don't want to start this new side of the project (rosetta) while I already have another project on the plate. I will still take this on though.

**Comment by jbphet** [comment]
I have added code to prevent chains, bumper, and example-sim from showing up for translators that are not PhET team members.  I just tested, and it seems to be working well.  Closing.
