### ISSUE TITLE
check for security issues in translated strings

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rosetta#117]
Issue created at 2/4/16 developer meeting.

An example: a string containing HTML markup could contain a nefarious script that gets executed.

**Comment by jonathanolson** [comment]
Curve Fitting and Sugar and Salt Solutions (both not yet published) contain the vulnerability (example was pasted in developer Skype).

**Comment by pixelzoom** [comment]
Related issue: https://github.com/phetsims/special-ops/issues/18

**Comment by jbphet** [comment]
@jonathanolson - is this vulnerability still present in the sim code and, if so, do you think that I should I work to address this during the chipper:2.0 effort?

**Comment by jonathanolson** [comment]
This is checked by XSS query params and fuzzing, not an issue anymore.
