### ISSUE TITLE
create a script to look at submissions from a specific user

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rosetta#118]
... to identify nefarious activity.  Related to https://github.com/phetsims/rosetta/issues/117.

@ariel-phet requested this issue at 2/4/16 developer meeting.

**Comment by liammulh** [comment]
I am not aware of any nefarious translations. We've never received a complaint to phethelp. I am going to close this issue.

If anyone is dealing with nefarious translations in the future, I think a more comprehensive script would create a list of inappropriate words for each locale, then iterate through the translations in babel, printing each string object (which would include the user ID) when an inappropriate word is encountered.
