### ISSUE TITLE
sims that are not yet visible are available for translation

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#120]
The Trig Tour sim was recently published, but was not made visible on the web site for a couple of days due to the fact that the publication happened on a Friday afternoon.  By the time the sim was made visible through the admin interface of the web site, several translations already existed.  Apparently, whether or not the sim is visible is not considered by Rosetta when deciding on the list of sims to present to a user for translation.  We should probably change this.

**Comment by jbphet** [comment]
IMO, this doesn't need to be a super high priority, since it didn't really cause any problems.  I can envision a couple of scenarios where this behavior *could* cause some issues, but they seem fairly unlikely.  So it should be fixed, but not urgently.

**Comment by liammulh** [comment]
Now we have a way of handling this — prototype sims. @jbphet I am going to close.
