### ISSUE TITLE
disable 'Submit' button if there are translation errors

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rosetta#122]
Created at 2/18/16 dev meeting.

It should not be possible to submit a translation that contains errors. For example see https://github.com/phetsims/joist/issues/319#issuecomment-185889403, where a MessageFormat pattern is missing placeholders.

**Comment by jbphet** [comment]
@lmulhall-phet is going to check into this a bit.  It seems like checking of the message format has been added, and works for both of our supported pattern formats, i.e. single and double curly braces.  He'll review the code (which is client-side) and, if all looks good, just close this.

**Comment by jbphet** [comment]
There is some usage of jQuery in the client-side code for this, so @muedli - as you're reviewing this code, please replace any jQuery that can easily be replaced with vanilla JS.

**Comment by liammulh** [comment]
Done.
