### ISSUE TITLE
simInfoArray should be eliminated once all HTML5 simulations are translatable

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#123]
As of this writing, when a simulation is published using the build server, the build server updates a file in Rosetta called "simInfoArray" so that Rosetta has a list of the translatable simulations.  This interaction is a little complicated and will be completely unnecessary once all sims are translatable.  This GitHub issue is used to remind us that we should remove the code from Rosetta and the build server once it is possible to do so, and have Rosetta get the list of simulations from the website's metadata.

**Comment by jbphet** [comment]
Rosetta is now using metadata instead of simInfoArray.  Assigning to @mattpen to eliminate the code in the build server that writes to simInfoArray and then remove the file from GitHub.

**Comment by mattpen** [comment]
This was removed tonight.
