### ISSUE TITLE
User reported issue: missing translatable strings

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/rosetta#124]
Email from translator:

As far as I have noticed then there are few strings in some simulations that can't be translated - when I submit them and open translation again then translation field value is empty again:
- In Beer's Law Lab:
    * units_nm
    * WavelengthSlider.pattern_0wavelength_1units
- In Bending Light:
    * units_nm
    * WavelengthSlider.pattern_0wavelength_1units
- In Reactants, Products and Leftovers:
    * FaceWithPointsNode.pattern_0sign_1points

@phet-steele Can you reproduce this?

**Comment by phet-steele** [comment]
@jbphet it's hard for me to safely reproduce this since these sims are not available on phet-dev to translate. If possible, can you make it so?

**Comment by jbphet** [comment]
Sims should now be available on phet-dev, please give it a try.

**Comment by jbphet** [comment]
I believe this issue is now resolved, see #126.  Assigning to @oliver-phet to communicate with the translator and verify that the behavior now appears correct.  Note that the translator may have to resubmit translations to test this.

**Comment by oliver-phet** [comment]
Translator has been notified and asked to resubmit translations to test the behavior.

**Comment by oliver-phet** [comment]
Translator has reported the following:

> Thanks for fixing problems with untranslatable strings. Anyway, I have discoreved that the same problem exists also with other HTML5 simulation:
> 
> * Acid-Base Solutions:
>     - shortCircuit

**Comment by jbphet** [comment]
The problem was with Rosetta, so it existed for all simulations, not just one of them.  Please ask the translator if they are still seeing the issue after having resubmitted translations.  If so, please record the simulation, locale, and missing strings in this issue so that I can go through the log and determine what's going on.

**Comment by oliver-phet** [comment]
Translator just confirmed that after re-testing, the problem is resolved (no resubmission needed). Closing this issue for now.
