### ISSUE TITLE
submissions can delete parts of a JSON file

### ISSUE THREAD

**Issue by phet-steele** [phetsims/rosetta#126]
@jbphet this results in previously translated strings no longer having a translation. If a user translates a sim with some scenery-phet strings, then translates a different sim with different scenery-phet strings, the original translations will be deleted from the json file. Example:

I went to Beer's Law Lab and translated the two scenery-phet strings there:

`WavelengthSlider.pattern_0wavelength_1units`
`units_nm`

resulting in this commit: https://github.com/phetsims/babel/commit/4fa230f05421932e7daf996f5eb48f5bd1a3e6b4

I then went to RPAL, in the same locale, and translated the scenery-phet string there:

`FaceWithPointsNode.pattern_0sign_1points`

and since the previous strings from Beer's Law Lab are not available in RPAL, submitting a translation for `FaceWithPointsNode.pattern_0sign_1points` deleted the translations for `WavelengthSlider.pattern_0wavelength_1units` and `units_nm`. Resulting commit: https://github.com/phetsims/babel/commit/4d8be724869693d64587f3fa14a62e30ea124c6a

@oliver-phet this is the cause for #124.

**Comment by phet-steele** [comment]
This has become a bigger issue than just common strings, but also applies to shared sim strings (like Beer's Law Lab and Concentration). This commit would have happened after submitting a translation for Concentration, effectively deleting existing Beer's Law Lab translations from the beers-law-lab/beers-law-lab-strings_ar.json file in babel: https://github.com/phetsims/babel/commit/721134ef9fe706b4a6229798623b5f9dd140278a

We may have to go back and replace any missing translations at some point.

**Comment by jbphet** [comment]
This is a pretty significant issue, since it can cause translators to lose a substantial amount of work in some cases.  I'll make fixing it a fairly high priority.

**Comment by jbphet** [comment]
As I think about this, I realize that we've actually been relying on this behavior to remove unused strings, which has enabled us to "preload" the babel repositories with strings converted from the old Java and Flash simulations.  Unless we add specific code to handle the situation of preexisting strings, fixing this issue will main that old unused strings will no longer be removed.

I discussed this with @ariel-phet, and he suggested fixing this in the most expeditious way and no longer transferring the previous strings from the old Java/Flash sims.  I'm on board for this plan.  Marking for the next dev meeting to make sure there are no major objections or suggestions for an easier fix.

**Comment by pixelzoom** [comment]
Why not just remove the used strings? They are clearly identified by the build process, and we previously agreed that they should be removed as a matter of good code hygiene.

**Comment by samreid** [comment]
I don't see any need for babel to remove unused strings (they are never presented to the translator), we should be doing that during development for hygiene.

**Comment by jbphet** [comment]
@pixelzoom said:

> [Unused strings] are clearly identified by the build process, and we previously agreed that they should be removed as a matter of good code hygiene.

Are we checking translated strings, or just English?

**Comment by jbphet** [comment]
We discussed this at the 3/1/2016 dev meeting and decided that I should move forward with the fix that preserves strings for all repos and decide at the next dev meeting (or some other future time) whether to invest effort in a tool that filters ported string files (i.e. those converted from a previous Java or Flash sim) to remove the unused strings or just have the translators translate everything from scratch.

**Comment by jbphet** [comment]
I've implemented a fix for this and tested it on phet-dev with @phet-steele's help, and all looks good.  I pulled it on to figaro and have restarted.  I'm going to leave this open and assigned to me until I see a translation submission that, prior to this fix, would have blown away previously translated strings, but no longer does.  Once I've verified this, I'll close the issue.

**Comment by jbphet** [comment]
Looks like the fix is working.  Below is a link to an example commit.  In this commit, a Solvakian translator submitted a translation for the string "shortCircuit", which is used in the ```ConductivityTesterNode``` common code component that is drawn from the ```scenery-phet``` repo, and which is used in the Acid Base Solutions simulation.  The translator had previously submitted translations for other strings that are *not* used by common code components within Acid Base Solutions, such as ```units_nm```, which is used in ```WavelengthSlider```.  These strings were not overwritten in the commit, therefore, I think it's safe to say the previous translations are no longer being overwritten due to this bug.

https://github.com/phetsims/babel/commit/845f8fbcae21d65f574712321c4480745dad8a82

Issue resolved, closing.
