### ISSUE TITLE
User reported issue: 'Test' sporadically failing

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/rosetta#128]
Translator has reported an error when 'Testing' a translation.

> While translating HTML5 simulations, Test would fail occasionally.  When fail, all the simulations would fail to test.

>I used F12 and the error was shown as attachments.

![phet](https://cloud.githubusercontent.com/assets/5090275/13403034/44070c12-ded0-11e5-9925-5d574caee946.jpg)
![phet1](https://cloud.githubusercontent.com/assets/5090275/13403035/440d16ac-ded0-11e5-993b-4c59ef280b39.jpg)

**Comment by jbphet** [comment]
I strongly suspect that this is essentially a duplicate of https://github.com/phetsims/rosetta/issues/115.  If you look at the URL in the image above, it is the Beer's Law Lab simulation, and the error shown says ```URI malformed```, which is the same error message seen in #115.  I'll leave this open for now, but once the other issue is fully addressed, I'm pretty confident that it will be safe to close this one too.

**Comment by jbphet** [comment]
Assigning to @oliver-phet so that he can let the reporter of the issue know that we believe it may be resolved, and ask them to verify.  If we hear nothing back within a week, I'd say we should just close the issue, since my confidence is reasonably high that it is resolved.

**Comment by oliver-phet** [comment]
User notified. Closing.
