### ISSUE TITLE
Create a github user account that will be used by Rosetta to push to Babel

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#13]
The title pretty much captures it.

**Comment by pixelzoom** [comment]
You might want to check the terms of GitHub, to make sure that creating a user account for a non-user is not a violation of their terms.

**Comment by samreid** [comment]
+1 I strongly recommend checking

**Comment by pixelzoom** [comment]
From GitHub Terms of Service, https://help.github.com/articles/github-terms-of-service/:

> A. Account Terms
> 
> (2) You must be a human. Accounts registered by "bots" or other automated methods are not permitted.

**Comment by jbphet** [comment]
I've contacted GitHub with a question about how to best do what we want to do with this.  I'll post their response below.

**Comment by aaronsamuel137** [comment]
@jbphet, did you ever head back from github about this?

**Comment by jbphet** [comment]
I did get a response, but it was pretty clear that he didn't understand our constraints.  This is what he said:

> The best way to do this, would be for each contributing translator to create a GitHub account, so that their contributions come from them specifically. They can use OAuth to authenticate with your tools so you can perform updates on their behalf.

> Please let me know if you have any other questions.

I don't think we want to require all translators to set up a GitHub account.  So far we've just been using @aaronsamuel137's account, and we have clear commit messages that indicate an automated commit.  I'm okay to continue this way.  Assigning to @aaronsamuel137 to close if he is okay with this.

**Comment by aaronsamuel137** [comment]
I think its okay for now. We can also reassess in the future if for some reason this creates complications for me. Closing
