### ISSUE TITLE
Require user to be a trusted translator before allowing translation

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#14]
As of this writing, Rosetta verifies that a user has valid PhET login credentials before allowing them to be able to translate a sim.  An additional test should be added to make sure that they are also a trusted translator.  The issue https://github.com/phetsims/website/issues/119 is a prerequisite for this issue.

**Comment by jbphet** [comment]
Assigning to @aaronsamuel137 for now, he can assign to @BrianNewsom if appropriate.

**Comment by aaronsamuel137** [comment]
This should be done now. If you are not a trusted translator and try to submit, a pop up will tell you that you need to email phethelp to become a trusted translator.

**Comment by aaronsamuel137** [comment]
This is done. Closing
