### ISSUE TITLE
Change link of PhET HTML5 Translation Utility User Guide

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/rosetta#140]
Please change the 'Help' (within a HTML5 sim translation) link to https://docs.google.com/document/d/18UHBP1O_es-YnGgWb9Ywvlv7OtWYbHpGxM4OVe6CAjU/edit#

Could we also add an identical 'Help' button to the Select Simulation / Select Locale page?

**Comment by mattpen** [comment]
@oliver-phet - Is the access to this doc intentionally controlled?  Neither @jbphet or I can access the doc.

**Comment by oliver-phet** [comment]
Fixed to view only!

**Comment by mattpen** [comment]
@jbphet - I added the new button and changed the link.  I think it should be ok to deploy, would you like to review?

**Comment by jbphet** [comment]
Looks good to me.  Please go ahead with deploying it, but let me know when you do so that I can take a look. Thanks!

**Comment by mattpen** [comment]
@jbphet @oliver-phet - This should be live now on the main website.  Please let me know if any further changes are needed.

**Comment by jbphet** [comment]
I just tested it, and it looks good.  Thanks @mattpen.  Closing.
