### ISSUE TITLE
items to include in Rosetta v2

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#141]
This issue will be used to keep track of the features to be added in the 2nd version of Rosetta.  The work for this is currently be discussed for mid-November 2016.

The features and fixes currently being discussed are:
- fix the problem where testing of the sim doesn't work due to long URLs, see #100 and #139
- support translation of the app strings (maybe - we may do this elsewhere)
- indicating to translators which sims have not been translated for a given locale
- adding support for accessibility strings

**Comment by phet-steele** [comment]
@jbphet, there are a lot of open issues in this repo with the label "rosetta:not for 1.0", maybe look through those to see which can be included?

Also, maybe work for #113? 😄

**Comment by oliver-phet** [comment]
In dev meeting 9/28 AP mentioned that adding support for accessibility strings is not a priority.

**Comment by liam-mulhall** [comment]
This issue is horribly outdated. Closing.
