### ISSUE TITLE
English sim seems to be rebuilt with each new translation

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#142]
I haven't dug into this much, but when I look at the modification dates of the sim files, it appears as if the English simulations are being rebuilt every time a new simulation is submitted.  We discussed this in a recent developer meeting, and decided it wasn't much of a problem, but I thought we should have an issue that tracks it.

**Comment by ariel-phet** [comment]
The more this comes up, the more distasteful it is seeming, and it seems like it might be important for the app in the long run. Self-assigning to discuss with @jbphet in the near future.

**Comment by jbphet** [comment]
I decided to spend a few minutes to see if I could localize this issue.  I looked at the directory containing the Arithmetic simulation, and found that a Spanish translation (locale=es) was built on Nov 29 at 14:59, and the English version was also rebuilt at that time.  I examined the log for Rosetta and can see that the URL that was sent to the build server at that time contained the string ```locales=es```, and did not list the English locale, so the issue is **not** that Rosetta is sending the wrong locales in its build request.

**Comment by jbphet** [comment]
The problem appears to be that the grunt tasks defined in chipper always assume that the English locale should be built.  In the current master version of chipper, in the function `getLocales` in `getBuildConfig.js`, the "fallback locale" is always added to the list of locales, and there is a comment that says, "fallback locale is included in all cases".  

As an experiment, I built a sim from the command line with the option `--locales=es`, and it created the Spanish version and the English version.  I then modified the `getLocales` function to omit the default locale and the Spanish version was built, and not the English version.  However, the `_en-iframe.html` file was still generated, so this mod may not be quite sufficient to solve the problem.

Marking for developer meeting to see if it would be safe to drop the fallback locale in cases where other locales are specified.

**Comment by pixelzoom** [comment]
FYI, this confused me when I was comparing a master change against published versions.  I looked at the date in the About dialog and has a difficult time finding a sim that hadn't been "published" in the past few days.  @jbphet explained that the English version gets rebuilt whenever a translation is added, so I understand this now.  Perhaps we should investigate *not* rebuilding the English version when a translation is published.

**Comment by pixelzoom** [comment]
@jbphet said:
> Marking for developer meeting to see if it would be safe to drop the fallback locale in cases where other locales are specified.

If it's difficult to "drop the fallback locale", then we could also do this:

- copy the English version to a safe place
- build and publish
- restore the saved English version

**Comment by jbphet** [comment]
In the 12/1/2016 developer meeting we decided to move forward with making the build task **not** include the fallback locale of other locales are explicitly specified.

**Comment by jbphet** [comment]
I just had a bit of a stark realization: Since the resolution to this issue involves changing a file in chipper, and since our releases specify a specific version of chipper, the fix for this won't take effect until we either publish a version of the sim from master or do a maintenance release that pulls the fix into the release branches.

**Comment by jbphet** [comment]
Assigning to @pixelzoom to review, since his name appears most often in the history.

Also assigning to @ariel-phet to say whether this should be incorporated into any upcoming maintenance releases.  I believe there is one coming up for stats, this could potentially be rolled in if important enough.

**Comment by pixelzoom** [comment]
First test, to verify that 'en' is not built:

```
% cd ../acid-base-solutions
% grunt --locales=ar
Running "eslint:allFiles" (eslint) task

Running "clean" task

Running "requirejs-build" task

Running "after-requirejs-build" task

Done.
%  ls build
acid-base-solutions_ar.html	dependencies.json
```

Second test, to verify that 'en' is built:

```
% cd ../acid-base-solutions
% grunt --locales=ar,en
Running "eslint:allFiles" (eslint) task

Running "clean" task

Running "requirejs-build" task

Running "after-requirejs-build" task

Done.
% ls build/
acid-base-solutions_ar.html		acid-base-solutions_en.html
acid-base-solutions_en-iframe.html	dependencies.json
```

Looks good, closing.
