### ISSUE TITLE
unnecessary commits, suspect problem with comparing strings

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#144]
I'm investigating a spate of PUSH FAILED notifications coming from Rosetta just after the publication of States of Matter (see https://github.com/phetsims/rosetta/issues/105#issuecomment-269538219), and I've noticed that there are a lot of commits for the "adaptedFrom" string in Joist that don't seem to actually change the value of the string.  I suspect that this is because the string contains a `\r` and the Rosetta code is always flagging it as changed, thus making the unnecessary commit.  Here are several example commits:

+ https://github.com/phetsims/babel/commit/eb23ed1839d8952fbc736c7e6c0d5bf042d669f2
+ https://github.com/phetsims/babel/commit/083262acdaa923456b6c1274a62b0695e04d50a2
+ https://github.com/phetsims/babel/commit/d0b693cdd68ef18f13aed46f150031ce6b49c514

**Comment by jbphet** [comment]
There is some code that looks like it could be at the root of this problem in `commitQueue.js`.  It looks like this:

```js
      // handle special case of multiline string
      if ( oldValue.indexOf( '\n' ) > -1 ) {
        oldValue = oldValue.replace( /\n/g, '\\n' );
      }
```

I'm not sure what this is all about, and I'm going to add some debug logging code so that I can see exactly how the change works and whether it is causes problems with comparing the old and new string values.

**Comment by jbphet** [comment]
I just tested Rosetta by going to the translation utility URL, selecting the States of Matter simulation, and selecting Danish as the language, since I know the sim has been translated into this language.  I was a little surprised at first to find that the `adaptedFrom` string isn't shown to the user.  This probably makes sense, since it isn't used in the PhET-branded version of the sim, but that makes this bug even more egregious if a string that isn't even being presented to the user is being updated when the translation is submitted.

**Comment by jbphet** [comment]
The debug code I added is definitely being hit, and it is showing that indeed, Rosetta is causing commits even when the user isn't changing anything.  The commit https://github.com/phetsims/babel/commit/439e0bdc4c09acb5ef4c8897c0673c16ef9734ff is an example.  Recall that this string isn't being presented to the user, so Rosetta is causing this change on its own.  Here is what was in the debug log at the time of this commit:

```
Dec 30 14:28:54 phet-server.int.colorado.edu rosetta[137201]: Dec 30 2016 14:28:54 MST - info: detected multi-line string
Dec 30 14:28:54 phet-server.int.colorado.edu rosetta[137201]: Dec 30 2016 14:28:54 MST - info: oldValue = punto
Dec 30 14:28:54 phet-server.int.colorado.edu rosetta[137201]: triple
Dec 30 14:28:54 phet-server.int.colorado.edu rosetta[137201]: Dec 30 2016 14:28:54 MST - info: prior to replace operation, oldValue === stringValue = false
Dec 30 14:28:54 phet-server.int.colorado.edu rosetta[137201]: Dec 30 2016 14:28:54 MST - info: oldValue (after replace operation) = punto\ntriple
Dec 30 14:28:54 phet-server.int.colorado.edu rosetta[137201]: Dec 30 2016 14:28:54 MST - info: after the replace operation, oldValue === stringValue = true
```

**Comment by zepumph** [comment]
Can you take a look at this one too @mbarlow12?

**Comment by ariel-phet** [comment]
back to @jbphet

**Comment by jbphet** [comment]
The fix did the trick - we are no longer seeing the spurious commits.  Closing.
