### ISSUE TITLE
pull simInfoArray so that Rosetta can run in separate directory from build-server

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#148]
There is a shared file that currently exists between Rosetta and the build-server that contains information about the simulations, mostly about where Rosetta should go to find the latest published version of each sim.  This file is called `simInfoArray`, and it is updated by the build server and read by Rosetta (I think).  The way it currently works, the build server writes to the copy on phet-server and then pushes those changes to GitHub.  Rosetta never pulls that file - it just relies on it being up to date by virtue of running in the same shared set of repositories as the build server.

We've decided that it would make more sense if each process had its own separate set of the repos that it needs.  This would prevent accidental tampering, and would remove implicit dependencies like the one described above.  For this to work, Rosetta would need to pull this file on a regular basis from GitHub, or read it directly from there (as it does with the string files).  It may make sense to do this at the same time as the plan described in https://github.com/phetsims/rosetta/issues/105#issuecomment-270256342 is addressed.

There is an issue about renaming the directory on phet-server that the build-server and Rosetta both run out of that kicked off this whole train of thought.  The issue is https://github.com/phetsims/perennial/issues/34.

**Comment by mattpen** [comment]
@jbphet - We should be able to use the metadata for this now, if it will help, as chains/example-sim/bumper are now all available.  See https://github.com/phetsims/rosetta/issues/171#issuecomment-367417895 for details.

**Comment by zepumph** [comment]
No objections! I see smithers, yotta, phet-office-mix, and the phet-io-website on that level as well. Good luck!

**Comment by mattpen** [comment]
+1 for `/data/share/phet/rosetta`

**Comment by jbphet** [comment]
Rosetta has moved and is now using metadata instead of simInfoArray.  Closing.
