### ISSUE TITLE
Figure out the URL and file location for translated sims

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#15]
This was discussed in the 4/9/2015 translation meeting.  We need to figure out where on the main server the translated versions of simulations should be maintained, and what the URL will be to access these files.  During the meeting, we basically decided that the translated files should be in the same place as the English files, but there was a bit of uncertainty.

Assigning to @aaronsamuel137.  If it's clear that we will indeed keep all of the translated HTML5 sims in the same place, he can state this and close the issue.

**Comment by aaronsamuel137** [comment]
I suggest the same directory with the English version, i.e.: http://phet-dev.colorado.edu/sims/html/area-builder/latest/area-builder_fr.html.

Closing
