### ISSUE TITLE
add "es_MX" to Java Translation Utility

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rosetta#152]
@kathy-phet asked me to add support for "es_MX" to the Java Translation Utility.  

I'm adding this issue to rosetta because it's related to translation, and so I don't have to deal with Unfuddle for tracking.

**Comment by pixelzoom** [comment]
According to phetcommon-locales.properties, "es_MX" is already supported:

```
ee,el,en,eo,es,es_CO,es_CR,es_ES,es_MX,es_PE,et,eu,\
```

And running Translation Utility version `2.18.00 (74383) May 28, 2015`, I see "Spanish, Mexico (es_MX)" in the locale combo box:

![screenshot_215](https://cloud.githubusercontent.com/assets/3046552/25018957/2457562a-2046-11e7-929f-091bc47e6b63.png)

So there's nothing to do here, it's already supported.

Closing.

**Comment by kathy-phet** [comment]
@oliver-phet - Can you send Diana the existing string files for es_MX and es.

**Comment by oliver-phet** [comment]
@phet-steele let's get together to get all of the files for Diana.

**Comment by oliver-phet** [comment]
Sent to Diana, closing.
