### ISSUE TITLE
Should rosetta's psql tables be in website_production?

### ISSUE THREAD

**Issue by mattpen** [phetsims/rosetta#154]
Currently rosetta uses tables (e.g. saved_translations) located in the website_production database.  It seems like it should not be connecting to this database but rather using its own database to improve encapsulation between the two applications.  Should we create a new db called `rosetta`?

**Comment by jbphet** [comment]
A separate DB sounds like it would make sense.  Let me know when it is set up and ready and we can try it out from Rosetta.  Ideally, we'd be able to test on ox-dev first, so I don't know if that means the DB should be set up on both ox-dev and phet-server.  I'll leave that to...@mattpen I guess.

**Comment by jonathanolson** [comment]
Sounds fine to me, but let me know if we should then add an additional backup step for Rosetta's DB.

**Comment by jbphet** [comment]
I've added the chipper:2.0 label for this, but I feel like it is low priority relative to a lot of the other work that will be done at the same time.  We should do this if it's reasonably easy, otherwise it can be deferred.

**Comment by mattpen** [comment]
The website does not use this table so it isn't causing any problems at the moment.

**Comment by mattpen** [comment]
Deferring priority as this isn't causing issues.

**Comment by liammulh** [comment]
Rosetta 2.0 doesn't use Postgres.
