### ISSUE TITLE
no validation support for named placeholders

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rosetta#155]
In https://github.com/phetsims/phetcommon/issues/36, we switched to patterns that use named placeholders, e.g. `"{{name}} is {{age}} years old."`  

The old approach was similar to Java's MessageFormat, using numbered placeholders, e.g. `"{0} is {1} years old."`   (This approach is deprecated, but will likely live on forever due to the number of translated strings involved. It will not be used in new code.)

When translating a string that contains placeholders, it's essential that the translated string contains all of the placeholders that appear in the English string.  Failure to do so would cause an assertion failure.  But in the versions used by Rosetta, assertions are stripped out, so there may be a hard failure.

Rosetta currently verifies numbered placeholders, see translate-sim.js line 172:

```    var messageFormatRegexp = /\{\d+\}/g;```

This is obviously not going to work for named placeholders, which use different delimiters and arbitrary names.   And there are live sims that use named placeholders.

Q: Should verification of named placeholders be added to Rosetta? 
Q: What is the priority?

**Comment by pixelzoom** [comment]
StringUtils.fillIn uses this regular expression to extract placeholders:

```var placeholders = template.match( /\{\{[^\{\}]+\}\}/g ) || [];```

Probably the same for Rosetta.

**Comment by pixelzoom** [comment]
I did some investigation into what happens when translated and English string don't have the same placeholders.   There are 2 cases, which I'll describe using this English example:

```
> phet.phetcommon.StringUtils.fillIn( '{{name}} is {{age}} years old', { name: 'Fred', age: 23 } )
"Fred is 23 years old"
```

(1) The translated string is missing a placeholder that appears in the English string. In this case, the extra value provided to `StringUtils.fillIn` is simply ignored.  Example:

```
> phet.phetcommon.StringUtils.fillIn( '{{age}} years old', { name: 'Fred', age: 23 } )
"23 years old"
```

(2) The translated string contains a placeholder that does not appear in the English string (e.g. because of a typo).  In this case, the placeholder is filled in with `undefined`.  

```
> phet.phetcommon.StringUtils.fillIn( '{{nome}} is {{age}} years old', { name: 'Fred', age: 23 } )
"undefined is 23 years old"
```

So... The sim won't crash.  But in both cases the string will be missing information.

**Comment by pixelzoom** [comment]
6/22/17 consensus:
• Yes, validation should be added to Rosetta.
• Since it doesn't crash the sim, this is not urgent. It will be addressed the next time we do a bunch of Rosetta work.

**Comment by jbphet** [comment]
This has been added to the code and tested on my local machine and on phet-server-dev.  As of this writing, it is not deployed to phet-server.  My plan is to deploy several new features and verify them all at that time.  This will remain open until I've verified it on the main site.

**Comment by jbphet** [comment]
Reducing priority so it doesn't show up on my "short list".

**Comment by jbphet** [comment]
This has been deployed to the production server and is in use.  This should be verified in conjunction with #173.  Assigning to @phet-steele.

**Comment by phet-steele** [comment]
Works great/
