### ISSUE TITLE
What should the license be for this repo?

### ISSUE THREAD

**Issue by samreid** [phetsims/rosetta#157]
Please review the guidelines in https://github.com/phetsims/tasks/issues/875 and see what license this repo should have.  I thought it might need to be classified as MIT, but wasn't sure.

**Comment by jbphet** [comment]
I reviewed the guidelines, and I agree that the MIT license seems more appropriate since I don't think we have any concerns about getting back any modified code.

**Comment by jbphet** [comment]
Done, assigning back to @samreid to either close or continue the discussion at his discretion.

**Comment by samreid** [comment]
Thanks, closing.
