### ISSUE TITLE
Add locale: Lakota

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/rosetta#158]
We received a request to add Lakota support into the HTML5 translation utility. 

JB commented: This might be a bit tricky to support, since there is apparently no ISO 639-1 two letter code for this language, nor is there an entry in ISO 629-2 (which has the three letter codes), so it may not be trivial to add.

**Comment by jbphet** [comment]
Here are a couple of links for the ISO 639-1 and ISO 639-2 codes.  Neither includes Lakota:

https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

https://www.loc.gov/standards/iso639-2/php/code_list.php

However, it does show up in this list:

http://search.cpan.org/dist/DateTime-Locale/lib/DateTime/Locale/Catalog.pm

**Comment by jbphet** [comment]
The Internet Assigned Numbers Authority (IANA) apparently maintains a set of language codes too, and it seems from some things that I saw on line that this is what Android uses as its language list.  I'm not sure how it relates to the ISO 639 codes, but the IANA list includes Lakota.  Here is a link to the "subtag registry":
https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry

There is a github repo that makes this available in JSON format, see https://raw.githubusercontent.com/mattcg/language-subtag-registry/master/data/json/registry.json.

**Comment by jbphet** [comment]
I'd like to get input from @jonathanolson and @samreid on this.  Here some initial ideas on what we could do:

+ Add the locale 'lk', which doesn't exist in ISO 639, but is unlikely to conflict with anything new.  We could document it heavily in the header file of `LocaleInfo.js`, where we already describe some differences that PhET does.
+ Migrate to the IANA codes.  This would be ambitious and probably unrealistic, but I thought I'd put it out there.
+ Tell the user we can't support it (but I'd really hate to do that).  We might want to at least contact them and see how serious they are before doing any of this.

Adding some assignees to get there input.

**Comment by samreid** [comment]
IMO this is not a sufficient reason to migrate to a different set of codes.  Since nobody else has claimed 'lk' yet, it seems good to assign it to Lakota.  If another LK group comes along later we can assign them a different code.  But I'm interested to hear @jonathanolson thoughts as well.

**Comment by jonathanolson** [comment]
> IMO this is not a sufficient reason to migrate to a different set of codes. Since nobody else has claimed 'lk' yet, it seems good to assign it to Lakota. If another LK group comes along later we can assign them a different code. But I'm interested to hear @jonathanolson thoughts as well.

Currently on the JS-side, we can definitely add locales with no problem (need to update build-server, rosetta, and maybe some other parts that use localeInfo.js).

I'm somewhat more concerned with the website and/or Java/Flash sims. @mattpen, since we use the Locale objects in Java for the website, would this be a problem?

**Comment by ariel-phet** [comment]
Marking for dev meeting, as we may want to have a general policy, and seems like this involves multiple parties

**Comment by jbphet** [comment]
Turns out that Lakota *is* included in ISO 639-3.  The Wikipedia entry for 639-3 says, "ISO 639-3 extends the ISO 639-2 alpha-3 codes with an aim to cover all known natural languages."   The three letter code is "lkt".

**Comment by jbphet** [comment]
In the 8/3/2017 dev meeting we decided that we should test out adding a two-letter locale code to `localeInfo.json` and test it on ox-dev.  I'll do that and report back.

**Comment by jbphet** [comment]
I tried getting this to run on phet-server-dev, but run into a bunch of issues with permissions and such that were unrelated to the problem at hand, so I just went for it on phet-server.  The lk locale is now available in the translation utility, but sims can't be successfully translated unless a maintenance release is done that adds this locale to the version of chipper used by the released simulation.  I did this for the 'chains' simulation to test it out.  I'll get to it later for other sims.

@oliver-phet - please contact the individual who requested this and ask them for the top sims that they would like to translate, and I'll prioritize those.

**Comment by jbphet** [comment]
@mattpen - now that I've done this for the HTML5 sims, is there anything that you need to check about the website code to make sure that the presence of this non-standard locale in the localInfo file doesn't mess anything up with the Java and Flash sims?

**Comment by jonathanolson** [comment]
I've pulled chipper for Yotta statistics processing, so it will pick up and understand the additional locale.

**Comment by oliver-phet** [comment]
Email to translator sent. Will update this issue once we hear back.

**Comment by oliver-phet** [comment]
Translator replied:
> Sorry for the delay -- I'm conferring with several teachers about the sims that would be most useful in their classes. I'll let you know about preferences soon.
>
>I think we will ultimately be interested in translating all the sims, but an initial focus will be on those oriented at elementary grades.

**Comment by mattpen** [comment]
I looked into the website interaction today.  I don't think this should affect Java/Flash sims at all.

It also looks like the interaction with the build-server *should* go smoothly.  The website should return a 200 response without an error, even though the locale is not supported.

However, Localized Simulations depend on `java.util.Locale`, so there will be some quirks on the website that will need to be solved.  Anytime we call `locale.getDisplayName()` (which is all over the place), it will return an empty string.  This is easily solved by creating a simple wrapper that adds Lakota support, but will take some time to implement.

**Comment by jbphet** [comment]
@mattpen - I've got a couple of followup questions.  You said,

> [T]here will be some quirks on the website that will need to be solved

Can you elaborate a bit?  Would these quirks be significant for all users, only for those looking for Lakota translations, or what?  In your opinion, would it be necessary to resolve these before publishing Lakota-translated simulations?

Also, you said:

> This is easily solved by creating a simple wrapper that adds Lakota support, but will take some time to implement.

Can you provide a rough estimate of how much time it would take?

Thanks.

**Comment by mattpen** [comment]
> Can you elaborate a bit? Would these quirks be significant for all users, only for those looking for Lakota translations, or what? In your opinion, would it be necessary to resolve these before publishing Lakota-translated simulations?

Anywhere we display the full name of the language of a sim, the label for Lakota sims will be blank.  It looks like it shouldn't cause any crashes, but will just have blank labels.  

* One example would be [the translated sims page](https://phet.colorado.edu/en/simulations/translated), there would be a line with no languages and therefore no clickable link to the lakota sims.
* Another example is the list of [translated sims on sim pages](https://phet.colorado.edu/en/simulation/projectile-motion#translations).  It would have similar behavior as above.
* It would also affect some of the admin reports, particularly the xlsx metadata 

There are a few more minor instances.

> Can you provide a rough estimate of how much time it would take?

Including testing and deployment, I would estimate 5-6 hours total.  I'd also like to have a way to test this on ox-dev first, I'm not sure yet what that would take as it would require getting rosetta and build-server up and running again on phet-server-dev.

**Comment by jbphet** [comment]
@oliver-phet - did we ever receive a list from the individual who requested this?  He/she said that they'd let us know their preferences soon.

**Comment by oliver-phet** [comment]
I still haven't heard anything back from this user (last pinged 9/18).

**Comment by jbphet** [comment]
I'm going to unassign this and set the priority to deferred.  If the translators get back to us, I'll assign and will increase the priority, and we can work with them to get the sims into shape for them to translate.  If they don't, it's just not a good use of our time to do anything more on this.

**Comment by jbphet** [comment]
We haven't heard anything more from this user, closing.
