### ISSUE TITLE
separate common and simulation strings on the translation page

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#16]
The translation page, i.e. the page that contains the English strings on the left and the translated strings on the right, should have two sections:
1. Simulation strings
2. Common strings
These could be sorted based on the string extraction from the published sim (see #6) and the information contained in the "active-repos" file, see https://raw.githubusercontent.com/phetsims/chipper/master/data/active-repos.  Based on this information, a page could be instructed that shows the two sections.

We decided recently that if a sim shares strings with another, such as concentration and beers-law-lab, the strings should all be displayed as simulation strings and NOT common strings.

**Comment by aaronsamuel137** [comment]
TODO: Add a warning for common strings

**Comment by aaronsamuel137** [comment]
Closing
