### ISSUE TITLE
Add trigger build route to Rosetta 2.0

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#161]
Every once in a while we need to make a fix to something that a translator submitted, and currently the only way to do this without ending up as a credited translator on the web site is to make direct changes to the string files in the babel repo.  We should have a way to make such modifications without ended up credited on the web site.  This will probably require work on the web site side as well.

**Comment by ariel-phet** [comment]
Marking as high priority for developer meeting since this might require a discussion with website folks

**Comment by mattpen** [comment]
Currently, we add a translation credit if there is a user provided in the call to the build-server, there is one locale provided, and that locale is not `*`.  If we can determine within rosetta that a translator should not be added, I think it is sufficient to simply omit the `translatorId` parameter from the post request to the build-server.  This solution would require no work on the build-server or website side.

If we can't determine this in rosetta, we could potentially add a field to the user in the database that is a boolean value called something like `shouldReportTranslationCredits` that individual users can toggle on the EditProfile page.  If desired, this option could only be shown to PhET Team Members.  This would take 5-10 hours of work to add the field to the database, build the UI element for the toggle and add it to the EditProfile page, and test it.

**Comment by samreid** [comment]
What if you just put your name, and we add logic in the website display to filter out PhET team members?  Then we can use the same toolchain for updating translations that translators do.

**Comment by pixelzoom** [comment]
How about a query parameter to rosetta that says "omit the `translatorId` parameter"?

**Comment by pixelzoom** [comment]
How about a query parameter for Rosetta that says "omit the `translatorId` parameter", or maybe more generally `?noCredit`.

**Comment by jessegreenberg** [comment]
Dev meeting 1/9/20: We like the idea of the query parameter if it is a quick solution to this problem.

**Comment by jbphet** [comment]
For https://github.com/phetsims/perennial/issues/178, I added a route that triggers a build of a sim.  The userID must be provided, but we could potentially modify it so that it doesn't, or provide a different route.

**Comment by jbphet** [comment]
The `trigger-build` route has been working well for rebuilding translations over the past several months.  The only downside is that there isn't a very good user interface, so it's a bit unlikely that anyone who doesn't have much experience with Rosetta will be able to use it easily.  Having said that, it *is* documented in `admin-guide.md`.

I think the next step for this will be to create a page that is only available to PhET team members where a sim and locale can be chosen and a "Rebuild Translated Sim" button is available.  This could use the `trigger-build` route, and could extract the user ID from the most recent translation.

Assigning to @muedli, and he and I can discuss at our next weekly meeting.  This can be a relatively low priority effort.

**Comment by liammulh** [comment]
Done.
