### ISSUE TITLE
Trim leading and trailing whitespace added by translators

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#163]
The string plugin is being modified to remove any leading white space from strings.  It was suggested that rosetta trim these too.  Strictly speaking, it's not absolutely necessary to have rosetta do it since the string plugin will prevent any problems, but it would be nice to make it so that the strings that translators supply are exactly what is shown in the sim.  It will also help keep the sim strings clean.  See this comment and the one right after: https://github.com/phetsims/chipper/issues/619#issuecomment-343217841.

**Comment by jbphet** [comment]
When implementing this, but sure to account for and test right-to-left languages.

**Comment by zepumph** [comment]
@mbarlow12 can you have a look at this.

**Comment by ariel-phet** [comment]
Looks like this issue is old and unlikely to get attention soon. Marking deferred.

**Comment by liammulh** [comment]
This is done in Rosetta 2.0:

https://github.com/phetsims/rosetta/blob/4b340a7b60d99af6961f1c19d71bb1947c466355/src/server/translationApi/makeTranslationFileContentsForRepo.js#L93-L99
