### ISSUE TITLE
Change calls to build-server to use POST data

### ISSUE THREAD

**Issue by mattpen** [phetsims/rosetta#165]
The main problem is described in phetsims/perennial#39.  We need to update the calls to the build-server to include parameters in a post data json object rather than as query parameters, much like the changes to chipper here: https://github.com/phetsims/chipper/commit/504a620f9568205cf0b014600d99ce830e98ec78.

@jbphet - We'll support the old query parameter API for a while so this isn't top priority, but this would be good to change as part of chipper 2.0.

**Comment by mattpen** [comment]
@jbphet - I thought this was implemented.  Can you confirm?

**Comment by jbphet** [comment]
Yep.  Closing.
