### ISSUE TITLE
how should functions that return promises be handled in JSDoc?

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#169]
I'm working on some code that uses native JavaScript promises and `async/await`, and I'm not sure how to document the return types in JSDoc.  Since this is new for PhET, this discussion may well set the standard for how this is done going forward.

Looking around online, it seems like there isn't a general consensus on this (see https://github.com/jsdoc3/jsdoc/issues/509 and, specifically, https://github.com/jsdoc3/jsdoc/issues/509#issuecomment-124712686).  The problem is that a Promise resolves to some value or throws an error, which makes it quite different from most return types.  I'm leaning towards something like this:

```js
@returns {Promise<string>}
```
...but in a recent meeting where this was discussed, @samreid suggested this:
```js
@returns {Promise<string, Error>}
```

Someone else - I can't recall whether it was @mattpen or @zepumph - suggesting using `@throws` too.

Part II of this question is how to document async functions.  There is a pretty clear example here http://usejsdoc.org/tags-async.html, though the `@async` and `@function` tags seem redundant to me and are unlikely to be picked up by PhET.  So, if we remove them, the example would look like this:

```js
/**
 * Download data from the specified URL.
 *
 * @param {string} url - The URL to download from.
 * @return {Promise<string>} The data from the URL.
 */
```

I'd like to get input from @jonathanolson and @mattpen first, since they are also writing async code using the latest JS support, and then we can open it up to the team.

**Comment by samreid** [comment]
Where can I see context for this?  I searched `Download data from the specified URL.` across master and didn't find anything.

**Comment by jonathanolson** [comment]
Including the type of the resolved value sounds great. Not sure about the utility of reject types. I’m switching to only using Error subtypes, sometimes including custom subtypes (see execute.js in perennial master). This would be nice to optionally document, but specifying “Error” everywhere sounds like something I’d want to avoid.

**Comment by zepumph** [comment]
@jonathanolson I agree. In the last dev meeting @mattpen seemed to be on the same page as you. If there is a specific `Error` subtype that is worth documenting/is custom, then we though that we could use `@throws` to dictate that.  Something like:

```js
/**
 * Have a party and invite all of your friends
 *
 * @param {Date} date - The date of the party.
 * @return {Promise<Boolean>} Whether or not the party is on.
 * @throws {HasNoFriendsForPartyError} - If there are no friends to invite to the party.
 */
```

I'm not sure if the `@throws` type would be the Error subtype itself, or a Promise of type Error subtype. The alternative marking would be:
`@throws {Promise.<HasNoFriendsForPartyError>}`

Either seem reasonable to me because it leaves the documentation of the reject/error case up to the developer.

**Comment by jbphet** [comment]
@samreid - for a specific example, please see `LongTermStringStorage.getStrings`.

**Comment by samreid** [comment]
Thanks for the context, I don't have anything to add beyond what @jonathanolson and @zepumph and @jbphet said.

**Comment by mattpen** [comment]
I think `@throws {Promise.<HasNoFriendsForPartyError>}` is preferable over `@throws {HasNoFriendsForPartyError}`.  The former instance indicates that the error can be thrown asynchronously with Promise.reject, whereas the latter looks like it only throws synchronous errors

**Comment by pixelzoom** [comment]
In 12/14/17 developer meeting, we decided 2 things (1) create this issue, (2) defer decision until @jonathanolson is available.  So labeling for dev meeting.

**Comment by pixelzoom** [comment]
Most of the above examples (https://github.com/phetsims/rosetta/issues/169#issue-282570380, https://github.com/phetsims/rosetta/issues/169#issuecomment-352288214) are using incorrect JSdoc syntax.  E.g. `{Promise<string>}` should be `(Promise.<string>}` -- not the missing '.'

**Comment by jonathanolson** [comment]
> I think @throws {Promise.<HasNoFriendsForPartyError>} is preferable over @throws {HasNoFriendsForPartyError}. The former instance indicates that the error can be thrown asynchronously with Promise.reject, whereas the latter looks like it only throws synchronous errors

So use of `@throws` is interesting. Note that if you throw an error in an async function, it rejects the promise with that error (instead of having the throw propagate normally). It definitely doesn't throw a `Promise`. If we're going to use that to document promise rejection types, I'd prefer `@throws {HasNoFriendsForPartyError}`.

**Comment by jonathanolson** [comment]
For example, perennial's execute.js would have the documentation:
```js
/**
 * Executes a command, with specific arguments and in a specific directory (cwd).
 * @public
 *
 * Promise will be rejected if the exit code is non-zero.
 *
 * @param {string} cmd - The process to execute. Should be on the current path.
 * @param {Array.<string>} args - Array of arguments. No need to extra-quote things.
 * @param {string} cwd - The working directory where the process should be run from
 * @returns {Promise.<string>} - Resolves with a string of the full stdout from the process.
 * @throws {ExecuteError} - Includes information about the stdout and exit code
 */
```

**Comment by mattpen** [comment]
Perhaps we should reserve `@throws` for syncronous exceptions and use `@reject` or `@rejects` for rejected promises, as in https://github.com/jsdoc3/jsdoc/issues/509?

**Comment by pixelzoom** [comment]
@jbphet is out this week, and he started this issue.  So does this need to be deferred to a future dev meeting?

**Comment by pixelzoom** [comment]
12/21/17 dev meeting: Deferred until @jbphet is back.

**Comment by pixelzoom** [comment]
12/21/17 dev meeting:

Go with what @jonathanolson proposed in https://github.com/phetsims/rosetta/issues/169#issuecomment-353410334 for now.

Revisit when @jbphet returns, to see if he has any objections.

**Comment by pixelzoom** [comment]
@ariel-phet I removed the "deferred" label so that @jbphet reviews this when he returns.

**Comment by jbphet** [comment]
I would prefer @rejects instead of @throws (as Matt suggested in https://github.com/phetsims/rosetta/issues/169#issuecomment-353411090d), since it is always a promise that is returned and exceptions are not truly thrown.  So, I'd like to modify the proposal to:

```js
/**
 * Executes a command, with specific arguments and in a specific directory (cwd).
 * @public
 *
 * Promise will be rejected if the exit code is non-zero.
 *
 * @param {string} cmd - The process to execute. Should be on the current path.
 * @param {Array.<string>} args - Array of arguments. No need to extra-quote things.
 * @param {string} cwd - The working directory where the process should be run from
 * @returns {Promise.<string>} - Resolves with a string of the full stdout from the process.
 * @rejects {ExecuteError} - Includes information about the stdout and exit code
 */
```

**Comment by jonathanolson** [comment]
The above proposal in https://github.com/phetsims/rosetta/issues/169#issuecomment-354328159 sounds great to me.

**Comment by pixelzoom** [comment]
I have no experience with promises, but I'll give https://github.com/phetsims/rosetta/issues/169#issuecomment-354328159 a +0.5.

**Comment by samreid** [comment]
Sounds good, you have my upvote.

**Comment by ariel-phet** [comment]
@jonathanolson will be updating relevant code with this style of documentation

**Comment by jonathanolson** [comment]
Also to note, the standard rejection would be of type `{Error}`, but since that would be included in every async function, it should be omitted. Only include the `@rejects` if it is for a non-standard error type.

**Comment by jonathanolson** [comment]
Applied the documentation changes, closing.
