### ISSUE TITLE
populate translation page based on strings in babel, phase I

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#17]
The translation page, i.e. the page that shows the English strings and allows the user to enter strings for a different language, needs to pull the translated strings from the Babel repository for already translated strings and put them into the text fields on the translation page.  

At some point, we will also need to load history and possibly check for strings in Babel that aren't in the simulation.  For now (phase I), this functionality can be deferred.

**Comment by aaronsamuel137** [comment]
I think this is working. See /translate/sim/arithmetic/es for an example. Where a few strings are prepopulated from babel.

**Comment by aaronsamuel137** [comment]
Finished, closing.
