### ISSUE TITLE
Prevent testing if fields don't validate

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#173]
Strings are currently prevented from being submitted via the "Submit" button if they don't pass validation, but while working with me on #139 @phet-steele noticed that the it is still possible to initiate a test with the "Test" button in this case.  It would be better if tests were also disallowed.

**Comment by jbphet** [comment]
This has been added and deployed.  @phet-steele - please give it a quick test and close this issue if it works.

**Comment by phet-steele** [comment]
Works.
