### ISSUE TITLE
'Save' translation is not saving strings

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/rosetta#174]
Originally reported by a translator on Jan 8, 2018.
> The first thing that I've figured out  that I cannot save the work.- on first image you see that the feedback is showing that the job is saved, but actually, it has been disappeared as soon as I've left the page.

I have been able to reproduce the problem by translating a string, clicking Save, navigating away and back to the saved translation and the translated string is gone.
![image](https://user-images.githubusercontent.com/5090275/34682959-d9e4fb28-f45d-11e7-821c-d67ec71cf4ea.png)
![image](https://user-images.githubusercontent.com/5090275/34683036-18ec41b4-f45e-11e7-9d1a-ef0d42bf3d88.png)

**Comment by phet-steele** [comment]
If I remember correctly while testing this ages ago, this was prone to caching issues and/or a slow response from github. I would see my saved strings if I did a hard refresh or waited a few minutes. Again, this was a long time ago, but @oliver-phet it might be worth asking if they have tried a hard refresh.

**Comment by jbphet** [comment]
@phet-steele - saved strings don't go into GitHub, they go into a DB on phet-server.  Only submitted strings are stored to GitHub.

**Comment by jbphet** [comment]
I'm able to duplicate this.  I tested on Chains+Abkhazian, and the user is correct that strings that are modded and saved are not being restored.  I checked the logs and didn't see anything obvious, so I don't know the root cause yet.  I'm going to mark this for the Chipper 2.0 effort, at medium priority.

**Comment by jbphet** [comment]
I found out that some of the changes for chipper 2.0 have been leaking on to the server, so I moved the changes to a branch and reverted the server code.  See https://github.com/phetsims/rosetta/issues/175 for more info on this.  These changes appear to have fixed the issue with saving.

@oliver-phet - can you request that the user who told us about this issue try it again and see if it is now working correctly for them?  Thanks.  If so, this can be closed.

**Comment by jbphet** [comment]
@oliver-phet - Any word?  Are we able to close this issue?

**Comment by oliver-phet** [comment]
Sorry, this fell off my radar. I just pinged the translator and will update this issue once I hear back.

**Comment by oliver-phet** [comment]
> Yes, everything works perfectly. Thank you a lot.
