### ISSUE TITLE
branch: mobile-app

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rosetta#179]
Identified by `print-branches.sh`. @jbphet please describe.

**Comment by jbphet** [comment]
I don't know anything about this.  The commits appear to have come from @mattpen, assigning to him.

**Comment by mattpen** [comment]
This branch is to handle adding the strings for the mobile apps to rosetta.

**Comment by muedli** [comment]
Branch was stale, so it was deleted. Closing.
