### ISSUE TITLE
Named placeholders could be colored

### ISSUE THREAD

**Issue by phet-steele** [phetsims/rosetta#182]
Numbered placeholders have a blue color to them, while named placeholders are not colored. Would be a nice touch if named placeholders were also colored blue.

<img width="457" alt="screen shot 2018-02-21 at 11 35 54 am" src="https://user-images.githubusercontent.com/5863899/36498401-68045826-16fb-11e8-8b1e-9f0bf5fb8f21.png">

**Comment by chrisklus** [comment]
Name placeholders are now also blue

**Comment by phet-steele** [comment]
Hooray thanks @chrisklus!
