### ISSUE TITLE
should variable names that appear in equations be translatable?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rosetta#183]
In an equation like "_x_ + _y_ = 12", should the variables _x_ and _y_ be translatable?

This came up most recently in https://github.com/phetsims/equality-explorer/issues/50#issuecomment-375734200, and previously in (e.g.) https://github.com/phetsims/expression-exchange/issues/17 and https://github.com/phetsims/trig-tour/issues/88.

As I said in https://github.com/phetsims/equality-explorer/issues/50#issuecomment-375734200 for Equality Explorer:
> In all sims to date, I have been asked to make variable symbols translatable. E.g. 'x' and 'y' are translatable in Graphing Lines and Function Builder. I see similar precedent in Curve Fitting, Least Squares Regression and Trig Tour. My understanding is that while math symbols (+, -, =,...) are universal, variable symbols are not. If that is for some reason different for Equality Explorer, let me know.

**Comment by pixelzoom** [comment]
@amanda-phet and I discussed this via Slack.

To see if anyone has translated variables, we looked at translation files for 2 sims: Function Builder and Graphing Lines.

In Function Builder, these locales translated "x" and "y".  The fact that changes appear for both "x" and "y" suggests that they are deliberate.

| locale | "x" translation | "y" translation |
| -- | -- | -- |
| Greek (el) |  "X" |  "ψ" |
| Korean (ko) | "x X" | "y Y" |
| Simplified Chinese (zh_CN) | "X" | "Y" |

In Graphing Lines, there were no translations of "x" and "y".  The locales noted above for Function Builder were included, but had no translations.  Did different translations do these files?

Recommendations:

(1) Send an email to all translators asking for their input on this issue.  

(2) Specifically ask the Function Builder translators (el, ko, zh_CN) about their translation choice. If they also translated Graphing Lines, ask them why they did not translate there.

**Comment by pixelzoom** [comment]
Assigning to @amanda-phet @ariel-phet @oliver-phet to move this issue forward.

**Comment by oliver-phet** [comment]
I sent a slack to @amanda-phet on 3/24:
> The Korean translator said that his translation “x X” was a mistake… and corrected this morning.

**Comment by amanda-phet** [comment]
The greek translation for x is actually chi, so both x and y have been translated to chi and psi. 
![image](https://user-images.githubusercontent.com/7852916/38046272-803a97f6-327c-11e8-94a9-b22f6db6e8c7.png)

@oliver-phet can you send the emails above that Chris suggested? For (1), I can help you word it if needed. 

For (2), it would especially be useful to email the greek translator.

**Comment by oliver-phet** [comment]
Sorry for not commenting earlier, I already emailed the greek translator... waiting to hear back.

**Comment by ariel-phet** [comment]
Removing my assignment for now. @oliver-phet and I spoke about this, and he said that even if no current translators desire this ability, he would not be surprised if a locale comes along in the future that does want this ability. That seemed like a reasonable notion.

It will be curious what the Greek translator says, but I think I am generally leaning towards allowing variable names to be translated (even if that ability is rarely used)

**Comment by amanda-phet** [comment]
@oliver-phet any update from the Greek translator? Would be good to wrap up this issue.

**Comment by oliver-phet** [comment]
I still haven't heard back (I pinged on 5/4).

**Comment by amanda-phet** [comment]
Thanks. 

It sounds like we will continue to leave variables translatable, but once we hear back about Graphing Lines we can close this issue.

**Comment by amanda-phet** [comment]
>Specifically ask the Function Builder translators (for locales el, ko, zh_CN) about their translation choices for "x" and "y". If they also translated Graphing Lines, ask them why they did not translate "x" and "y" there.

I thought we were waiting on the greek translator to answer this question.

**Comment by oliver-phet** [comment]
We should close this issue if we are waiting on the Greek translator. It's been over a month with multiple emails sent. I don't think we should plan on hearing back... but if we do we can reopen this depending on what they say.

**Comment by amanda-phet** [comment]
OK.
