### ISSUE TITLE
Modularize Rosetta

### ISSUE THREAD

**Issue by zepumph** [phetsims/rosetta#190]
While I was poking around in this repo, I saw that, although `rosetta.js` isn't too big, there were some obvious modules that we could pull out. I think it looks clean if the express app main js file is mostly just routes. This is just a minor change, but @jbphet I hope you will step in if you think I'm implementing nonsense.

**Comment by zepumph** [comment]
Let me know what you think @jbphet

**Comment by muedli** [comment]
See https://github.com/phetsims/rosetta/projects/2#card-39601470.

**Comment by muedli** [comment]
I think I'm going to expand the scope of this issue to include general modularization of Rosetta.

- [ ] Create a file for setting up the short-term storage database. See TODO in rosetta.js.
- [ ] Figure out a more graceful way to handle getting the Rosetta config. See TODO in rosetta.js.
- [ ] Move code for getting saved strings out of routeHandlers.js and into its own file. See TODO in routeHandlers.js.

**Comment by liam-mulhall** [comment]
This should also be an epic with sub-issues.

**Comment by liam-mulhall** [comment]
The new epic is https://github.com/phetsims/rosetta/issues/284. Closing.

**Comment by samreid** [comment]
As discovered in https://github.com/phetsims/chipper/issues/946, there are TODOs in the code referring to this issue.  Reopening.

**Comment by liammulh** [comment]
There are no longer any TODOs in Rosetta's code base. If there are TODOs in other repos referring to this issue, they need to be removed.

I am going to close this issue.
