### ISSUE TITLE
Multiline text inputs go outside of their surrounding box

### ISSUE THREAD

**Issue by zepumph** [phetsims/rosetta#192]
In chrome and firefox I see multiline text and long words go outside of the bounding div that looks editable. Currently it is the worst on firefox we have:
![image](https://user-images.githubusercontent.com/6856943/40211953-f82dcbe4-59f9-11e8-8349-39233f0f76fa.png)

I witnessed this on the published site too. This is a minor issue, as it is purely UI related, but If we change the height and width to `min-height` and `min-width`, then the problem will go away as far as dev tools shows me.

Here is the potential fix:

![image](https://user-images.githubusercontent.com/6856943/40211973-14ff25ec-59fa-11e8-8808-1b4452910f5c.png)

This is changing 2 lines of css, but again, this isn't really my repo, so I don't want to just go in and take over doing stuff like this. @jbphet how does this sound to you?

**Comment by jbphet** [comment]
Sure, go for it.  My experience with CSS and raw HTML is so limited that it's fine with me of others make changes like these without checking with me, just make sure you test such changes well, and bring in the QA team for additional testing if needed.

**Comment by liammulh** [comment]
This is no longer an issue because we use textareas now.
