### ISSUE TITLE
Add the ability to turn on support for a11y string translation on a per-sim basis

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#196]
Work is being planned for the implementation of support for translation of a11y strings, see #193.  One of the features that was proposed and approved was to have a list of sims for which translation of a11y strings is supported.  This would allow us to publish sims with a11y strings but not present those strings to translators, and the a11y team has said that this is what they want because they feel that both keys and values will evolve for a while for most simulations.

The proposal on how to handle this is to have a data file that is a simple list of sims for which translation of a11y strings is enabled.  Rosetta would read this file each time it presents a translation page and, if the sim being translated isn't on the list, a11y strings won't be shown for translation.

**Comment by jbphet** [comment]
@emily-phet - I need to prioritize this versus other a11y work.  Can you provide any insight into when we want to start rolling out support for translation of a11y strings?

**Comment by zepumph** [comment]
I think that this is far down the road, definitely not a high priority.

**Comment by jbphet** [comment]
Support for translation of a11y strings has not become a priority, and there has been a realization that it would probably require a significantly more complex approach than just enhancing Rosetta.  I'm going to close this issue, but will leave https://github.com/phetsims/rosetta/issues/132 open as a sort of "catch all" issue to collect thoughts on the translation of these strings.
