### ISSUE TITLE
Why get strings from master json files for published sim translations?

### ISSUE THREAD

**Issue by zepumph** [phetsims/rosetta#200]
From https://github.com/phetsims/scenery-phet/issues/419#issuecomment-436040330

@jbphet mentioned that deleting a string key from master of BASE would make that string unaccessible to translators even for old shas, published versions, of the simulation. 

This feels really strange and backwards to me, so I'd like to discuss to understand this more.

From that issue, @jbphet said:
>If the string key is simply deleted from the English strings file, that string will stop appearing to translators right away, i.e. before the updated version of the simulation is published. This is because Rosetta extracts the list of strings used in a sim from the published version, then retrieves the master version of the strings from GitHub, and only presents each individual string to the user if it appears in both the sim and the English strings file (at least I'm fairly certain that this is how it operates).

@jbphet can you comment on this issue after looking a bit more into things. I want to make sure that we aren't devoting too much time under in a direction that is "fairly" sure.

**Comment by jbphet** [comment]
This was due to a mis-remembering moment on my part, see https://github.com/phetsims/scenery-phet/issues/419#issuecomment-436306952.  Closing.
