### ISSUE TITLE
MemoryStore is not designed for a production environment

### ISSUE THREAD

**Issue by mattpen** [phetsims/rosetta#205]
@jbphet @mbarlow12 - the master branch of rosetta (currently at 4ea91a255a042fb1e45513973e3056795e199113) does not appear to be stable.  What is the status of development?

When I try to start rosetta from master on ox-dev, this is what happens:

```
Mar 19 10:42:30 phet-server-dev.int.colorado.edu rosetta[33682]: Mar 19 2019 10:42:30 MDT - info: ---- rosetta starting up ----
Mar 19 10:42:31 phet-server-dev.int.colorado.edu rosetta[33682]: Mar 19 2019 10:42:31 MDT - info: Node version: v8.9.0
Mar 19 10:42:31 phet-server-dev.int.colorado.edu rosetta[33682]: Mar 19 2019 10:42:31 MDT - info: locale info data was stale, initiating a new request
Mar 19 10:42:31 phet-server-dev.int.colorado.edu rosetta[33682]: Mar 19 2019 10:42:31 MDT - info: requesting locale info file from GitHub, URL = https://raw.githubusercontent.com/phetsims/chipper/master/js/data/localeInfo.js
Mar 19 10:42:31 phet-server-dev.int.colorado.edu rosetta[33682]: Mar 19 2019 10:42:31 MDT - info: sim data was stale, initiating a new request
Mar 19 10:42:31 phet-server-dev.int.colorado.edu rosetta[33682]: Warning: connect.session() MemoryStore is not
Mar 19 10:42:31 phet-server-dev.int.colorado.edu rosetta[33682]: designed for a production environment, as it will leak
Mar 19 10:42:31 phet-server-dev.int.colorado.edu rosetta[33682]: memory, and will not scale past a single process.
Mar 19 10:42:31 phet-server-dev.int.colorado.edu rosetta[33682]: module.js:538
Mar 19 10:42:31 phet-server-dev.int.colorado.edu rosetta[33682]: throw err;
Mar 19 10:42:31 phet-server-dev.int.colorado.edu systemd[1]: rosetta.service: main process exited, code=exited, status=1/FAILURE
Mar 19 10:42:31 phet-server-dev.int.colorado.edu systemd[1]: Unit rosetta.service entered failed state.
Mar 19 10:42:31 phet-server-dev.int.colorado.edu systemd[1]: rosetta.service failed.
Mar 19 10:42:31 phet-server-dev.int.colorado.edu systemd[1]: rosetta.service holdoff time over, scheduling restart.
Mar 19 10:42:31 phet-server-dev.int.colorado.edu systemd[1]: start request repeated too quickly for rosetta.service
Mar 19 10:42:31 phet-server-dev.int.colorado.edu systemd[1]: Failed to start rosetta.service.
Mar 19 10:42:31 phet-server-dev.int.colorado.edu systemd[1]: Unit rosetta.service entered failed state.
Mar 19 10:42:31 phet-server-dev.int.colorado.edu systemd[1]: rosetta.service failed.
```

Starting from 20981ac5f256219ac5f018df5d322df6df2ec3af it works fine, which is the current position of rosetta on phet-server.  It would probably be a good idea to keep the master branch of rosetta functional, in case there is an unintentional pull and restart in production.

I'd like to start a feature branch for #204, but not sure which branch/sha I should start from.

**Comment by mbarlow12** [comment]
@mattpen I think this is due to some code that should be in a different branch. I deleted the lines in https://github.com/phetsims/rosetta/commit/6c9a0189183d69ff3856db2cea5a5b26e15ca79a, so that should hopefully help.

The MemoryStore() error is from our session handling, but it's not fatal. However, if we want to eliminate that, we should be storing session data in our db (e.g. https://www.npmjs.com/package/connect-pg-simple). The default MemoryStore() actually uses application memory for the session store, which I'm guessing we'd like to avoid. Thoughts?

**Comment by mattpen** [comment]
> The default MemoryStore() actually uses application memory for the session store, which I'm guessing we'd like to avoid. Thoughts?

I'm really not familiar with the rosetta session handling, but we've been running the app like this for quite a while with no problems.  I haven't noticed any memory leaks.  We usually have less than 5 concurrent users max, so maybe its not an issue?  There are other database related improvements in the pipeline IIRC, so might this be good to handle when those get addressed?

**Comment by mattpen** [comment]
Rosetta is running from master again.

**Comment by jbphet** [comment]
Thanks for following up on this @mbarlow12.  The message about MemoryStore has been around for a long time and was already reported in https://github.com/phetsims/rosetta/issues/133.  As @mattpen said, it doesn't seem to impact the actual operation of the utility.

With this in mind, I believe this issue can be closed.  @mattpen - any objections?

**Comment by mbarlow12** [comment]
No objections here.

**Comment by mattpen** [comment]
No objections
