### ISSUE TITLE
Rosetta is wrapped in an iframe on phet-server-dev

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#210]
I'm trying to do some testing of changes to rosetta on phet-server-dev before deploying them to phet-server.  It looks like some changes have been make on phet-server-dev such that rosetta is wrapped in an iframe, probably so that it will be easier to make it look consistent with the new web site changes.  However, it isn't working very well, and it is causing me to lose some time when trying to debug changes to the core rosetta app.  Would it be possible to revert and set aside this iframe wrapping website code until it is closer to going live?  It would probably make sense to do a bit of a push right before the web site goes live to make rosetta compatible with the new look and feel, and I'd be glad to help out with that.

**Comment by mattpen** [comment]
https://ox-dev.colorado.edu/translate/ should only redirect to the iframe wrapper when running in the reskin branch.  Are you working in this branch?  I checked out master and restarted rosetta and it is not redirecting to the iframe wrapper.

**Comment by jbphet** [comment]
I wasn't working the reskin branch that I know of, and I'm not sure I would know how to.  I just tried the link, though, and it's no longer in the iframe, so whatever was done fixed the problem.  Closing.
