### ISSUE TITLE
Get English strings for libraries from the appropriate SHA

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#219]
While working on #214, I noticed that while Rosetta is currently obtaining its English string values from the published SHA of the sim, it is getting the library strings (e.g. those in joist) from master.  It should get them from the branch of each library that is stored in the dependency file.

This hasn't seemed to cause any major issues thus far, and frankly, there are bigger fish to fry on Rosetta, but this should be corrected at some point.

**Comment by jbphet** [comment]
When reflecting on this, it would be difficult to do, since these strings are shared between multiple simulations, so it would require merging in of everything that is submitted.  This is potentially doable, but not trivial.

**Comment by muedli** [comment]
We talked about this in our weekly meeting. It would be too big of a change to do right now, so we're closing. If there's a big overhaul in the future, we might consider reopening.
