### ISSUE TITLE
Changes to translate sim page

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/rosetta#22]
1. Add a link for "translate another sim" in upper left

2. Put buttons at the top as well.

3. Add margin to bottom

4. Change order to "Test" "Save" "Submit"

5. Gray out saved button once saved, and ungray it once another character is pressed. Display the text "Saved" below when the button is grayed.

**Comment by aaronsamuel137** [comment]
Looks great! One more thing - add a text that says "Saved" above the saved buttons when you click it, and have this text disappear when the button is ungreyed.

**Comment by aaronsamuel137** [comment]
And another thing - the save button should not be clickable when it is gray.

**Comment by aaronsamuel137** [comment]
Great! A few more things:

There is a giant gap between the buttons and the start of text:

![screen shot 2015-06-10 at 3 34 34 pm](https://cloud.githubusercontent.com/assets/3193912/8094780/518a2d2a-0f86-11e5-8c72-cf70ec80b037.png)

Is there a reason why this is there? Can you make it smaller? It might be a good idea to start over from scratch with the css for the buttons if this proves difficult.

Also, the highlighting on mouseover is not working for the save button now.

Another thing: might be good to have the "saved" text a little bigger, and maybe above the button? And the buttons farther apart? Just a few ideas, probably we'll have the team take a look tomorrow.

**Comment by zepumph** [comment]
The mouseover doesn't work I believe because the button is disabled until you type into an input again. Is that a problem?  Also how does this look for spacing?

![translation_util_spacing](https://cloud.githubusercontent.com/assets/6856943/8095804/7cb941ae-0f8e-11e5-9237-a5402246900e.png)

**Comment by aaronsamuel137** [comment]
No that is correct. However, after it is ungreyed for the first time, the mouseover no longer works.

**Comment by aaronsamuel137** [comment]
Looks great! Closing
