### ISSUE TITLE
Try allowing compression on fetches of string files from GitHub

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#220]
There is currently the following bit of code in one of the files that gets strings from GitHub:

```js
  // get the file from GitHub
  // TODO: Why is compress set to false?  Try getting rid of that option and see if things still work.
  const response = await nodeFetch( rawStringFileURL, { compress: false } );
```

I'm not sure of the history here, but at some point we should try turning on compression and seeing if it works and whether it makes performance better or worse.

**Comment by muedli** [comment]
@jbphet, I've replaced these instances of Node Fetch in longTermStringStorage.js with my built-in Node HTTPS stuff. Can we close this issue or would you like me to look into compression?

**Comment by jbphet** [comment]
Closing sounds good to me.
