### ISSUE TITLE
Replace the request package

### ISSUE THREAD

**Issue by muedli** [phetsims/rosetta#228]
https://github.com/phetsims/website/issues/1069 led @jbphet to make [this temporary workaround](https://github.com/phetsims/rosetta/commit/579374a248bd747654117cedb15e755daa5f100b). @jbphet then asked me to replace the deprecated Node module "request".  See https://github.com/request/request/issues/3142. @jbphet read https://github.com/request/request/issues/3143 where the Node module "axios" is suggested as a replacement. He suggested we use "axios" for Rosetta. See the "axios" GitHub page https://github.com/axios/axios.

I've used the "axios" module to replace the "request" module, which was only used for one function in js/simData.js.

<details>
<summary><b>Old simData.js</b></summary>

```
// function that updates the local copy of the sim info by retrieving and interpreting metadata from the PhET site
async function updateSimData() {
  const url = RosettaConstants.PRODUCTION_SERVER_URL +
              '/services/metadata/1.2/simulations?format=json&type=html&include-unpublished=true&summary';

  winston.debug( 'updating sim data using metadata URL = ' + url );

  let simMetadata;
  try {
    simMetadata = await new Promise( ( resolve, reject ) => {
      request( url, async ( error, response, body ) => {
        try {
          body = JSON.parse( body );
        }
        catch( e ) {

          // the JSON object wasn't formatted right, reject
          reject( e );
        }

        // there was some error in the request, reject
        if ( error ) {
          reject( error );
        }

        // there was an error processing the request
        else if ( body.error ) {
          reject( new Error( body.error ) );
        }

        // it's all good, resolve the promise
        else {
          resolve( body );
        }
      } ).auth( 'token', global.config.serverToken, true );
    } );
  }
  catch( err ) {
    winston.error( 'metadata retrieval failed, err = ' + err );
    return Promise.reject( err );
  }

  if ( !simMetadata || !simMetadata.projects ) {
    winston.error( 'unable to obtain metadata, sim info not updated' );
  }
  else {

    // extract the subset of the metadata needed by the translation utility and save it in the sim info object
    simMetadata.projects.forEach( projectInfo => {
      projectInfo.simulations.forEach( simData => {
        const simName = simData.name;
        const translationLocales = [];
        let englishTitle = '';
        simData.localizedSimulations.forEach( localizedSimData => {
          translationLocales.push( localizedSimData.locale );
          if ( localizedSimData.locale === 'en' ) {
            englishTitle = localizedSimData.title;
          }
        } );

        simDataObject[ simName ] = {
          englishTitle: englishTitle,
          simUrl: RosettaConstants.PRODUCTION_SERVER_URL + '/sims/html/' + simName + '/latest/' + simName + '_en.html',
          translationLocales: translationLocales,
          visible: simData.visible,
          version: projectInfo.version.string
        };
      } );
    } );
    timeOfLastUpdate = Date.now();
  }
}
```

</details>

<details>
<summary><b>New simData.js</b></summary>

```
// TODO: Verify that this is working correctly with John.
// Gets sim metadata from the PhET site.
async function getSimMetadata() {

  // Set a variable for the URL and use Winston to log it.
  const simMetadataUrl = `${RosettaConstants.PRODUCTION_SERVER_URL}/services/metadata/1.2/simulations?format=json&type=html&include-unpublished=true&summary`;
  winston.debug( `Updating sim info using metadata at ${simMetadataUrl}.` )

  // Get sim metadata from the PhET site. "axios" automatically transforms JSON into a JavaScript object.
  try {
    const response = await axios.get(simMetadataUrl, {
      auth: {
        username: 'token',
        password: global.config.serverToken
      }
    });
    return response.data;
  }
  catch ( error ) {
    winston.error( `Getting sim metadata failed with ${error}.` );
  }
}

// TODO: Verify that this is working correctly with John.
// Updates the local sim info with metadata from the PhET site.
async function updateSimData() {

  const simMetadata = await getSimMetadata();

  if ( !simMetadata ) {
    winston.error( 'Unable to obtain "simMetadata". Sim info not updated.' );
  }
  else if ( !simMetadata.projects ) {
    winston.error( '"simMetadata.projects" is undefined. Sim info not updated.' )
  }
  else {

    // Extract the subset of the metadata needed by the translation utility and save it in the sim info object.
    simMetadata.projects.forEach( projectInfo => {
      projectInfo.simulations.forEach( simData => {
        const simName = simData.name;
        const translationLocales = [];
        let englishTitle = '';
        simData.localizedSimulations.forEach( localizedSimData => {
          translationLocales.push( localizedSimData.locale );
          if ( localizedSimData.locale === 'en' ) {
            englishTitle = localizedSimData.title;
          }
        } );

        simDataObject[ simName ] = {
          englishTitle: englishTitle,
          simUrl: RosettaConstants.PRODUCTION_SERVER_URL + '/sims/html/' + simName + '/latest/' + simName + '_en.html',
          translationLocales: translationLocales,
          visible: simData.visible,
          version: projectInfo.version.string
        };
      } );
    } );
    timeOfLastUpdate = Date.now();
  }
}
```

</details>

I believe the sim info is being updated correctly, but I need to verify this with John.

**Comment by muedli** [comment]
Note to Self: It might make more sense to rename updateSimData to updateSimInfo, since that's how we're referring to it in comments. (This can be an es6plusify improvement.)

**Comment by muedli** [comment]
@jbphet and I talked and since "request" was only used in one function, we're going to scrap the idea of replacing it with "axios" and just use vanilla "https", which is what the rest of Rosetta uses. I will close this issue and delete this branch once I've got simData.js working with "https".

**Comment by muedli** [comment]
I've tried to use Node's built-in https module for this, but I keep getting an error that doesn't make sense to me.

`promise returned by updateSimData failed, error = TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object`

[Here's a link to the official documentation for https.request.](https://nodejs.org/api/https.html#https_https_request_url_options_callback)

Here's how I've set up a function to get the sim metadata.
```
async function getSimMetadata() {
  const options = {
    hostname: RosettaConstants.PRODUCTION_SERVER_URL,
    port: 443,
    path: '/services/metadata/1.2/simulations?format=json&type=html&include-unpublished=true&summary',
    method: 'GET',
    auth: {
      user: 'token',
      pass: global.config.serverToken
    }
  };
  const request = https.request( options, ( response ) => {
    console.log( 'statusCode:', response.statusCode );
    console.log( 'headers:', response.headers );
    response.on( 'data', ( data ) => {
      return data;
    } );
  } );
  request.on( 'error', ( error ) => {
    console.error( error );
  } );
  request.end();
}
```

It's set up the exact same way as in the documentation, but I'm still getting the error.

**Comment by jbphet** [comment]
I've taken a quick look at this, and I think the problem is that `getSimMetadata` isn't actually written as an async operation, meaning that there is no resolution of the promise when the data is received.  The handling of the response currently looks like this:

```js
    response.on( 'data', data => {
      return data;
    } );
```

...so I don't think the data actually goes anywhere, and the promise isn't resolved when it is received.  I think you'll need to either do some manual management of the promise behavior or use a package (like axios, which we previously considered) to accomplish this.  I found this article that might be helpful, though I only skimmed it myself: https://www.twilio.com/blog/5-ways-to-make-http-requests-in-node-js-using-async-await.

**Comment by muedli** [comment]
Among the dumb things I was doing here was

```
    auth: {
      user: 'token',
      pass: global.config.serverToken
    }
```

in the options parameter. This is what was producing the error that had me so befuddled. (It's supposed to be `auth: 'username:password'`.)

And @jbphet was right, I wasn't doing anything with the data, which is embarrassing. I believe I've remedied that in https://github.com/phetsims/rosetta/commit/fa1216283a325c109ba9ef9ad9a8c7b25862f415.

I've tested the above commit and I'm pretty sure it's working. If @jbphet looks upon my works and does not despair, then I think it's OK to close this issue and delete the "replace-request" branch.

**Comment by jbphet** [comment]
@muedli and I did a bit of a real-time review of the code during our weekly check-in meeting, and for the most part it's looking good.  I was concerned that the following bit of code in the `getSimMetadata` function in `simData.js`:

```js
      response.on( 'end', () => {
        try {
          const parsedData = JSON.parse( rawData );
          resolve( parsedData );
        }
        catch( error ) {
          winston.error( `Parsing metadata failed. Error: ${error}.` );
        }
      } );
    } );
```

I'm absolutely no expert on JavaScript promises, but it seems to me that since the function is creating an explicit promise, we may need to call the `reject` function in the `catch` block.  @muedli and I discussed this, and he is going to force the error and test the outcome.

I'm going to unassign myself until there are some updates.

**Comment by muedli** [comment]
I'm going to make sure there aren't more corner cases that we need to consider, but the error handling here is pretty much done. See https://github.com/phetsims/rosetta/issues/235#issuecomment-662724214.

**Comment by muedli** [comment]
I think, as of https://github.com/phetsims/rosetta/commit/8bab2d58f86fd3b6b5847c9031174465a7d49e19, the error handling is looking good. I'll review this with @jbphet on Monday.

**Comment by muedli** [comment]
Error logging is looking good as of https://github.com/phetsims/rosetta/commit/80ec5735086e41d357235f1b3307727c663006db. I think we can close this now.
