### ISSUE TITLE
Add better parameter validation for trigger-build

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#231]
As described in https://github.com/phetsims/perennial/issues/178, we recently had a situation where several translations were submitted but due to problems with the build server, they didn't get built and published.  I've added a route that supports this, but it's a little crude at this point, and we should add some better validation to make sure that it is a legitimate request before it is sent to the build sever.  See `routeHandlers.triggerBuild`.

**Comment by muedli** [comment]
- Look for sim name in metadata.
- Look for locales in localeInfo.js.
- Look at login and credentials to find userID.

**Comment by muedli** [comment]
Posted wrong link in commit message 🤦. Here's the commit I wanted to link: https://github.com/phetsims/rosetta/commit/8c1424bad3c5cf6f8c4a90b8764488082fd60da1.

**Comment by muedli** [comment]
The new plan for validating the userID is...

Get the sim's translation from Babel, get every userID from the file for the translation. Check that against the query parameter supplied. In most cases, there will only be one or two userID's. Plan B: Look at the login validation code to see if there's something you can use to validate the user ID. This will probably involve having Matt help me get a valid user ID from the web server. This isn't something we do in Rosetta.

**Comment by muedli** [comment]
JB and I just did an end-to-end test. It's working. Closing this issue.
