### ISSUE TITLE
Replace the now-deprecated 'request' package

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#232]
(Transferred to this repo from https://github.com/phetsims/website/issues/1072)

While working on https://github.com/phetsims/website/issues/1069, which is related to http requests, I learned that one of the packages that we are currently using, called `request`, is now deprecated.  See https://www.npmjs.com/package/request.  We should replace it.

There is an issue that describes some alternatives at https://github.com/request/request/issues/3143.  It mentions a package called `axios`, which sounds like it is very maintained, and I think I would start by taking a look at that one.  Either that, or see if what we need can be done with the built-in `https` module.

Assigning to @muedli since he's working on rosetta these days, and this seems like a great issue to get familiar with some of the underpinnings of the process.

**Comment by muedli** [comment]
Request package has been replaced. Error logging is looking good as of https://github.com/phetsims/rosetta/commit/80ec5735086e41d357235f1b3307727c663006db.

This was transferred from the website repo and was tracked in https://github.com/phetsims/rosetta/issues/228.
