### ISSUE TITLE
"SELECT NOW()" test succeeds, but "result.rows[ 0 ].now" is undefined

### ISSUE THREAD

**Issue by liammulh** [phetsims/rosetta#234]
On @jbphet's machine, we saw the `SELECT NOW()` test succeed, but somehow `result.rows[0]now` was undefined. Keep your eyes peeled. As of this writing, this database test is in rosetta.js.

**Comment by muedli** [comment]
I did some investigating of this issue, and I'm pretty sure it's a "sighting." That is, I think it's a rare bug that makes seemingly random appearances.

That being said, John and I found some peculiarities with the error logging. I'll add these notes to the documentation.

> For some reason, logging "error.stack" (which is how they have it in the docs) produces a slightly less verbose error message than logging "JSON.stringify(error)". Also, logging "error" seems to be the same as logging "error.stack".
¯\\\_(ツ)\_/¯. 
Docs can be found here https://node-postgres.com/api/pool#pool.query.

**Comment by liammulh** [comment]
We don't use Postgres in Rosetta 2.0.
