### ISSUE TITLE
Do we need explanations field for strings?

### ISSUE THREAD

**Issue by muedli** [phetsims/rosetta#239]
When originally designed, we envisioned the ability for translators to explain why they were changing a string so as to avoid arguments between translators. That was never implemented, but there is a field in the translation data structure for it and the value is always null. Do we still need this field? Would it be useful to get feedback from the translators?

**Comment by ariel-phet** [comment]
@muedli I think we can safely remove this field. So far our "trusted translator" model has worked quite well and we have not had a need for this potential feature. Feel free to remove this field.

**Comment by muedli** [comment]
Translations field removed. Closing.
