### ISSUE TITLE
routes.js should check if a specific locale.json exists before trying to open it when hitting 'Go'.

### ISSUE THREAD

**Issue by zepumph** [phetsims/rosetta#24]
I get these two errors when opening a new locale for translating a sim, non fatal but something that should be looked into.

error: request for translated strings for project example-sim failed. Response code: 404. URL: https://raw.githubusercontent.com/phetsims/babel/tests/example-sim/example-sim-strings_af.json. Error: null
error: request for translated strings for project joist failed. Response code: 404. URL: https://raw.githubusercontent.com/phetsims/babel/tests/joist/joist-strings_af.json. Error: null

**Comment by aaronsamuel137** [comment]
These errors are expected if these files don't exist on github. Nothing bad will happen - just means that the no strings will be found from github when trying to prepopulate the form.
