### ISSUE TITLE
Set up automated tests for Rosetta

### ISSUE THREAD

**Issue by liam-mulhall** [phetsims/rosetta#240]
We need to decide on a testing framework.

**Comment by muedli** [comment]
We've decided to use QUnit because we think it will work reasonably well for Rosetta and it is used by other PhET repositories.

**Comment by muedli** [comment]
Talk to JO about setting this up with Aqua.

**Comment by muedli** [comment]
Think about a more formal process for testing Rosetta.

**Comment by liam-mulhall** [comment]
This will be done (to some extent) in the new version of Rosetta.

**Comment by liam-mulhall** [comment]
This isn't a priority for Rosetta 2.0, so I'm going to close and we can re-open or make a new issue if/when we want to add tests.
