### ISSUE TITLE
Branch: personal-access-token

### ISSUE THREAD

**Issue by phet-dev** [phetsims/rosetta#246]
This is a branch that was created to allow us to fix #245 without having to pull the code off of master, which is currently not ready for prime time.

**Comment by muedli** [comment]
I accidentally submitted the issue as phet-dev.

**Comment by muedli** [comment]
This is a branch that we used to set up a GitHub personal access token for Rosetta. We also used this branch as a temporary stable branch to run Rosetta while we worked on #250. Now #250 is fixed, we no longer need this branch.
