### ISSUE TITLE
It would be nice to rewrite translate-sim.js

### ISSUE THREAD

**Issue by liam-mulhall** [phetsims/rosetta#247]
I'm in the process of eliminating instances of jQuery in Rosetta's code base. Right now, they're all in translate-sim.js. Anyway, I've noticed that translate-sim.js is kind of an unholy mess, and I'd like to rewrite it at some point. I'm not going to do it right now.

**Comment by muedli** [comment]
Question for @jbphet: What's the oldest browser we want to support for Rosetta? I see code in here for IE 8 and lower, but I don't think that some of the new ES6 JavaScript I'm adding is supported on these browsers.

**Comment by muedli** [comment]
According to our system requirements, we don't even support IE, so I'm wondering if I can get rid of that code.

**Comment by jbphet** [comment]
Yes, anything related to IE support can be removed.

**Comment by liam-mulhall** [comment]
At this point, this is a duplicate of https://github.com/phetsims/rosetta/issues/238. There used to be other instances of jQuery in the code base, but now it's all in translate-sim.js.
