### ISSUE TITLE
Possible hack attempt

### ISSUE THREAD

**Issue by muedli** [phetsims/rosetta#256]
I was checking Rosetta's logs today and I saw

```
Jan 28 12:17:49 phet-server.int.colorado.edu rosetta[3376]: URIError: Failed to decode param '%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/etc/passwd'
```

several times. I asked @mattpen about it and he said: "I can check the httpd logs to see if there is a common IP, and we can ask OIT to block it."

**Comment by muedli** [comment]
Assigning to @mattpen to check httpd.

**Comment by mattpen** [comment]
I think this was a "white hat" hacking attempt.

I'm seeing a lot of requests looking for vulnerabilities yesterday from 146.6.15.0 with a User agent of UT-Dorkbot/1.0.

This looks like a legitimate service: https://security.utexas.edu/dorkbot.  The IP is registered with UT Austin: https://ipinfo.io/146.6.15.0.

We get emails from places like this occasionally if they find vulnerabilities, so it actually has been useful to allow this in the past.  Closing.
