### ISSUE TITLE
Create script or route to indicate which strings still need to be translated

### ISSUE THREAD

**Issue by liam-mulhall** [phetsims/rosetta#259]
@kathy-phet mentioned the need for a script that spits out a CSV file for a sim containing the strings that haven't been translated for that sim.

@jbphet thinks it would be a good idea to create a subdirectory `scripts` in the `js` directory.

### Ideas

* Supply locale as command line argument. Generate CSV for all untranslated strings in that locale
* Spit out number of strings untranslated / number of strings translated for sim and locale.
  * Something along the lines of 88% of \<locale\> strings translated.
* CSV should look something like the below table:

| sim1       | sim2       | ... | simN       |
|------------|------------|-----|------------|
| sim1string1 | sim2string1 | ... | simNstring1 |
| sim1string2 | sim2string2 | ... | simNstring2 |
| ... | ... | ... | ... |

### Questions

* Should we make a CSV file for all locales?
* Something like:

| locale | sim1        | ... | simN        |
|--------|-------------|-----|-------------|
| ab     | sim1string1 | ... | simNstring1 |
|        | sim1string2 | ... | simNstring2 |
| ...    | ...         | ... | ...         |
| zh_TW  | sim1string1 | ... | simNstring1 |

This is a subset of this issue: 
https://github.com/phetsims/rosetta/issues/272

**Comment by liam-mulhall** [comment]
I'll need a list of published sims. Maybe get this from metadata.

**Comment by liam-mulhall** [comment]
See also #121.

**Comment by jbphet** [comment]
Also, it would be good to include a route for identifying which sims are completely untranslated for a given locale as part of this.  @liam-mulhall and I have already discussed this quite a bit, I just thought it would be good to put it into this issue.

**Comment by liam-mulhall** [comment]
This will be added in the new version of Rosetta.

**Comment by liam-mulhall** [comment]
The new epic is https://github.com/phetsims/rosetta/issues/284. Closing.
