### ISSUE TITLE
Allowing empty strings during translation

### ISSUE THREAD

**Issue by phet-steele** [phetsims/rosetta#26]
There was a decision made that prevents users from deleting previously translated strings and leaving them empty. I'm going to advocate for this to be reverted and instead allow empty strings. As I've been testing the functionality of the translation utility, I've found this behaviour incredibly frustrating and clunky. Simple mistakes can easily be made by the user, maybe translating the wrong thing then having to go back and delete the mistake only to have nothing change (as just one use case). Furthermore, with the case of malicious translating, I would think there are better workarounds than limiting the usability of everyone else. Also, this makes the saving behaviour somewhat confusing and potentially broken in the eyes of the user since any deleted strings reappear as being filled after the page has been reloaded.

If the decision is not made to revert this, I'd say we should at least make this behaviour more obvious to the user. For example, after a user has deleted some strings and submitted the translation, the debug info in the resulting form only shows strings that were changed and contain values, there is nothing saying that the empty strings will not be saved. A warning on this screen saying something like "Changes resulting in empty strings have not been saved/submitted" would make it more obvious to the user that they need to go back and fix those strings properly.

**Comment by aaronsamuel137** [comment]
Decided in 7/7 dev meeting to allow empty strings.

**Comment by aaronsamuel137** [comment]
I removed the empty check so empty strings can now be submitted. Only strings that have the same value as previously will not be submitted. Closing
