### ISSUE TITLE
Email addresses should not be logged

### ISSUE THREAD

**Issue by mattpen** [phetsims/rosetta#267]
While researching a build failure for a translation, I discovered that email addresses and first names are being logged in rosetta when a user logs in.  I think it is ok to log the user ID, but the PII should not be logged to comply with our future privacy policy.  Let me know if I should provide more context on why we should make this change.

**Comment by jbphet** [comment]
I think it should be pretty straightforward to remove the email information from the logging.  Leaving this to @liam-mulhall.  I don't think we need to make it into asterisks as @mattpen showed above, we can just leave it out entirely.

**Comment by liam-mulhall** [comment]
Done in https://github.com/phetsims/rosetta/commit/7939d28f73c6f419017d6adcd2f3e44b50c1cfb4.
