### ISSUE TITLE
Patch in string file typo fix

### ISSUE THREAD

**Issue by liam-mulhall** [phetsims/rosetta#269]
In https://github.com/phetsims/faradays-law/commit/63179e1b8c2ddb567710ab04e1f1a0cd8ea13234 and https://github.com/phetsims/faradays-law/commit/81f150c6bc0a690f206feba1304213c15899c49f, I fixed typos in the strings file that were causing problems in the new version of Rosetta.

For context, the new version of Rosetta gets the sim's HTML, then tries to parse the string JSON. It couldn't parse the JSON because the JSON wasn't valid. I'm not sure how the old version of Rosetta manages to circumvent this problem.

**Comment by jbphet** [comment]
I'm in agreement that users should be able to use the double quote character in strings.  @liam-mulhall - Is this a new problem that has come about because some of the refactoring that is being done?

**Comment by liam-mulhall** [comment]
I believe this issue is fixed. Closing.
