### ISSUE TITLE
Testing of strings should embed RTL control characters for RTL languages

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#27]
Rosetta provides users with the ability to test a translation as it is worked on.  It does this by launching the simulation and overriding the strings using query parameters.  Currently, this feature does not correctly display RTL strings.  For instance, if the following string in entered into the translation utility for the Persian language:

![rtl-persian-1](https://cloud.githubusercontent.com/assets/3082831/8489196/17c201ba-20d6-11e5-853a-3e632ed96f21.png)

...the string shows up like this:

![rtl-persian-2](https://cloud.githubusercontent.com/assets/3082831/8489205/2374423e-20d6-11e5-9f46-078071dcdefd.png)

The last paren is in the wrong place because the string is not seen as RTL all the way through.  This issue was dealt with in the RequireJS and built versions of the simulation by embedding characters to set the direction to RTL for the locales that require it, see https://github.com/phetsims/joist/issues/152.  The same thing needs to be done for the strings in the query parameter for testing RTL language translations.

I looked up the characters needed for this, and they are ```%E2%80%AB``` for pushing right-to-left embedding and ```%E2%80%AC``` for popping directional formatting, see http://www.fileformat.info/info/unicode/char/202b/index.htm and http://www.fileformat.info/info/unicode/char/202c/index.htm, respectively.

**Comment by aaronsamuel137** [comment]
Fixed. Assigning to @jbphet for review.

**Comment by jbphet** [comment]
I tested the behavior with two RTL languages (Persian and Hebrew) and regressing tested with two LTR languages (English and Armenian) and it appears to work correctly in all tested cases.  The commits also look reasonable, so all in all this looks great.  Closing.
