### ISSUE TITLE
Add Client-Side Testing Framework

### ISSUE THREAD

**Issue by liammulh** [phetsims/rosetta#271]
Most of PhET uses QUnit as a testing framework, so the backend of Rosetta will use QUnit.

We would like to use QUnit for the frontend, but React + QUnit isn't as idiomatic as React + Jest, so we may end up using Jest for the frontend.

**Comment by liam-mulhall** [comment]
I don't think we're going to do this. I'm going to close. We can re-open or make a new issue if/when we decide we want to test our client-side code.
