### ISSUE TITLE
Rosetta 2.0 design mockups

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/rosetta#274]
@liam-mulhall [here are the mockups we went over today (.ai)](https://drive.google.com/drive/u/2/folders/15ewte989-vcqOCBnG3nqaXMy8oG62TkZ)

**Comment by oliver-phet** [comment]
Nice Font awesome sort icons:
[Sort icon](https://fontawesome.com/v5.15/icons/sort)
[Sort down](https://fontawesome.com/v5.15/icons/sort-down?style=solid)
[Sort up](https://fontawesome.com/v5.15/icons/sort-up?style=solid)

**Comment by liam-mulhall** [comment]
@oliver-phet, should there be Test/Save/Submit buttons on the top and the bottom of the translation form (upon selecting a simulation)? Or only on the bottom? Or something else?

**Comment by oliver-phet** [comment]
> (1) Should there be Test/Save/Submit buttons on the top and the bottom of the translation form (upon selecting a simulation)? Or only on the bottom? Or something else?

The current utility has top and bottom, so I'd just keep that design (hopefully that's easiest)!
> 
> (2) Suppose you've just landed on `https://phet.colorado.edu/translate`. Do you just see a locale select or do you see the locale select and the translation report for the first sim in the locale select, Abkhaz (ab)? In other words, does the user need to open the select before they can see a translation report?

I think it would be best to have a null value like "Select" that the drop down defaults to. So a translator needs to explicitly select their locale to begin translating. I'm worried if we open the first by default we'll receive some accidental Abkhaz submissions.

**Comment by oliver-phet** [comment]
@liam-mulhall here are some updated design mockup based on the meeting last week! (Note: ignore the pared-down locale list, since we aren't doing [locale access per user](https://github.com/phetsims/rosetta/issues/301), that list will continue to contain all phet locales for now)

**Initial Screen**
- Split the sim list into two sections (Sims not yet translated into..., Sims translated into...)
- All columns sortable
![screen1](https://user-images.githubusercontent.com/5090275/181646551-6b1d88aa-06b7-4127-b437-c010af987b07.png)
- (Added) since there is a publication delay, should we show a "pending" message after a translator clicks publish?
![screen3c](https://user-images.githubusercontent.com/5090275/181646768-39f223f0-ba4f-49a7-9dfe-ff652472a0de.png)

**Translate sim screen**
- Untranslated strings are highlighted
- Clicking the [copy button](https://fontawesome.com/icons/clone?s=solid) copies the English string over.
![screen2a](https://user-images.githubusercontent.com/5090275/181646575-1dc82cb4-c07d-4c1a-a74a-b86287ceb866.png)
- Discard changes dialog
![screen2b](https://user-images.githubusercontent.com/5090275/181646601-3a228c22-1f7d-4029-9512-020c8a834af4.png)
- Confirm publication dialog
![screen3b](https://user-images.githubusercontent.com/5090275/181646627-7df48334-cf72-439a-8d53-7002c835f7c1.png)
- Save message
![screen3d](https://user-images.githubusercontent.com/5090275/181646667-d97aae57-a4fb-4e4c-8526-4ccf2fe15fbb.png)
- (Added) "Hide translated strings" checkbox. This seems like it would be very useful.
![screen3d](https://user-images.githubusercontent.com/5090275/181646803-2cd38285-82a9-42bb-b034-076679732faa.png)

**Comment by liam-mulhall** [comment]
Thanks, @oliver-phet! These look great. :)

**Comment by oliver-phet** [comment]
Another update after getting feedback from Amanda and Amy in website meeting:

I had preserved the simplified navigation at the top of the Translation Utility pages, but I'm realizing that now that we have a "discard changes" warning, I'm less concerned about users inadvertently navigating away during translation. Can you plan to just reuse the existing persistent navigation that the rest of the website uses? (Maybe consult @mattpen or @chrisklus)
<img width="800" alt="image" src="https://user-images.githubusercontent.com/5090275/182469302-4ff2a4c1-f45f-4683-8e56-8d4f806ab660.png">

**Comment by oliver-phet** [comment]
[Design mockups](https://drive.google.com/drive/u/2/folders/15ewte989-vcqOCBnG3nqaXMy8oG62TkZ) have been updated to reflect meeting yesterday!

**Comment by liammulh** [comment]
Done.
