### ISSUE TITLE
Allow translation of prototype simulations

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#277]
@oliver-phet joined the weekly review of the translation utility status today, and requested that we start to allow the translation of prototype simulations.  According to him, we are going to start making these more visible on the website and, when we do, we should enable translation of them.

@liam-mulhall is in the process of rewriting rosetta to use react, but he estimates at least 3 to 4 weeks until this is ready to deploy, so we decided to investigate enabling this capability in the current incarnation of the utility.  I said I'd investigate how to do this and communicate my findings.

**Comment by jbphet** [comment]
I just looked at the metadata for the sims, and it looks like the field `visible` is what is used to designate a sim as a prototype.  In other words, if `visible` is set to `false`, the sim is a prototype and not fully shown to users on the main website.  Here is an excerpt that shows the Greenhouse Effect, which is currently considered a prototype, and Hooke's Law, which is fully published (I removed most of the translation data for Hooke's Law for brevity):

```json
    {
      "visible": false,
      "name": "html/greenhouse-effect",
      "supportsXhtml": true,
      "id": 204,
      "xhtmlFile": "https://phet.colorado.edu/sims/html/greenhouse-effect/latest/xhtml/greenhouse-effect_all_phet.html",
      "type": "html",
      "version": {
        "string": "1.0.2",
        "major": 1,
        "minor": 0,
        "dev": 2,
        "timestamp": 0
      },
      "simulations": [
        {
          "visible": false,
          "name": "greenhouse-effect",
          "id": 244,
          "localizedSimulations": [
            {
              "translateTime": "2021-09-24 11:29:18.196",
              "id": 11506,
              "locale": "en",
              "title": "Greenhouse Effect"
            },
            {
               "comment": "Other translations removed for brevity"
            }
          ]
        }
      ]
    },
    {
      "visible": true,
      "name": "html/hookes-law",
      "supportsXhtml": false,
      "id": 138,
      "type": "html",
      "version": {
        "string": "1.0.25",
        "major": 1,
        "minor": 0,
        "dev": 25,
        "timestamp": 0
      },
      "simulations": [
        {
          "visible": true,
          "name": "hookes-law",
          "id": 178,
          "localizedSimulations": [
            {
              "translateTime": "2020-01-22 23:39:45.229",
              "id": 10289,
              "locale": "tr",
              "title": "Hooke Kanunu"
            },
            
          ]
        }
      ]
    }
```

Note the settings of the `visible` field in two places.

In rosetta, in `simData.getSimTranslationPageInfo`, there is a parameter called `includeUnpublished`.  If we invoke all usages of this method with a parameter value of `true`, I believe the prototypes will be show.

This is a very minor change, but there is some question of whether we could make this change on master and then use that version as the primary server.  We may end up needing to do a branch.

**Comment by jbphet** [comment]
@oliver-phet - Let me know when the prototype changes that you described are live, and I'll go ahead with figuring out how to make this change to rosetta on the main server.

**Comment by oliver-phet** [comment]
@mattpen Can you confirm that the `visible` field is what we use to identify sims as prototypes?

**Comment by mattpen** [comment]
I think the changes to accomodate the breaking changes would be minimal.  Basically, the localizedSimulations object changed from an array of objects with locale and title properties, to an object whose keys are the locales and the values are objects with a title property.

Example (Hooke's Law, en and es only):
1.3:

```
"localizedSimulations": {
        "en": {
          "title": "Hooke's Law",
          "isCheerpj": false
        },
        "es": {
          "title": "Ley de Hooke",
          "isCheerpj": false
        }
      },
```

1.2:

```
"localizedSimulations": [
      {
        "id": 6018,
        "title": "Hooke's Law",
        "translateTime": "2016-11-09 20:28:01.31058",
        "locale": "en"
      },
      {
        "id": 7108,
        "title": "Ley de Hooke",
        "translateTime": "2016-11-09 20:28:01.31058",
        "locale": "es"
      }
    ]
```



<details>

<summary>
Here's a patch that I think would work (untested).  Mostly it is just reworking the for loop for iterating on localized sims.
</summary>

```
Index: js/simData.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/simData.js b/js/simData.js
--- a/js/simData.js	(revision 3489ccf12e47efe7a4b34ec644de999aec9d8aa9)
+++ b/js/simData.js	(date 1642791782844)
@@ -25,7 +25,7 @@
 };
 const PRODUCTION_SERVER_URL = global.config.productionServerURL;
 const METADATA_URL = `${PRODUCTION_SERVER_URL
-}/services/metadata/1.2/simulations?format=json&type=html&include-unpublished=true&summary`;
+}/services/metadata/1.3/simulations?format=json&type=html&include-unpublished=true&summary`;
 
 //===========================================================================//
 // Set up variables for later use.                                           //
@@ -79,18 +79,18 @@
         const simName = simulationInfo.name;
         const translationLocales = [];
         let englishTitle = '';
-        simulationInfo.localizedSimulations.forEach( localizedSimData => {
-          translationLocales.push( localizedSimData.locale );
-          if ( localizedSimData.locale === 'en' ) {
-            englishTitle = localizedSimData.title;
+        for ( let locale in simulationInfo.localizedSimulations ) {
+          translationLocales.push( locale );
+          if ( locale === 'en' ) {
+            englishTitle = localizedSimData[ locale ].title;
           }
-        } );
+        }
 
         simInfoObject[ simName ] = {
           englishTitle: englishTitle,
           simUrl: `${PRODUCTION_SERVER_URL}/sims/html/${simName}/latest/${simName}_en.html`,
           translationLocales: translationLocales,
-          visible: simulationInfo.visible,
+          visible: simulationInfo.visible || simulationInfo.isPrototype,
           version: projectInfo.version.string
         };
       } );

```

</details>

**Comment by jbphet** [comment]
Assigning this issue back to me for more investigation.  I'll try the 1.3 metadata locally, see how it works and how significant the changes are to switch to it, and we can go from there.

**Comment by oliver-phet** [comment]
@jbphet I noticed the Prototypes have been [translated into Portuguese (Brazil)](https://phet.colorado.edu/en/simulations/filter?locale=pt_BR&type=prototype). Was this intentional? The translator who submitted is NOT a team member.

**Comment by jbphet** [comment]
> @jbphet I noticed the Prototypes have been translated into Portuguese (Brazil). Was this intentional? The translator who submitted is NOT a team member.

Interesting.  No, I haven't done anything on this yet.  I'll spend some time today and see what I can figure out.

**Comment by jbphet** [comment]
@oliver-phet - I believe you have a login that is set up as a trusted translator and not a team member.  Can you please log in with those credentials and let me know if you see Greenhouse Effect on the list of sims that are available for translation?  I'm trying to figure out how it got translated, and it's all a bit mysterious at this point.

**Comment by oliver-phet** [comment]
No - Greenhouse Effect (nor other prototypes) are visible in the list. This was tested using a non-team member translator account.

**Comment by jbphet** [comment]
I just did some experimentation with the 1.3 metadata format, and the structure is slightly different, and as far as I can tell it doesn't include version information for the sim.  The 1.2 format _did_ include this, and rosetta uses it.  So, we either need to add version into to 1.3 or `isPrototype` to the 1.2 to get it all to work.

Also, in my experimentation, I found that my attempts to retrieve metadata on my machine using what I believe to be the correct flags returned data that did not include unpublished sims.  I'll need to work with @mattpen to figure this out.

**Comment by jbphet** [comment]
@mattpen - I removed the `summary` query parameter, and am able to see the version information in the 1.3 metadata now, which is great.  However, I'm a little concerned about the size of this data and the time it takes to get it.  I tested on phet-sever, and it takes about 4 seconds, which isn't bad, bit it may make some pages a bit slow if users trigger an update of the local copy of the data.  And, when I made this request from my local machine, it took 38 seconds.  This is a bit of an impediment to local testing of rosetta, which we do frequently, since it has to grab the metadata on each restart.  Are there any other query parameters we could use to get less data?  Is there some other approach that you can envision?

**Comment by mattpen** [comment]
You could limit the data with locale=en, but then you would need to make 2 requests I think.  One for a summary of all locales and one for complete data of just English. That seems silly. 

 I think the best solution is to just add the version data back into the summary for 1.3. That shouldn't add too much bloat. It'll take a bit to get that change up in production,  though.

**Comment by jbphet** [comment]
> I think the best solution is to just add the version data back into the summary for 1.3.

Sounds good to me.  Let me know when it's ready and I'll give it a try.

**Comment by oliver-phet** [comment]
@mattpen do you have an ETA on getting the version data back into the 1.3 summary?

**Comment by mattpen** [comment]
OK, @jbphet the version summary should now be available in the 1.3 summary.  Sorry for the delay, can you please check on your side.

**Comment by jbphet** [comment]
I just checked and can see both the version information and the `isPrototype` flag.  This looks good as far as I can tell, and I'll try incorporating it into Rosetta next.

**Comment by jbphet** [comment]
I've implemented support for translation of prototypes on the master branch of Rosetta.  Since we are going to cut over to a new server in a couple of days, I'm going to make this feature available at the time of the cutover, since it will take less of my time that way.  If everything goes as planned, this functionality should go online on Sunday March 13 2022.

**Comment by jbphet** [comment]
I've assigned this to @liam-mulhall, since he'll need to make sure that this is supported in the reacted-based version on rosetta on which he is working.  The commit list above should be helpful for that.

**Comment by oliver-phet** [comment]
> I've implemented support for translation of prototypes on the master branch of Rosetta. Since we are going to cut over to a new server in a couple of days, I'm going to make this feature available at the time of the cutover, since it will take less of my time that way. If everything goes as planned, this functionality should go online on Sunday March 13 2022.

Woohoo! I'll look out for confirmation next week then send an announcement to translators.

**Comment by jbphet** [comment]
I just tested the version of Rosetta that includes support for prototype translation by accessing it on ox-dev, which currently resolves to phet-server2.  I logged in as a user that is a trusted translator but is not a team member and, as expected, saw the prototype sims in the translation list, such as greenhouse-effect and geometrics optics, and did _not_ see the invisible sims, such as chains and example sim.  When I logged out and then back in as myself, I saw the invisible sims too.  Bottom line: This is behaving correctly as far as I can tell, and we're good to move forward with publishing it.

**Comment by jbphet** [comment]
We've cut over to the new server, so support for translation of prototypes should now be available to our translators.  @oliver-phet - you can send out your email whenever you're ready.  Once that's done, please leave this issue open and assigned to @liam-mulhall so that he can make sure this capability is supported in rosetta-react.

**Comment by oliver-phet** [comment]
Translators have been notified that prototypes are now available in the utility.

**Comment by liammulh** [comment]
This is done.
