### ISSUE TITLE
Add a route to obtain SHA of code running in a given instance of Rosetta

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#278]
The SHA is logged at startup in the output log, but while working on some maintenance recently, it occurred to be that it would sure be nice to just get the SHA from a URL instead of having to search through logs.

**Comment by jbphet** [comment]
I've added this functionality to the main, non-react version.  Assigning to @liam-mulhall to add it to the react version.

**Comment by liam-mulhall** [comment]
Done in https://github.com/phetsims/rosetta/commit/dc74eb4d14fc5f54d20ade424212f6ee1c8f72ec and https://github.com/phetsims/rosetta/commit/cd907fb1d14ddd4dd06cb0201734477c190afc92.
