### ISSUE TITLE
RTL strings don't show up correctly on the "Translation submitted" page

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#28]
When a translation is submitted in Rosetta, and page is shown that details what exactly was submitted.  Currently, RTL languages don't correctly display the translated strings.  For example, if the following Persian string is submitted on the translation page:

![rtl-persian-1](https://cloud.githubusercontent.com/assets/3082831/8489346/d732bd9a-20d7-11e5-9f11-333ec10b6604.png)

...the following is shown on the "Translation submitted" page:

![rtl-persian-3](https://cloud.githubusercontent.com/assets/3082831/8489355/e9107dae-20d7-11e5-9db9-3c25a59b0a17.png)

@aaronsamuel137 and I talked about this, and while we're not entirely sure that this page will be kept in the final version, it seems like there is a good chance that it will be, so it's probably worth fixing.

**Comment by aaronsamuel137** [comment]
This should be fixed now. Feel free to review or close @jbphet.

**Comment by jbphet** [comment]
Tested on the currently running version of Rosetta, and this appears to work fine.  Commits look good.  Closing.
