### ISSUE TITLE
admin-guide.md and implementation-notes.md need an update

### ISSUE THREAD

**Issue by mattpen** [phetsims/rosetta#280]
These two files both reference phet-server as the main production machine, which is set to change very soon.  This documentation should be updated to reference phet-server2 as the primary backend and phet-server as the secondary backend (which should host rosetta in maintenance-mode permanently).

Assigning @jbphet @liam-mulhall - happy to help if needed.

**Comment by liam-mulhall** [comment]
There will be an up-to-date guide in the new version of Rosetta.

**Comment by liam-mulhall** [comment]
The title "admin-guide.md and implementation-notes.md need an update" makes this specific to old Rosetta.

**Comment by jbphet** [comment]
I updated references to phet-server to phet-server2.  I did some other minor editing, but not a ton, since there will be a new round of documentation that comes along with Rosetta 2.0, as @liam-mulhall mentions above.  I think that should suffice, closing.
