### ISSUE TITLE
Test Rosetta with Node 16

### ISSUE THREAD

**Issue by mattpen** [phetsims/rosetta#282]
@jbphet @liam-mulhall - we should test rosetta with Node 16 to make sure it is compatible. Node 16 is installed on phet-server-dev, so we should be able to test this at https://ox-dev.colorado.edu/translate.  Node 16 is now the LTS version of node, and we are upgrading it to solve some problems in https://github.com/phetsims/chipper/issues/1171#issuecomment-1088978203.

**Comment by jbphet** [comment]
@mattpen - What is your time frame for upgrading to Node 16 on phet-server2?  Knowing this will help @liam-mulhall and I to prioritize and schedule this work.

**Comment by mattpen** [comment]
I had to upgrade node to 16 on a high priority for the build-server today, but it looks like rosetta can use 14 for the time being by referencing the old executables in nvm's version directory.  I'm not sure this is a good long term solution, so it would be nice to get this done sooner if possible.

**Comment by jbphet** [comment]
@mattpen - I just pulled the latest Rosetta code onto phet-server-dev and restarted the server process there using systemctl, and I can see by tailing the logs and messing around at https://ox-dev.colorado.edu/translate that interaction is occurring.  However, Rosetta records the Node version that it's running on in its log when it starts up, and that line says:

```
Apr 19 15:47:26 phet-server-dev.int.colorado.edu rosetta[39001]: info - Node Version v12.22.9
```

Running `node --version` from the command line yields the result `v16.14.2`, so it seems like the systemctl configuration has Rosetta running on an older version of Node.  I'm not sure how to change this.  Can you make the change and let me know, and then I'll finish this testing?

**Comment by mattpen** [comment]
I changed `/usr/bin/node` to `/usr/local/bin/node` in /usr/lib/systemd/system/rosetta.service.  This should cause rosetta to run with node 16, sorry I missed this.  Back to @jbphet and @liam-mulhall for testing.

**Comment by jbphet** [comment]
@mattpen - I just tested on ox-dev and everything seemed to work fine.  Feel free to switch to Node 16 on the main server and let me know when you've done it, and I'll take a look there.

For my reference, I tested all of the basic UI interactions, but I didn't submit an actual translation, since the server was configured to submit to master and to make build requests.

**Comment by mattpen** [comment]
I updated rosetta to use 16.14.2 on phet-server2 and restarted it.  Looks like it started successfully:

```
$ sudo systemctl status rosetta
● rosetta.service
   Loaded: loaded (/etc/systemd/system/rosetta.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2022-05-12 15:39:08 MDT; 6s ago
 Main PID: 3056099 (node)
    Tasks: 11 (limit: 1646332)
   Memory: 50.3M
   CGroup: /system.slice/rosetta.service
           └─3056099 /home/phet-admin/.nvm/versions/node/v16.14.2/bin/node /data/share/phet/rosetta/js/rosetta.js

May 12 15:39:08 phet-server2.int.colorado.edu rosetta[3056099]: info - Testing database connection...
May 12 15:39:08 phet-server2.int.colorado.edu rosetta[3056099]: info - locale info data was stale, initiating a new request
May 12 15:39:08 phet-server2.int.colorado.edu rosetta[3056099]: info - Requesting locale info file from GitHub. URL: https://raw.githubusercontent.com/phetsims/chipper/master/data/localeInfo.json
May 12 15:39:08 phet-server2.int.colorado.edu rosetta[3056099]: debug - Sim data was stale. Initiating a new request.
May 12 15:39:09 phet-server2.int.colorado.edu rosetta[3056099]: info - Listening on port 16372.
May 12 15:39:09 phet-server2.int.colorado.edu rosetta[3056099]: info - Open your browser to http://localhost:16372/translate
May 12 15:39:09 phet-server2.int.colorado.edu rosetta[3056099]: info - Database test using SELECT NOW() succeeded. Now: Thu May 12 2022 15:39:09 GMT-0600 (Mountain Daylight Time)
May 12 15:39:09 phet-server2.int.colorado.edu rosetta[3056099]: info - initial population of localeInfo object complete
May 12 15:39:09 phet-server2.int.colorado.edu rosetta[3056099]: debug - Metadata successfully retrieved!
May 12 15:39:09 phet-server2.int.colorado.edu rosetta[3056099]: info - Initial population of simInfoObject complete.
```

**Comment by jbphet** [comment]
I ran a test where I updated the `ab` locale of the Chains sim, and it looks like everything worked fine.

I'll add a reminder to check early next week that we got some successful translations, and then I think we can safely close this.

For reference, here are two entries from Rosetta's log that show the Node version and the SHA that were tested:

```
May 12 15:39:08 phet-server2.int.colorado.edu rosetta[3056099]: info - Node Version v16.14.2
May 12 15:39:08 phet-server2.int.colorado.edu rosetta[3056099]: info - Current SHA is f1ad91a782b1a5ba460834ac4583155656
```

**Comment by jbphet** [comment]
I checked the logs and the main website this morn, and it appears that several translations have been successfully submitted and deployed since the change to Node 16, so I think we can safely close this issue.
