### ISSUE TITLE
Branch: `rosetta_2.0_main`

### ISSUE THREAD

**Issue by liammulh** [phetsims/rosetta#285]
This branch is for the development of Rosetta 2.0. See https://github.com/phetsims/rosetta/issues/284.

**Comment by liam-mulhall** [comment]
We initially thought we were going to create this branch and transfer code from my fork to this repo manually, but then we decided to rebase my fork from master and then push the rebased fork to this repo. Thus, this branch will be deleted once I integrate its monorepo structure into the new branch that was rebased and pushed.

**Comment by liammulh** [comment]
@samreid and I removed this branch today.
