### ISSUE TITLE
Add form validation equivalent to what current Rosetta has

### ISSUE THREAD

**Issue by liammulh** [phetsims/rosetta#289]
If there is a pattern in your string key, the user's input should match the pattern. This is a feature in Rosetta 1.0 that we want in Rosetta 2.0.

Consider the following:

<img width="722" alt="example" src="https://user-images.githubusercontent.com/60749003/179061093-a72b962f-797e-43c6-bba5-24b31038e8e4.png">

If you add a pattern that doesn't conform to the string key, this is what you'll see:

<img width="760" alt="warning-icon" src="https://user-images.githubusercontent.com/60749003/179061169-31921311-5a4f-47b9-9601-dc8122bec1cd.png">

If you click the warning icon, you'll see the following alert:

<img width="445" alt="alert" src="https://user-images.githubusercontent.com/60749003/179061229-3ab2d0ca-cd74-4522-a267-82f8dfb7d4ed.png">

**Comment by liam-mulhall** [comment]
See if there are any old GitHub issues having to do with form validation that can be incorporated into this issue.

**Comment by liammulh** [comment]
Done.
