### ISSUE TITLE
list of languages should be sorted by name and not locale

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#30]
The languages in the "Select Target Language" combo box are currently sorted by locale ID and not by the name of the language, which results in some some odd-looking ordering.  The screenshot below illustrates, and I've highlighted the languages that look out of order.  It would be much more user friendly to sort by language name.

![rosetta-language-order](https://cloud.githubusercontent.com/assets/3082831/8555569/2b393c0a-24ae-11e5-94c3-29d84c972288.png)

**Comment by aaronsamuel137** [comment]
Fixed. Assigning to @jbphet for review.

**Comment by jbphet** [comment]
Looks great, thanks.  Closing.
