### ISSUE TITLE
Add method for notifying users of updated strings

### ISSUE THREAD

**Issue by liammulh** [phetsims/rosetta#302]
We want a way to tell a user if a string has been updated, so they can make the appropriate changes to a translation.

@oliver-phet, @kathy-phet:

1. Is this something we want in Rosetta 2.0?
2. I need this to be more concrete. I need design and requirements.
    * Is this an icon next to the English string?
    * Does the user see that there's an updated string in the translation report (i.e. do they see this in the overview page, not the actual translation form)?

Similar to https://github.com/phetsims/rosetta/issues/212.

**Comment by oliver-phet** [comment]
Hey @liam-mulhall I thought we had decided last week that it would be quite difficult to separately identify if/when a string is either "new" or "updated". Instead, we were just going to identify translated/untranslated strings.

**Comment by liam-mulhall** [comment]
Ah, yeah I remember now. Sorry, I think the notes I took were from before we made that decision. I will leave this issue open as it's something we might eventually want, but I won't add it to Rosetta 2.0.

**Comment by oliver-phet** [comment]
This will be accomplished in #417
