### ISSUE TITLE
CT 'SEND_BUILD_REQUESTS' is assigned a value but never used no-unused-vars

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/rosetta#310]
```
rosetta : lint
Lint failed with status code 1:
Running "lint" task

/data/share/phet/continuous-testing/ct-snapshots/1662721214770/rosetta/js/stringSubmissionQueue.js
21:7 error 'SEND_BUILD_REQUESTS' is assigned a value but never used no-unused-vars

✖ 1 problem (1 error, 0 warnings)

Fatal error: Lint failed
Snapshot from 9/9/2022, 5:00:14 AM
```

**Comment by jbphet** [comment]
I believe that this was already fixed in https://github.com/phetsims/rosetta/commit/37ac1ae8ac641dbb97153d70e087de41c2c82249, but CT hasn't re-run since the change was submitted.  I'll keep an eye on it, but I suspect there will be nothing else that needs to be done.

**Comment by jbphet** [comment]
CT is now clear, see screenshot below.  Closing.

![image](https://user-images.githubusercontent.com/3082831/189422668-3ff03bb0-4fd5-4eed-b85d-fcb5891c9490.png)
