### ISSUE TITLE
Make sure email sends are up to date

### ISSUE THREAD

**Issue by mattpen** [phetsims/rosetta#315]
It looks like rosetta is sending automated emails using phetmail@colorado.edu.  We need to make a few updates.  

- We should change the email server to `smtp.office365.com`
- We need to make sure that `starttls` is enabled and that it supports TLS 1.2
- We should authenticate with `phetmail@colorado.edu` and not just `phetmail` for the username.

I think this needs to happen at a fairly high priority, like prior to mid-october. I'm going to work on this on the build-server today and Monday and I'm happy to help.

**Comment by liammulh** [comment]
Looking at the code, I don't think rosetta is actually sending emails. It could if we wanted it to, but I don't think it is.

So I'm wondering if this work is necessary if we aren't currently sending emails.

**Comment by liammulh** [comment]
I think it's @jbphet's call since he's the owner.

**Comment by jbphet** [comment]
I certainly don't recall receiving any automated emails from Rosetta, at least not recently, so I'm not surprised that the code to send them is currently unused.  Let's just delete it, and if we decide that we need support for sending automated emails in the future, we will work with @mattpen then to make it happen.  I don't anticipate such a need soon.

I'll take care of removing the current code.

**Comment by jbphet** [comment]
The email-related code has now been removed.  Closing.

**Comment by jbphet** [comment]
For the record, after I removed the email-related code, I check my local config file as well as those on the main server and the development server, and none of them had any values that appeared to be related to email support, so no modifications were necessary.
