### ISSUE TITLE
Recently committed strings won't show up in translation utility for ~5 min.

### ISSUE THREAD

**Issue by liammulh** [phetsims/rosetta#316]
In developing and testing Rosetta 2.0, @jbphet and I noticed that our recently committed strings weren't showing up in the translation utility immediately. That is, we would go into the translation form, make some changes, submit those changes, and then go back to the form expecting to see said changes to no avail. The old string would still be there. After a while, the new string would show up.

We initially thought this might be an issue with either our client-side code or our server-side code, but we narrowed it down to being an issue with getting the strings from GitHub. To get translated strings that we present to the user in the translation form, we issue an HTTP request to raw.githubusercontent.com (with the correct path to the file in phetsims/babel, of course) using the Axios library. The file on GitHub is updated immediately after we submit, but apparently GitHub caches requests to raw.githubusercontent.com (at least according to [this SO answer](https://stackoverflow.com/a/55615178)). We googled around to see if perhaps there was a way to bypass this caching, but (at least according to [this other SO answer](https://stackoverflow.com/a/62786202)) there is no way to bypass it.

Ideally, a user of the translation utility would be able to see recently committed strings immediately. That being said, we've never had any complaints about it. For now, we are not going to fix this issue. If/when we get complaints about this, we can look into fixing it.

**Comment by Nancy-Salpepi** [comment]
This looks good in https://github.com/phetsims/qa/issues/931. I tested using Italian with CG and Concentration --making changes to (sim-specific, common, and shared strings).

**Comment by liammulh** [comment]
We ended up fixing this by using Octonode to interface with GitHub. Deployed in https://github.com/phetsims/rosetta/commit/6021626a17d44d4a05a0be5cb4a3cbf1a41ccb17 (2.0.7).
