### ISSUE TITLE
Update check-login endpoint

### ISSUE THREAD

**Issue by mattpen** [phetsims/rosetta#319]
@jbphet @liammulh - I'm in the process of overhauling the user authentication services for phet.  One thing that is changing is the endpoint for the Check Login feature.  We'll need to coordinate this change with rosetta as well.

Production:
https://phet.colorado.edu/services/check-login -> https://phet-direct.colorado.edu/user/check-login

Test:
https://ox-dev.colorado.edu/services/check-login -> https://phet-direct-dev.colorado.edu/user/check-login

There shouldn't be a change in the API; you should be able to parse the response exactly the same way.  There will just be a new target for the http request that checks the login status.  It looks like in the master branch this only affects `ensureValidSession.js`, but I did not search across branches.

I'm planning on the change happening sometime in January or February, but it is already in place on ox-dev today (but likely not permanently). I'll try to remember to update this issue when I have a better idea of the timing.  Let me know if you have any questions.

**Comment by liammulh** [comment]
This is done in Rosetta 2.

**Comment by jbphet** [comment]
@mattpen - Does this need to be done for Rosetta 1, or can we leave it as is, since we expect that it will likely be retired in favor of Rosetta 2.0 in January?

**Comment by mattpen** [comment]
>  Does this need to be done for Rosetta 1

I think we should wait and see. I strongly suspect that Rosetta 2.0 will be ready before the new user services.

**Comment by liammulh** [comment]
Hey, @mattpen, JB and I are wondering if the sign-in page we see on Ox-Dev is going to eventually look better? I assume so, but just want to double check.

<img width="795" alt="sign-in" src="https://user-images.githubusercontent.com/60749003/209020809-25942713-0f40-48a0-a95e-430b09abd156.png">

**Comment by mattpen** [comment]
Yes, right now it has basically no custom CSS yet, that will change before this is published for sure.

**Comment by jbphet** [comment]
I'm going to unassign myself since there isn't anything that we need to do for Rosetta 1, and @liammulh has done it for Rosetta 2.0.  If the new user services _are_ in fact ready before Rosetta 2.0 is deployed, please assign this back to me and I'll work on it.

**Comment by liammulh** [comment]
@mattpen please re-assign me when the switch is made so I can update the endpoint in Rosetta's config file.

**Comment by liammulh** [comment]
This is done.
