### ISSUE TITLE
Should Apache httpd be used for Rosetta?

### ISSUE THREAD

**Issue by liammulh** [phetsims/rosetta#320]
@mattpen, how hard would it be to use Apache httpd for Rosetta instead of Varnish?

<hr/>

## Background

Today, @mattpen and I discussed using Apache httpd for Rosetta instead of Varnish Cache.

Varnish probably shouldn't be used for Rosetta since the data in Rosetta changes frequently, and the traffic to Rosetta is relatively low.

Another issue with using Varnish is that our [server sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events) for the translation report can't been seen streaming in. Varnish waits until the response ends before anything is sent on to Rosetta.

One solution @mattpen and I discussed was using Apache httpd for Rosetta instead of Varnish so that we could see the translation report objects streaming in.

@jbphet and I discussed this today, and if it's not too difficult, we'd like to see if Apache httpd would allow us to see the objects streaming in.

**Comment by mattpen** [comment]
@liammulh - this should be working now, I checked https://ox-dev.colorado.edu/translate/report/fr and it was loading the sim completion statuses one by one as you demonstrated earlier today.

**Comment by liammulh** [comment]
@mattpen, @jbphet and I are not seeing the incremental server sent events on phet-server2. Do we need to redo this on phet-server2?

**Comment by liammulh** [comment]
@mattpen is going to run a script to do this tonight.

**Comment by mattpen** [comment]
I deployed the httpd config change to production. The Server Sent Events parts are now working in Rosetta 2.0.

**Comment by jbphet** [comment]
Thanks @mattpen - I just tried it and the incremental loading is working well!
