### ISSUE TITLE
Don't build phet-io brand if there is a version suffix

### ISSUE THREAD

**Issue by liammulh** [phetsims/rosetta#322]
Today, @kathy-phet and @jonathanolson brought our attention to the fact that a phet brand sim was deployed as an active phet-io sim. The reason this happened is that [in `requestBuild.js`](https://github.com/phetsims/rosetta/blob/7ab85e5344377ee7367ebdb75907ddcc30eab19c/js/requestBuild.js#L64), we have the following:

```js
  // See if there is a published phet-io version of the sim we are requesting a build for. If so, add the phet-io brand
  // to the list of brands we are requesting to build. For the history of this, see:
  // https://github.com/phetsims/phet-io/issues/1874.
  const phetioSims = await simPhetioMetadata( { active: true, latest: true } );
  const brands = [ 'phet' ];
  for ( let i = 0; i < phetioSims.length; i++ ) {
    const phetioSim = phetioSims[ i ];
    const phetioSimVersion = new SimVersion( phetioSim.versionMajor, phetioSim.versionMinor, phetioSim.versionMaintenance );
    const nameAndVersionAreSame = phetioSim.name === simName &&
                                  phetioSimVersion.major === simVersionObject.major &&
                                  phetioSimVersion.minor === simVersionObject.minor;
    if ( nameAndVersionAreSame ) {
      brands.push( 'phet-io' );
    }
  }
```

The sim charges-and-fields has a 1.0 phet brand branch and a 1.0-phetio phet-io brand branch. Thus, our check above added both phet and phet-brand to the list of brands to include in the build request object. That build request made it so that a phet brand charges-and-fields 1.0 was deployed as the active charges-and-fields phet-io sim.

In order to fix this, we need to add a check for a version suffix, and not include the phet-io brand in the array of brands if the version suffix is present.

**Comment by jbphet** [comment]
For reference, the issue where the feature was added that requests the phet-io brand when it is present is https://github.com/phetsims/phet-io/issues/1874.

**Comment by jbphet** [comment]
I've added code to prevent building the phet-io brand when the matching phet-io metadata has a version suffix, tested it locally on my machine, deployed it to the primary server, and tested it there by executing a trigger build on charges-and-fields and verifying that it only requested the phet brand, and not phet io.  Here are a couple snippets from the build server log:

Excerpts from build server log before change (this was a recent translation build):
```
Nov 28 09:14:24 phet-server2.int.colorado.edu build-server[2767]: info: building sim charges-and-fields
.
.
.
Nov 28 09:15:10 phet-server2.int.colorado.edu build-server[2767]: info: building for brands: phet,phet-io version: 1.0.50
```

...and after change (this was from my trigger build request):
```
Dec 09 16:52:17 phet-server2.int.colorado.edu build-server[1414679]: info: building sim charges-and-fields
.
.
.
Dec 09 16:52:54 phet-server2.int.colorado.edu build-server[1414679]: info: building for brands: phet version: 1.0.50
```

**Comment by liammulh** [comment]
@jbphet, the logic for your code in https://github.com/phetsims/rosetta/commit/fc63c52d92f3e75c7e616060f418343b080774fe looks correct to me.

**Comment by jbphet** [comment]
Thanks for the review.  Closing, and I'll do the related work in https://github.com/phetsims/rosetta/issues/323 shortly (hopefully).
