### ISSUE TITLE
Remove ab/acid-base-solutions translation

### ISSUE THREAD

**Issue by liammulh** [phetsims/rosetta#326]
In testing Rosetta 2, I accidentally created an ab/acid-base-solutions translation and it's live on the website.

- [x] remove string file from babel (I will do this.)
- [x] remove sim from website (@mattpen, can you please do this?)

**Comment by mattpen** [comment]
I've deleted it from the database.

@jonathonolson - does anything additional need to happen here for yotta?

**Comment by jonathanolson** [comment]
I believe I handled this! Closing.
