### ISSUE TITLE
Give feedback on Rosetta 2

### ISSUE THREAD

**Issue by liammulh** [phetsims/rosetta#328]
Hey, @oliver-phet, the newest version of Rosetta 2 is live on Ox-Dev. Can you please take a look at it and provide more feedback in this issue? I've included responses to your last round of feedback below. Thanks!

Also, please look over the wireframes and the design doc to see if there's anything I'm overlooking.

- [design folder with wireframes](https://docs.google.com/document/d/1QaiX3nMyWqtNetOl1Iij9lvOhWDfVqJsjR9l-0fxqeQ/edit#heading=h.wof4n3kkzvn1)
- [up-to-date design document](https://docs.google.com/document/d/1QaiX3nMyWqtNetOl1Iij9lvOhWDfVqJsjR9l-0fxqeQ/edit#heading=h.wof4n3kkzvn1)

-------------------------------------------

- Top Navigation
  - [x] Remove ‘Translate’ - this is Rosetta 1.0, correct? Should be removed
  - [x] Rename ‘Translation Report’ to ‘Translate’
  - [x] In my design, I had a link to ‘User Guide’ (no ‘Help’ in navigation). Is there a reason we aren’t doing this on the ‘Translate Utility’ page?
    - I changed the design so that it's called 'User Guide', and it's just a link to an external doc.
- Translation Utility
  - [ ] Could we remove the ‘Get Translation Report’ button - just update the page when a locale is selected?
    - Unfortunately, no, this would require a significant amount of work.
  - [x] Rename the header ‘Translation Report’ is really unintuitive. I’d just use “PhET Translation Utility (HTML5)” like my design used.
  - [x] Don’t say “The translation report is finished!”
  - [x] When loading, maybe just have the spinner? Maybe “Translation data loading [spinner]“?
  - [x] How do users navigate back to locale selection screen? (My design had drop down persist)
    - I added link in the navbar.
  - [x] Handle case when no sims untranslated.
  - [x] Message saying all sims translated, check percentages.
  - [x] No sort buttons if one sim.
- Translation “Form”
  - [x] Shorten buttons to Save Publish Test? Put them on one line like the design?
  - [ ] Add warning/unsaved changes dialog - If I click in the nav I can lose my work!
    - We can't add this yet. See https://github.com/phetsims/rosetta/issues/325.

**Comment by oliver-phet** [comment]
Adding link to 2.0: https://ox-dev.colorado.edu/translate

**Comment by oliver-phet** [comment]
From @liammulh 

> You can test, but the form needs to be dirty (i.e. you put in a new value) before the button will be enabled. Also, you have to enable pop-ups for Ox-Dev.
> You can save, it should work.
> You can hit publish, but nothing will happen because I've turned off string commits and build requests.
> (Form needs to be dirty for any of the buttons to be enabled.)

- [ ] Open 'User Guide' in new tab `target="_blank"`
- [ ] Change page title to "PhET Translation Utility (HTML5)" (currently it's "PhET Translation Tool")
- [ ] 'Save' presents this dialog to the user `If you have a translation saved for acid-base-solutions in locale vi, it will be overwritten.` I'm having trouble understanding what this means and how a translator might "have a translations saved". Perhaps I'm not thinking of something, but why do we have this? Wouldn't that translator always be working from the saved translation?
- [ ] 'Save' currently doesn't actually save anything
- [ ] Can we hide Chains, Bumper, and Example Simulation?
- [ ] Is it possible to add "Signed in as: _useremail_" to the left of "Sign Out"
- [ ] match website link style (normal:#6c6c6c, visited:#840633, focus:#e01e5a), there aren't really any links within body text so an underline isn't needed on any text links.
- [ ] match website button style (#521764 Rectangular buttons with stroke, and inverted on hover.) Disabled could probably use the same color you already have #6c757d. Might be able to just reuse the css the website uses.
![image](https://user-images.githubusercontent.com/5090275/207984874-f3700001-ea58-4ae8-9b7d-d317295a6770.png)

**Comment by liammulh** [comment]
> 'Save' presents this dialog to the user `If you have a translation saved for acid-base-solutions in locale vi, it will be overwritten.` I'm having trouble understanding what this means and how a translator might "have a translations saved". Perhaps I'm not thinking of something, but why do we have this? Wouldn't that translator always be working from the saved translation?

The translator can only have one saved translation per ID/sim/locale combo. Thus, if they save a translation, change the translation, and click the save button again, it will overwrite what they currently have saved.

**Comment by liammulh** [comment]
> Can we hide Chains, Bumper, and Example Simulation?

These will be hidden in production. Right now it's set to show them because of the configuration.

**Comment by liammulh** [comment]
I thought we discussed not necessarily being able to match the website's styling? It seems like it wasn't an explicit requirement, and the scope on this rewrite/upgrade is already huge, I don't want to add more requirements.

**Comment by oliver-phet** [comment]
> > 'Save' presents this dialog to the user `If you have a translation saved for acid-base-solutions in locale vi, it will be overwritten.` I'm having trouble understanding what this means and how a translator might "have a translations saved". Perhaps I'm not thinking of something, but why do we have this? Wouldn't that translator always be working from the saved translation?
> 
> The translator can only have one saved translation per ID/sim/locale combo. Thus, if they save a translation, change the translation, and click the save button again, it will overwrite what they currently have saved.
> 
> Does that answer your question, @oliver-phet?

That's what I would expect, but isn't that behavior implied by "Save"? I'd pull out my hair if every time I saved a file I was asked if I was sure I wanted to save!

> > Is it possible to add "Signed in as: useremail" to the left of "Sign Out"
> 
> Yes, it's possible. I can add it if you feel it's necessary. I thought it was obvious that the email that's displayed next to the person icon is who you're signed in as.

I don't see an email next to the person icon and I think it's nice to show the email that will receive credit when a translation is submitted. If it's not trivial to add don't worry about it. 

> > match website link style (normal:#6c6c6c, visited:#840633, focus:#e01e5a), there aren't really any links within body text so an underline isn't needed on any text links.
> 
> > match website button style (#521764 Rectangular buttons with stroke, and inverted on hover.) Disabled could probably use the same color you already have #6c757d. Might be able to just reuse the css the website uses.
> > ![image](https://user-images.githubusercontent.com/5090275/207984874-f3700001-ea58-4ae8-9b7d-d317295a6770.png)
> 
> I thought we discussed not necessarily being able to match the website's styling? It seems like it wasn't an explicit requirement, and the scope on this rewrite/upgrade is already huge, I don't want to add more requirements.

That's totally fine. It can be saved for 2.1. It's certainly best for websites to look consistent and I thought it would be pretty easy to add some styling to links/buttons.

**Comment by liammulh** [comment]
> That's what I would expect, but isn't that behavior implied by "Save"? I'd pull out my hair if every time I saved a file I was asked if I was sure I wanted to save!

The confirm dialogue is no longer there.

> I don't see an email next to the person icon and I think it's nice to show the email that will receive credit when a translation is submitted. If it's not trivial to add don't worry about it.

I added "Signed in as: " before the email.

> That's totally fine. It can be saved for 2.1. It's certainly best for websites to look consistent and I thought it would be pretty easy to add some styling to links/buttons.

We actually don't have *any* styling in Rosetta as it is. We're just using vanilla [Bootstrap](https://getbootstrap.com/), and the idea is that we'll just take it out and replace the styling with PhET website styling, but that's actually a big can of worms that I'd rather not open right now.

**Comment by liammulh** [comment]
Okay, @oliver-phet, as of that last comment, I think I've addressed all of the feedback. Take another look at Ox-Dev when you get a chance.

**Comment by oliver-phet** [comment]
Looking good - I think just fix the typo in "Singed in as:"

**Comment by oliver-phet** [comment]
Also, styling in a future version sounds good.

**Comment by liammulh** [comment]
> fix the typo in "Singed in as:"

Done in the latest change and deployed to Ox-Dev.

> styling in a future version sounds good

I agree!

**Comment by liammulh** [comment]
Closing.
