### ISSUE TITLE
pH scale and pH scale basics are at the end of the list when sorted alphabetically

### ISSUE THREAD

**Issue by stemilymill** [phetsims/rosetta#331]
for https://github.com/phetsims/qa/issues/869

When sorting the translation utility alphabetically, pH Scale and pH Scale: Basics are sorted to the end of the alphabet.

![pH scale at the end of the alphabet](https://user-images.githubusercontent.com/85511101/208750321-5c3d82a5-6fb6-46e8-8bd5-c43d5ef84b65.jpg)

**Comment by liammulh** [comment]
https://github.com/phetsims/rosetta/commit/e7cee15bccc86b082a896308f2ba0f3f8c919672 makes it so that when you click the sort button, the pH sims are where they should be. However, they are still initially at the bottom of the list, and I'm not sure why.

**Comment by liammulh** [comment]
As of https://github.com/phetsims/rosetta/commit/bef63002c2dc64d58d468fb459503e0e9b794f88, this should be fixed.

**Comment by Nancy-Salpepi** [comment]
This looks good in round 2. Closing.
