### ISSUE TITLE
Translation Utility sorting inconsistencies  

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/rosetta#332]
**Test device**
MacBook Air (m1 chip) and Dell

**Operating System**
MacOS 13 and Win10

**Browser**
Safari and Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/869, if the sims are listed in ascending order and then I sort the sim-specific or common strings columns, sims with the same %age will be in alphabetic order. Pressing sort again so that the %ages go from least-->most, will result in sims with the same %age being in reverse alphabetic order. 

**Steps to reproduce**
1. Choose Portugese
2. Scroll down to Sims translated into Portugese --sims are in alphabetical order
3. Press the Sort button next to Common Strings --sims of the same % will still be in alphabetical order
4. Press the Sort button again next to Common Strings --sims of the same % will be in reverse alphabetical order

**Visuals**

https://user-images.githubusercontent.com/87318828/208752722-e3b64329-28f6-485b-a502-f4941e662c82.mp4

**Comment by liammulh** [comment]
@oliver-phet, what are your thoughts on this? I think it's more of a design question. How should the sorting work ideally? Then once I have the "ideal" behavior, we can talk about engineering.

**Comment by oliver-phet** [comment]
I get the same behavior in my testing. It would be nice if it kept Sim Title (ascending A-Z) - so the behavior is to preserve the existing sorting of the table but prioritize the new sort.

Essentially, I'm thinking:
**Default logic:** Sort by Sim Title (asc), then by Sim Strings % (asc), then by Common Strings % (asc)
**Upon clicking a sort:** that column is moved to the first priority of the logic (with opposite order).

If that is tricky/time consuming. Let's just sort by one column at a time, leave the others (asc).

Another peculiarity (that I think may be more disrupting to translators) is the inconsistent position of 'pH Scale'. If I sort by Sim Title, it is at the top or bottom (seems to be sorting uppercase/lowercase) _but_ if I then sort by Sim/Common Strings, it is sorted correctly?

**Comment by oliver-phet** [comment]
Oh - I also wanted to add Sim Strings % and Common Strings % are only sorting the %. When I plug this data into other data sorting tools (excel, google sheets) the entire string is sorted:
<img width="391" alt="image" src="https://user-images.githubusercontent.com/5090275/208764207-9c87e122-d711-41bc-a4df-aa6ce94d7d64.png">

This also seems nice (allows translators to see among sims that have the same % which contain the most strings) and addresses some of @DianaTavares 's feedback in https://github.com/phetsims/qa/issues/869#issuecomment-1360146192.

**Comment by liammulh** [comment]
@jbphet and I discussed this yesterday, and we think there might be some issues with sorting the string in lexicographic order. For instance, what happens if we want to change the string? Then our sorting might not be correct, depending on how we change the string.

Thus, we are going to try to implement a "fallback" sort criterion for sim-specific percent and common percent. The fallback for sim-specific percent will be the total number of sim-specific strings, and the fallback for common percent will be the total number of common strings. This way if the percentages are equal, the sorting will depend on the total number of strings.

**Comment by oliver-phet** [comment]
> @jbphet and I discussed this yesterday, and we think there might be some issues with sorting the string in lexicographic order. For instance, what happens if we want to change the string? Then our sorting might not be correct, depending on how we change the string.
> 
> Thus, we are going to try to implement a "fallback" sort criterion for sim-specific percent and common percent. The fallback for sim-specific percent will be the total number of sim-specific strings, and the fallback for common percent will be the total number of common strings. This way if the percentages are equal, the sorting will depend on the total number of strings.

That sounds fine (and probably more robust).

**Comment by jbphet** [comment]
I'm unassigning myself, since @liammulh is planning to implement this (or has already done so).

**Comment by liammulh** [comment]
So, for people reading this in the future, the way it should work now is that items with the same percent should have a secondary sort criterion, which is the total number of strings. So if you had something like:

50% (10 of 20)
50% (20 of 40)

The secondary sort criterion should be the 20 and the 40.

Should be resolved as of https://github.com/phetsims/rosetta/commit/006ffcaabca6088af82d63fce862afe212bae97e. Marking as ready for review.

**Comment by Nancy-Salpepi** [comment]
Sorting correctly in round 2: 
When pressing the Sort button next to Translated Strings, the sims will sort:
-first by percentage (largest to smallest)
-then within the same percentage, by the total number of strings (largest to smallest)

When pressing that Sort button a second time, the sims will sort:
-first by percentage (smallest to largest)
-then within the same percentage, by the total number of strings (smallest to largest)

Closing.
