### ISSUE TITLE
Add copy to clipboard button

### ISSUE THREAD

**Issue by liammulh** [phetsims/rosetta#335]
In https://github.com/phetsims/qa/issues/869, @DianaTavares noted it would be helpful to have a copy to clipboard button for the English value so that it can be easily pasted into Google translate. I think this could be done with [Clipboard API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API). If we do this, I think we need to change the copy English string to input button icon. See https://github.com/phetsims/rosetta/issues/334.

**Comment by jbphet** [comment]
Discussed in 6/14/2023 meeting, and decided that the "copy English string into form" is sufficient for now, closing.
