### ISSUE TITLE
Show percent translated on the translation form page

### ISSUE THREAD

**Issue by liammulh** [phetsims/rosetta#337]
In https://github.com/phetsims/qa/issues/869, @DianaTavares asked:

> It is possible to have the information in the picture always visible while we are translating the strings? I always give a fast scroll up-down to be sure that I translate all strings, but having this information, I think, is more efficient.
>
> ![image](https://user-images.githubusercontent.com/60749003/208790300-0db14bf2-aa09-4655-930f-a1fa60bc2d1b.png)

I think this is a feature @kathy-phet also thought would be nice.

I'm not sure how we'd show the percentage dynamically. Maybe every time the translation form data changes, we compute the string percentages:

```jsx
// This is just pseudocode.

const [translatedStringsData, setTranslatedStringsData] = useState({});
useEffect(() => {
  const newData = computeTranslatedStringsData(translationValues);
  setTranslatedStringsData(newData);
}, [translationFormData]);
```

And then in the JSX:

```jsx
// This is just pseudocode.

const formJsx = (
  <div>
    <h2>Sim-Specific Strings</h2>
    <p>{translatedStringsData.translated} of {translatedStringsData.total}</p>
  </div>
);
```

(We'd need to compute the percentage again, I think. And we'd need to do the pseudocode for each type of strings. And we might want to make the percentage show at the top of the screen in a sticky container so it's always visible.)

**Comment by oliver-phet** [comment]
This will be accomplished in #417
