### ISSUE TITLE
Test sim looks like it's always loading

### ISSUE THREAD

**Issue by liammulh** [phetsims/rosetta#338]
In https://github.com/phetsims/qa/issues/869#issuecomment-1360146192, @DianaTavares noted that the test button can open a tab that has a loading spinner that makes it look like the tab is always loading.

>Is normal that when I test a sim, the tab loos like is always loading?
>
>![image](https://user-images.githubusercontent.com/26031501/208757948-4ff4aa50-ea8c-4557-9d86-c88dea0ac344.png)

@DianaTavares, could you please provide steps to reproduce the problem and tell what operating system and web browser you were using?

**Comment by liammulh** [comment]
It looks like this was on Chrome. I can't reproduce the issue on macOS 12.4 + Chrome 108.0.5359.124 with Abkhazian (ab) Wave on a String or Spanish (es) Wave on a String.

**Comment by DianaTavares** [comment]
I get it again all the time with Spanish Colombia (I try a couple of sims) and  Abkhazian (ab) Wave on a String 
![image](https://user-images.githubusercontent.com/26031501/208975757-2c085f72-e813-43a5-baaf-3b7ba143c103.png)

and also I get this error sometimes: 
![image](https://user-images.githubusercontent.com/26031501/208975794-835f8558-62d5-46d5-9695-ae734e7dcc7a.png)

I have macOS Monterey and Chrome Version 108.0.5359.124

**Comment by liammulh** [comment]
@DianaTavares, did you enable pop-ups for Ox-Dev? Otherwise, the test button won't work.

**Comment by liammulh** [comment]
@DianaTavares and I corresponded on Slack. She showed me that she has pop-ups enabled for Ox-Dev. However, she's still seeing the loading spinner. I'm going to take a look at the code and see if I can figure out why this might be happening.

**Comment by liammulh** [comment]
Yeah, I just can't figure this out without being able to reproduce the error.

**Comment by liammulh** [comment]
@KatieWoe, could you please have the QA team try to duplicate this?

**Comment by KatieWoe** [comment]
I don't see this on Win 11 Chrome or Firefox. On chrome I see the generic "globe" image rather than the phet logo, but it doesn't look like it's loading.
![globular](https://user-images.githubusercontent.com/41024075/209391243-8ccafc2e-4961-49a1-9d8d-c395373bd94b.png)

**Comment by Nancy-Salpepi** [comment]
I can't replicate with macOS 13.0.1 and safari/chrome

<img width="1130" alt="Screenshot 2022-12-23 at 2 00 33 PM" src="https://user-images.githubusercontent.com/87318828/209394963-9cccbe63-f46d-483d-94c4-f70c7cc44088.png">

<img width="491" alt="Screenshot 2022-12-23 at 1 58 34 PM" src="https://user-images.githubusercontent.com/87318828/209395016-a56f2ce5-1001-4cf6-9e8f-7bfa6d602057.png">

**Comment by liammulh** [comment]
Since we can't reproduce, I'm going to close this issue. We can re-open it if there are other people who have the issue.
