### ISSUE TITLE
Support metadata for strings

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/rosetta#34]
Discussed during 7/14/15 dev meeting.

We need to discuss adding metadata to strings, for example:

``` json
}
  "multilineString": {
    "value": "Give me a\nbreak.",
    "multiline": true
  },
  "htmlString": {
    "value": "Turning left on <i>red</i> is a <b>bold</b> move.",
    "html": true
  }
}
```

We need to discuss exactly which flags should be supported, and then how to integrate this information into the Rosetta UI.

The plan is to not worry about this for iteration 1 of Rosetta.

**Comment by jbphet** [comment]
I'm going to close this issue.  There is some metadata in the string entries in babel at this point, and we haven't had a need yet to add more, and this issue is over two years old.  We can create a new one if and when we decide other metadata is needed.
