### ISSUE TITLE
Handle untranslated sim-specific sort button

### ISSUE THREAD

**Issue by liammulh** [phetsims/rosetta#340]
In https://github.com/phetsims/qa/issues/869, both @DianaTavares and @solaolateju noted that having a sort button for sim-specific untranslated sims doesn't make much sense and might be confusing.

@oliver-phet, some of solutions I proposed were disabling the button, removing the button, or making the button not do anything. What do you think we should do? I personally think removing the button would be the best option, but it would be visually inconsistent.

**Comment by oliver-phet** [comment]
I'd rather both tables use the same logic - something like what I proposed here: https://github.com/phetsims/rosetta/issues/332#issuecomment-1360225805

**Comment by liammulh** [comment]
I believe this issue will be resolved by the solution we plan on implementing for https://github.com/phetsims/rosetta/issues/332 described in https://github.com/phetsims/rosetta/issues/332#issuecomment-1363226469.

**Comment by liammulh** [comment]
So, for people reading this in the future, the way it should work now is that items with the same percent should have a secondary sort criterion, which is the total number of strings. So if you had something like:

50% (10 of 20)
50% (20 of 40)

The secondary sort criterion should be the 20 and the 40.

Should be resolved as of https://github.com/phetsims/rosetta/commit/006ffcaabca6088af82d63fce862afe212bae97e. Marking as ready for review.

**Comment by Nancy-Salpepi** [comment]
In Round 2 there is no longer a Sim-Specific Strings Column. There is only a Translated Strings Column. The sort button seems to be working correctly though. See https://github.com/phetsims/rosetta/issues/332#issuecomment-1398361893 for a description.
