### ISSUE TITLE
Shared strings don't show up in certain scenarios

### ISSUE THREAD

**Issue by liammulh** [phetsims/rosetta#342]
In https://github.com/phetsims/qa/issues/869, we discovered that a sim with shared strings won't have a shared strings table. I looked at the code, and I think we need to check if there's a translated file, and if there isn't we should set the shared string to be an empty string.

**Comment by liammulh** [comment]
https://github.com/phetsims/rosetta/commit/85f046cb279884f1693907d03239b59b8c92806c seems to show shared strings for Concentration, but not for Geometric Optics.

**Comment by liammulh** [comment]
The shared strings object in the translation form data was empty on the Geometric Optics translation form page. I need to check and see if `categorizedStringKeys.shared` is empty for Geometric Optics.

**Comment by liammulh** [comment]
Okay, I've verified that `categorizedStringKeys.shared` and `categorizedStringKeys.sharedSims` are both empty for Geometric Optics in Abkhazian (ab) using the master phetsims/babel branch.

Why? Is the logic for adding them incorrect? I will compare the logic of the old translation utility and the new one. It might be that the old one is determining whether it has shared strings based on sim key in the sim metadata. If so, we could just key into the sim metadata for the given sim, I think.

**Comment by liammulh** [comment]
I think this might actually be fixed. Geometric Optics: Basics is the sim that has the shared strings.

I need to go through a handful of sims and ensure this is working properly. For the next round of testing, QA should go through the sims on the old translation util, and for each sim with shared strings, they should verify that the new translation util also shows shared strings.

**Comment by liammulh** [comment]
I believe this is fixed. We will need to test this before publication.

**Comment by KatieWoe** [comment]
Bumper and Under Pressure both have shared strings on the main website but not on ox-dev

**Comment by liammulh** [comment]
> Bumper and Under Pressure both have shared strings on the main website but not on ox-dev

Bumper's strings:

```
{
  "en": {
    "SCENERY_PHET/ResetAllButton.name": "‪Reset All‬",
    "CHAINS/htmlString": "‪Turning left on <i>red</i> is a <b>bold</b> move.‬",
    "CHAINS/multilineString": "‪Give me a\nbreak.‬",
    "CHAINS/namedPlaceholdersString": "‪{{name}} is traveling at {{speed}} km/hr‬",
    "CHAINS/patternString": "‪{0}: {1} {2}‬",
    "CHAINS/plainString": "‪It's not easy being green.‬",
    "CHAINS/size": "‪Size‬",
    "SCENERY_PHET/units_nm": "‪nm‬",
    "JOIST/termsPrivacyAndLicensing": "‪Terms, Privacy & Licensing‬",
    "JOIST/translation.credits.link": "‪Translation Credits‬",
    "JOIST/thirdParty.credits.link": "‪Third-party Credits‬",
    "SCENERY_PHET/key.pageDown": "‪Pg Down‬",
    "SCENERY_PHET/key.pageUp": "‪Pg Up‬",
    "SCENERY_PHET/key.shift": "‪Shift‬",
    "SCENERY_PHET/keyboardHelpDialog.or": "‪or‬",
    "SCENERY_PHET/key.tab": "‪Tab‬",
    "JOIST/keyboardShortcuts.title": "‪Keyboard Shortcuts‬",
    "JOIST/keyboardShortcuts.toGetStarted": "‪to get started‬",
    "JOIST/credits.contributors": "‪Contributors: {0}‬",
    "JOIST/credits.graphicArts": "‪Graphic Arts: {0}‬",
    "JOIST/credits.leadDesign": "‪Lead Design: {0}‬",
    "JOIST/credits.qualityAssurance": "‪Quality Assurance: {0}‬",
    "JOIST/credits.softwareDevelopment": "‪Software Development: {0}‬",
    "JOIST/credits.soundDesign": "‪Sound Design: {0}‬",
    "JOIST/credits.team": "‪Team: {0}‬",
    "JOIST/credits.thanks": "‪Thanks‬",
    "JOIST/credits.title": "‪Credits‬",
    "JOIST/credits.translation": "‪Translation‬",
    "JOIST/updates.checking": "‪Checking for updates…‬",
    "JOIST/updates.getUpdate": "‪Get Update…‬",
    "JOIST/updates.newVersionAvailable": "‪There is a new version available: {0}.‬",
    "JOIST/updates.noThanks": "‪No Thanks‬",
    "JOIST/updates.offline": "‪Unable to check for updates.‬",
    "JOIST/updates.outOfDate": "‪New version available‬",
    "JOIST/updates.upToDate": "‪This simulation is up to date.‬",
    "JOIST/updates.yourCurrentVersion": "‪Your current version is: {0}.‬",
    "JOIST/versionPattern": "‪version {0}‬",
    "JOIST/options.title": "‪Options‬",
    "JOIST/menuItem.about": "‪About…‬",
    "JOIST/menuItem.enhancedSound": "‪Enhanced Sound‬",
    "JOIST/menuItem.fullscreen": "‪Full Screen‬",
    "JOIST/menuItem.getUpdate": "‪Check for Updates…‬",
    "JOIST/menuItem.mailInputEventsLog": "‪Mail Input Events Log‬",
    "JOIST/menuItem.options": "‪Options…‬",
    "JOIST/menuItem.outputInputEventsLog": "‪Output Input Events Log‬",
    "JOIST/menuItem.phetWebsite": "‪PhET Website…‬",
    "JOIST/menuItem.reportAProblem": "‪Report a Problem…‬",
    "JOIST/menuItem.screenshot": "‪Screenshot‬",
    "JOIST/menuItem.submitInputEventsLog": "‪Submit Input Events Log‬",
    "JOIST/simTitleWithScreenNamePattern": "‪{{simName}} — {{screenName}}‬",
    "BUMPER/bumper.title": "‪Bumper‬"
  }
}
```

Under Pressure's strings:

```
{
  "en": {
    "JOIST/HomeButton.name": "‪Home‬",
    "JOIST/adaptedFrom": "‪adapted\nfrom‬",
    "JOIST/termsPrivacyAndLicensing": "‪Terms, Privacy & Licensing‬",
    "JOIST/translation.credits.link": "‪Translation Credits‬",
    "JOIST/thirdParty.credits.link": "‪Third-party Credits‬",
    "JOIST/credits.title": "‪Credits‬",
    "JOIST/credits.leadDesign": "‪Lead Design: {0}‬",
    "JOIST/credits.softwareDevelopment": "‪Software Development: {0}‬",
    "JOIST/credits.team": "‪Team: {0}‬",
    "JOIST/credits.qualityAssurance": "‪Quality Assurance: {0}‬",
    "JOIST/credits.graphicArts": "‪Graphic Arts: {0}‬",
    "JOIST/credits.translation": "‪Translation‬",
    "JOIST/credits.thanks": "‪Thanks‬",
    "JOIST/updates.upToDate": "‪This simulation is up to date.‬",
    "JOIST/updates.outOfDate": "‪New version available‬",
    "JOIST/updates.checking": "‪Checking for updates…‬",
    "JOIST/updates.offline": "‪Unable to check for updates.‬",
    "JOIST/updates.newVersionAvailable": "‪There is a new version available: {0}.‬",
    "JOIST/updates.yourCurrentVersion": "‪Your current version is: {0}.‬",
    "JOIST/updates.getUpdate": "‪Get Update…‬",
    "JOIST/updates.noThanks": "‪No Thanks‬",
    "JOIST/versionPattern": "‪version {0}‬",
    "JOIST/options.title": "‪Options‬",
    "JOIST/showPointers": "‪Show Pointers‬",
    "JOIST/done": "‪Done‬",
    "JOIST/title.settings": "‪Settings‬",
    "JOIST/menuItem.options": "‪Options…‬",
    "JOIST/menuItem.about": "‪About…‬",
    "JOIST/menuItem.mailInputEventsLog": "‪Mail Input Events Log‬",
    "JOIST/menuItem.outputInputEventsLog": "‪Output Input Events Log‬",
    "JOIST/menuItem.phetWebsite": "‪PhET Website…‬",
    "JOIST/menuItem.reportAProblem": "‪Report a Problem…‬",
    "JOIST/menuItem.screenshot": "‪Screenshot‬",
    "JOIST/menuItem.fullscreen": "‪Full Screen‬",
    "JOIST/menuItem.settings": "‪Settings…‬",
    "JOIST/menuItem.getUpdate": "‪Check for Updates…‬",
    "JOIST/menuItem.submitInputEventsLog": "‪Submit Input Events Log‬",
    "JOIST/PhetButton.name": "‪PhET Menu Button‬",
    "JOIST/titlePattern": "‪{0} {1}‬",
    "FLUID_PRESSURE_AND_FLOW/atm": "‪atm‬",
    "FLUID_PRESSURE_AND_FLOW/psi": "‪psi‬",
    "FLUID_PRESSURE_AND_FLOW/kPa": "‪kPa‬",
    "FLUID_PRESSURE_AND_FLOW/valueWithUnitsPattern": "‪{0} {1}‬",
    "FLUID_PRESSURE_AND_FLOW/ftPerSPerS": "‪ft/s<sup>2</sup>‬",
    "FLUID_PRESSURE_AND_FLOW/mPerSPerS": "‪m/s<sup>2</sup>‬",
    "FLUID_PRESSURE_AND_FLOW/densityUnitsEnglish": "‪lb/ft<sup>3</sup>‬",
    "FLUID_PRESSURE_AND_FLOW/densityUnitsMetric": "‪kg/m<sup>3</sup>‬",
    "FLUID_PRESSURE_AND_FLOW/m": "‪m‬",
    "FLUID_PRESSURE_AND_FLOW/ft": "‪ft‬",
    "FLUID_PRESSURE_AND_FLOW/atmosphere": "‪Atmosphere‬",
    "FLUID_PRESSURE_AND_FLOW/on": "‪On‬",
    "FLUID_PRESSURE_AND_FLOW/off": "‪Off‬",
    "FLUID_PRESSURE_AND_FLOW/grid": "‪Grid‬",
    "FLUID_PRESSURE_AND_FLOW/ruler": "‪Ruler‬",
    "FLUID_PRESSURE_AND_FLOW/metric": "‪Metric‬",
    "FLUID_PRESSURE_AND_FLOW/english": "‪English‬",
    "FLUID_PRESSURE_AND_FLOW/units": "‪Units‬",
    "FLUID_PRESSURE_AND_FLOW/atmospheres": "‪Atmospheres‬",
    "SCENERY_PHET/ResetAllButton.name": "‪Reset All‬",
    "FLUID_PRESSURE_AND_FLOW/pressure": "‪Pressure‬",
    "FLUID_PRESSURE_AND_FLOW/readoutMeters": "‪{0} m‬",
    "FLUID_PRESSURE_AND_FLOW/readoutFeet": "‪{0} ft‬",
    "FLUID_PRESSURE_AND_FLOW/massLabelPattern": "‪{0} kg‬",
    "FLUID_PRESSURE_AND_FLOW/mysteryFluid": "‪Mystery Fluid‬",
    "FLUID_PRESSURE_AND_FLOW/mysteryPlanet": "‪Mystery Planet‬",
    "FLUID_PRESSURE_AND_FLOW/planetA": "‪Planet A‬",
    "FLUID_PRESSURE_AND_FLOW/planetB": "‪Planet B‬",
    "FLUID_PRESSURE_AND_FLOW/planetC": "‪Planet C‬",
    "FLUID_PRESSURE_AND_FLOW/fluidA": "‪Fluid A‬",
    "FLUID_PRESSURE_AND_FLOW/fluidB": "‪Fluid B‬",
    "FLUID_PRESSURE_AND_FLOW/fluidC": "‪Fluid C‬",
    "FLUID_PRESSURE_AND_FLOW/fluidDensity": "‪Fluid Density‬",
    "FLUID_PRESSURE_AND_FLOW/gravity": "‪Gravity‬",
    "FLUID_PRESSURE_AND_FLOW/earth": "‪Earth‬",
    "FLUID_PRESSURE_AND_FLOW/mars": "‪Mars‬",
    "FLUID_PRESSURE_AND_FLOW/jupiter": "‪Jupiter‬",
    "FLUID_PRESSURE_AND_FLOW/gasoline": "‪gasoline‬",
    "FLUID_PRESSURE_AND_FLOW/water": "‪water‬",
    "FLUID_PRESSURE_AND_FLOW/honey": "‪honey‬",
    "FLUID_PRESSURE_AND_FLOW/underPressureScreenTitle": "‪Under Pressure‬",
    "UNDER_PRESSURE/under-pressure.title": "‪Under Pressure‬"
  }
}
```

**Comment by liammulh** [comment]
I need to look at `getCategorizedStrings.js`.

**Comment by liammulh** [comment]
> Are all shared strings in the common table?

In Bumper?
- [ ] `"CHAINS/htmlString": "‪Turning left on <i>red</i> is a <b>bold</b> move.‬",`
- [ ] `"CHAINS/multilineString": "‪Give me a\nbreak.‬",`
- [ ] `"CHAINS/namedPlaceholdersString": "‪{{name}} is traveling at {{speed}} km/hr‬",`
- [ ] `"CHAINS/patternString": "‪{0}: {1} {2}‬",`
- [ ] `"CHAINS/plainString": "‪It's not easy being green.‬",`
- [ ] `"CHAINS/size": "‪Size‬",`

**Comment by liammulh** [comment]
> Are all shared strings in the common table (for Under Pressure)?

- [ ] `"FLUID_PRESSURE_AND_FLOW/atm": "‪atm‬",`
- [ ] `"FLUID_PRESSURE_AND_FLOW/psi": "‪psi‬",`
- [ ] `"FLUID_PRESSURE_AND_FLOW/kPa": "‪kPa‬",`
- [ ] `"FLUID_PRESSURE_AND_FLOW/valueWithUnitsPattern": "‪{0} {1}‬",`
- [ ] `"FLUID_PRESSURE_AND_FLOW/ftPerSPerS": "‪ft/s<sup>2</sup>‬",`
- [ ] `"FLUID_PRESSURE_AND_FLOW/mPerSPerS": "‪m/s<sup>2</sup>‬",`
- [ ] `"FLUID_PRESSURE_AND_FLOW/densityUnitsEnglish": "‪lb/ft<sup>3</sup>‬",`
- [ ] `"FLUID_PRESSURE_AND_FLOW/densityUnitsMetric": "‪kg/m<sup>3</sup>‬",`
- [ ] `"FLUID_PRESSURE_AND_FLOW/m": "‪m‬",`
- [ ] `"FLUID_PRESSURE_AND_FLOW/ft": "‪ft‬",`
- [ ] `"FLUID_PRESSURE_AND_FLOW/atmosphere": "‪Atmosphere‬",`
- [ ] `"FLUID_PRESSURE_AND_FLOW/on": "‪On‬",`
- [ ] `"FLUID_PRESSURE_AND_FLOW/off": "‪Off‬",`
- [ ] `"FLUID_PRESSURE_AND_FLOW/grid": "‪Grid‬",`
- [ ] `"FLUID_PRESSURE_AND_FLOW/ruler": "‪Ruler‬",`
- [ ] `"FLUID_PRESSURE_AND_FLOW/metric": "‪Metric‬",`
- [ ] `"FLUID_PRESSURE_AND_FLOW/english": "‪English‬",`
- [ ] `"FLUID_PRESSURE_AND_FLOW/units": "‪Units‬",`
- [ ] `"FLUID_PRESSURE_AND_FLOW/atmospheres": "‪Atmospheres‬",`
- [ ] `"SCENERY_PHET/ResetAllButton.name": "‪Reset All‬",`
- [ ] `"FLUID_PRESSURE_AND_FLOW/pressure": "‪Pressure‬",`
- [ ] `"FLUID_PRESSURE_AND_FLOW/readoutMeters": "‪{0} m‬",`
- [ ] `"FLUID_PRESSURE_AND_FLOW/readoutFeet": "‪{0} ft‬",`
- [ ] `"FLUID_PRESSURE_AND_FLOW/massLabelPattern": "‪{0} kg‬",`
- [ ] `"FLUID_PRESSURE_AND_FLOW/mysteryFluid": "‪Mystery Fluid‬",`
- [ ] `"FLUID_PRESSURE_AND_FLOW/mysteryPlanet": "‪Mystery Planet‬",`
- [ ] `"FLUID_PRESSURE_AND_FLOW/planetA": "‪Planet A‬",`
- [ ] `"FLUID_PRESSURE_AND_FLOW/planetB": "‪Planet B‬",`
- [ ] `"FLUID_PRESSURE_AND_FLOW/planetC": "‪Planet C‬",`
- [ ] `"FLUID_PRESSURE_AND_FLOW/fluidA": "‪Fluid A‬",`
- [ ] `"FLUID_PRESSURE_AND_FLOW/fluidB": "‪Fluid B‬",`
- [ ] `"FLUID_PRESSURE_AND_FLOW/fluidC": "‪Fluid C‬",`
- [ ] `"FLUID_PRESSURE_AND_FLOW/fluidDensity": "‪Fluid Density‬",`
- [ ] `"FLUID_PRESSURE_AND_FLOW/gravity": "‪Gravity‬",`
- [ ] `"FLUID_PRESSURE_AND_FLOW/earth": "‪Earth‬",`
- [ ] `"FLUID_PRESSURE_AND_FLOW/mars": "‪Mars‬",`
- [ ] `"FLUID_PRESSURE_AND_FLOW/jupiter": "‪Jupiter‬",`
- [ ] `"FLUID_PRESSURE_AND_FLOW/gasoline": "‪gasoline‬",`
- [ ] `"FLUID_PRESSURE_AND_FLOW/water": "‪water‬",`
- [ ] `"FLUID_PRESSURE_AND_FLOW/honey": "‪honey‬",`
- [ ] `"FLUID_PRESSURE_AND_FLOW/underPressureScreenTitle": "‪Under Pressure‬",`

**Comment by liammulh** [comment]
Based on the above investigation, I think it's reasonable to assume that somehow the strings that _should_ be shared strings are being categorized as common strings. How are these strings being categorized as common rather than shared?

**Comment by liammulh** [comment]
Here's the relevant code in `getCategorizedStringKeys.js`:

```js
if ( repoName === simName ) {
  logger.verbose( `categorizing sim-specific string key: ${stringKeyWithRepoName}` );
  categorizedStringKeys.simSpecific.push( stringKey );
}
else if ( simNames.includes( repoName ) ) {
  logger.verbose( `categorizing shared string key: ${stringKeyWithRepoName}` );
  categorizedStringKeys.shared.push( stringKey );
  if ( !categorizedStringKeys.sharedSims.includes( repoName ) ) {
    categorizedStringKeys.sharedSims.push( repoName );
  }
}
else {
  logger.verbose( `categorizing common string key: ${stringKeyWithRepoName}` );
  categorizedStringKeys.common.push( stringKey );
}
```

**Comment by liammulh** [comment]
Bumper isn't in the list of sims being passed to `getCategorizedStringKeys.js`:

<details>

<summary><code>simNames</code> (list of sims)</summary>

```
----------> acid-base-solutions
----------> area-builder
----------> area-model-algebra
----------> area-model-decimals
----------> area-model-introduction
----------> area-model-multiplication
----------> arithmetic
----------> atomic-interactions
----------> balancing-act
----------> balancing-chemical-equations
----------> balloons-and-static-electricity
----------> beers-law-lab
----------> bending-light
----------> blackbody-spectrum
----------> build-a-fraction
----------> build-a-molecule
----------> build-a-nucleus
----------> build-an-atom
----------> capacitor-lab-basics
----------> center-and-variability
----------> charges-and-fields
----------> circuit-construction-kit-ac
----------> circuit-construction-kit-ac-virtual-lab
----------> circuit-construction-kit-dc
----------> circuit-construction-kit-dc-virtual-lab
----------> collision-lab
----------> color-vision
----------> concentration
----------> coulombs-law
----------> curve-fitting
----------> density
----------> diffusion
----------> energy-forms-and-changes
----------> energy-skate-park
----------> energy-skate-park-basics
----------> equality-explorer
----------> equality-explorer-basics
----------> equality-explorer-two-variables
----------> expression-exchange
----------> faradays-law
----------> forces-and-motion-basics
----------> fourier-making-waves
----------> fraction-matcher
----------> fractions-equality
----------> fractions-intro
----------> fractions-mixed-numbers
----------> friction
----------> function-builder
----------> function-builder-basics
----------> gas-properties
----------> gases-intro
----------> gene-expression-essentials
----------> geometric-optics
----------> geometric-optics-basics
----------> graphing-lines
----------> graphing-quadratics
----------> graphing-slope-intercept
----------> gravity-and-orbits
----------> gravity-force-lab
----------> gravity-force-lab-basics
----------> greenhouse-effect
----------> hookes-law
----------> isotopes-and-atomic-mass
----------> john-travoltage
----------> least-squares-regression
----------> make-a-ten
----------> masses-and-springs
----------> masses-and-springs-basics
----------> mean-share-and-balance
----------> molarity
----------> molecule-polarity
----------> molecule-shapes
----------> molecule-shapes-basics
----------> molecules-and-light
----------> my-solar-system
----------> natural-selection
----------> neuron
----------> normal-modes
----------> number-line-distance
----------> number-line-integers
----------> number-line-operations
----------> number-play
----------> ohms-law
----------> pendulum-lab
----------> ph-scale
----------> ph-scale-basics
----------> plinko-probability
----------> projectile-motion
----------> proportion-playground
----------> ratio-and-proportion
----------> reactants-products-and-leftovers
----------> resistance-in-a-wire
----------> rutherford-scattering
----------> states-of-matter
----------> states-of-matter-basics
----------> trig-tour
----------> under-pressure
----------> unit-rates
----------> vector-addition
----------> vector-addition-equations
----------> wave-interference
----------> wave-on-a-string
----------> waves-intro
```

</details>

**Comment by liammulh** [comment]
> Neither Bumper nor Fluid Pressure and Flow are in the list of sims being passed to `getCategorizedStringKeys.js`.

This is because they are not supposed to be in the list of sims if you aren't a team member.

The way this is happening is:

- Someone who isn't a team member requests the translation form for Bumper or Under Pressure.
- In order to make the translation form data, we need to get categorized string keys.
- In order to get categorized string keys, we need a list of sims to check for shared strings.
- If the user isn't a team member, neither chains nor fluid-pressure-and-flow will be in the list of sim names because neither of those sims match the criteria for being public.
- If the repo name isn't in the list of sims, then the string key will be categorized as common, hence seeing the shared string keys in the common table.

**Comment by liammulh** [comment]
It wouldn't be very DRY, but we could sort of replicate the code for getting sim names and titles in `getCategorizedStringKeys.js`, but instead of checking for whether the person is a team member, just get the full list of sims, even the invisible ones. I don't know if this would cause other problems. I'll have to think about what the best solution to this would be.

**Comment by liammulh** [comment]
Maybe we do something like:

```js
  const simMetadata = await getSimMetadata();
  const simNames = Object.keys( getSimNamesAndTitles( simMetadata, 'true' ) );
```

**Comment by liammulh** [comment]
It's okay for Under Pressure's shared strings to be in the common category.

@jbphet and I reviewed this. The strings for FPAF in Under Pressure will be categorized as common strings since that is the "fallback" category if they can't be categorized as shared strings. To be categorized as a shared string, the string's repo needs to be in the list of all sims, and FPAF is never in that list, thus it falls into the common category.

**Comment by KatieWoe** [comment]
Things look good in Under Pressure and two random sims. Bumper couldn't be tested since sign ins don't work right now, so leaving open.

**Comment by stemilymill** [comment]
looks good on bumper as well as various other sims 👍
