### ISSUE TITLE
'Translation not submitted' error shown

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/rosetta#343]
For https://github.com/phetsims/qa/issues/869 on macOS 13 + safari, after pressing the "Publish" button, and then "OK" -- I get an error message:
<img width="542" alt="Screenshot 2022-12-21 at 4 54 57 PM" src="https://user-images.githubusercontent.com/87318828/209011401-33feb8d0-cd61-4ed8-abfe-00e348f96bde.png">

But when I go to babel, the translation is there. Here it is for Mean, Share, and Balance:

<img width="907" alt="Screenshot 2022-12-21 at 4 58 33 PM" src="https://user-images.githubusercontent.com/87318828/209011578-42e7380c-ad26-46c5-b3cf-545dde80dc0b.png">

**Comment by liammulh** [comment]
This is actually behaving consistently with the config. The send build request flag is set to false. This means the strings will be committed, but the build request for the sim won't be sent to the build server.

However, I understand why this error message is confusing.

If we were to have booleans for `stringsWereCommitted`, `buildRequestSent`, `sendBuildRequests`, and `performStringCommits` on the client when we're about to display this message, we could have an accurate message.

We could say, "hey, we're not sending build requests, but your strings were committed to babel," for example.

**Comment by liammulh** [comment]
This is not high-priority for me right now. I will reassign when I get to this.

**Comment by liammulh** [comment]
This should be fixed in https://github.com/phetsims/rosetta/commit/156697d4547d376cc963233dc431416f8baa5cd1.

**Comment by Nancy-Salpepi** [comment]
This looks good in https://github.com/phetsims/qa/issues/931. closing.

**Comment by liammulh** [comment]
Deployed in https://github.com/phetsims/rosetta/commit/6021626a17d44d4a05a0be5cb4a3cbf1a41ccb17 (2.0.7).
