### ISSUE TITLE
Saved Translation not deleted

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/rosetta#344]
For https://github.com/phetsims/qa/issues/869 with macOS 13.0.1 + safari 16.1:

After publishing a sim, the saved translation isn't deleted. 
I followed the instructions in the general issue:
>ensure that once they've published a translation, and then wait about ten minutes, they see the strings from Babel, not strings
they saved
To test this, save a translation, modify the saved translation, publish it, and then wait ten minutes. When you come back, you
should see the strings that are in Babel in the form rather than your saved strings. (The saved translation should be deleted from the database when you publish.)

Specifically I did this:
1. Using Abkhazian, in Blackbody Spectrum I translated some of the sim-specific strings and then saved the translation. 
<img width="980" alt="Screenshot 2022-12-21 at 5 47 47 PM" src="https://user-images.githubusercontent.com/87318828/209018921-20a5331d-3fff-4032-8418-295ff81f0b56.png">

2. I then went back and for "lightbulb" I changed the '2' to a 'II' and published.
<img width="188" alt="Screenshot 2022-12-21 at 5 48 16 PM" src="https://user-images.githubusercontent.com/87318828/209019070-2be1af1a-0c75-40a2-ad2a-4089a3a9a280.png">

3. Waited a while and then went back into the translation utility --the '2' is still there.

**Comment by liammulh** [comment]
Ah, I think I simply neglected to add the code that deletes a saved translation when you hit publish. This should be easy enough to add (I hope).

**Comment by liammulh** [comment]
Should be resolved as of https://github.com/phetsims/rosetta/commit/2fcd1528651baebe69de11e42426e3d4b3082579. I'm going to mark this as ready for review.

**Comment by Nancy-Salpepi** [comment]
Unable to verify until https://github.com/phetsims/rosetta/issues/359 is addressed.
