### ISSUE TITLE
Should we add a "Total" column to the translation report?

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#348]
As of this writing, the columns for the translation report look like this:

![image](https://user-images.githubusercontent.com/3082831/209395640-324b254c-8472-4ec0-bad5-b337ea00c0da.png)

This makes it a little hard for users to answer questions like "What sims need the least work to finish up?" or "Which sims need the most work?".  Should we consider adding a "Total" column to make this easier?  My guess is that they would use that column for sorting more than the others.

**Comment by oliver-phet** [comment]
This sounds like more of a 2.1 feature. I'd recommend focusing on https://github.com/phetsims/rosetta/issues/332#issuecomment-1360225805
(sorting using the entire string - so that sims with the same % and sorted).

**Comment by jbphet** [comment]
There is another issue that is also about adding a column, and we should consider that one when evaluating this one, since we don't want to make the report look too cluttered.  See #347.

**Comment by oliver-phet** [comment]
Discussed with @liammulh today. We decided it would be best to move to a single column "Strings Translated" that is a composite of sim-specific, shared, and common strings. Updated design:
<img width="917" alt="image" src="https://user-images.githubusercontent.com/5090275/209406216-86af1e98-9cf1-48f2-b954-4f33880df1ec.png">

**Comment by liammulh** [comment]
I think as of https://github.com/phetsims/rosetta/commit/48bb47a01b1e21c1f5ebfb520f09a6bfe687c8b9, the total column is working as envisioned in this issue. I will mark this as ready to review.

**Comment by Nancy-Salpepi** [comment]
Things looks good in round 2--there is now only one column: Translated Strings. The associated sort button is working as it should. Next to each percentage there is now an info button which separates out the strings by type. 

Closing.
