### ISSUE TITLE
How should we handle long strings in the translation utility?

### ISSUE THREAD

**Issue by liammulh** [phetsims/rosetta#349]
@oliver-phet, @jbphet and I noticed a long non-a11y-description string in pH Scale:

<img width="800" alt="Screen Shot 2023-01-04 at 3 32 03 PM" src="https://user-images.githubusercontent.com/60749003/210662543-dbaad56b-fea4-474b-aff4-ef155e777ce2.png">

John and I were thinking that if we want to keep super long strings like this translatable, we should probably provide a [textarea](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea) rather than an [input](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input). Thoughts?

EDIT: For context, the above screenshot was taken from ph-scale/sw (Swahili).

**Comment by oliver-phet** [comment]
We looked at this together today. I think there is a larger discussion around validating the html tags that seem to be present in several of these.

For now, I'd opt for a textarea for handling these.

**Comment by liammulh** [comment]
In https://github.com/phetsims/rosetta/commit/beb2136d83c0e9882e78a006dd04ff09357efc85, I made all inputs textareas with a default height similar to that of an input. This seemed like a more elegant solution to me. I also aligned the copy value button and the text areas. I think it looks much nicer and feels much nicer from a UX perspective.
