### ISSUE TITLE
Some strings are improperly updating when the value has't changed

### ISSUE THREAD

**Issue by phet-steele** [phetsims/rosetta#35]
While testing the utility and translating the sim "Chains" into Czech (cs), the debug info, and commits in babel, would claim to continuously translate the strings with string keys "multilineString" and "adaptedFrom" each time I clicked on Submit. This is happening regardless of whether I've change the string contents or not.

An example commit: https://github.com/phetsims/babel/commit/0278b7d625e45e6ff8a9ea001815d361608f42e4

The string isn't changing but is updating anyway.

**Comment by phet-steele** [comment]
My hunch here is that any submitted values the have a line break will cause this.

**Comment by aaronsamuel137** [comment]
I suspect you're right, there is some special handling of newline strings that could lead to this. Assigning to myself.

**Comment by aaronsamuel137** [comment]
I've attempted a fix for this, let me know if it works for you @phet-steele.

**Comment by phet-steele** [comment]
The above issue is fixed, but I'll continue to keep an eye out for any exceptions with multiline strings
