### ISSUE TITLE
Curly brace validation not working for string keys with markup

### ISSUE THREAD

**Issue by liammulh** [phetsims/rosetta#350]
While testing a new tooltip for translators about how to correctly translate curly brace patterns, I noticed that our validation wasn't running correctly for a string key with markup and double curly braces in ab/diffusion:

<img width="800" alt="Screen Shot 2023-01-05 at 4 00 37 PM" src="https://user-images.githubusercontent.com/60749003/210896688-94df5c28-f750-4d1d-b86f-8222ec9bd213.png">

How it's supposed to look:

<img width="800" alt="Screen Shot 2023-01-05 at 4 01 46 PM" src="https://user-images.githubusercontent.com/60749003/210896707-f9d7d8c7-549f-430c-a364-c548508070ca.png">

Some questions:

- Is this happening in Rosetta 1.0?
  - No.

- Is this happening for all string keys with both markup and curly braces?

Wow, interestingly, no. This isn't an issue in ab/fourier-making-waves:
<img width="800" alt="Screen Shot 2023-01-05 at 4 14 22 PM" src="https://user-images.githubusercontent.com/60749003/210898127-a67060c8-fed3-46f2-8393-11d5333ec2d3.png">

- Is this happening for string keys with markup and single curly braces?
  - Seemingly, no.
  - See ab/acid-base-solutions pattern.0value.1power.
  - See ab/forces-and-motion-basics pattern.0name.1valueUnitsAcceleration.

**Comment by liammulh** [comment]
I think I know what the issue is. The `makeValidationSchema.js` module was written before we added support for shared strings. I bet `tAvg` and `tAvgK` are shared strings, and those strings aren't getting validation schemas. Going to try to validate my hypothesis.

**Comment by liammulh** [comment]
`tAvg` and `tAvgK` are indeed shared strings. Going to try to fix now...

**Comment by liammulh** [comment]
Should be fixed in https://github.com/phetsims/rosetta/commit/8f301844d42d62a3ee926037937a2617ba75ee9e. Marking as ready for review for next round of testing.

**Comment by Nancy-Salpepi** [comment]
looks good in round 2.
