### ISSUE TITLE
Shorten time that "(pending update)" is shown

### ISSUE THREAD

**Issue by liammulh** [phetsims/rosetta#351]
In Rosetta 2.0, we show a list of sims that have been published and a list that haven't been published. We create these lists based on the sim metadata we get from the website. Yesterday, @jbphet and I met with @mattpen, and he said that in the worst-case scenario, the website's sim metadata could be cached for 48 hours. Thus, our list of published or unpublished sims could potentially be out-of-sync with reality for up to 48 hours. Our solution to this is to show a "(pending update)" note next to a sim title after a user submits a translation for it. However, showing this note for 48 hours seems like a bad user experience.

@mattpen, is there some way we could shorten the amount of time we have to show this note? Is there a better source of truth than the sim metadata for getting a list of published vs. unpublished sims?

## Note for QA

Testing this should be part of phase 2. To test, publish a sim, then go back to the sim list. You should see a note that says "(pending update)", and that note should go away after 30 minutes.

**Comment by mattpen** [comment]
We have some cache avoidance in place.  It requires the use of a shared password and it exposes metadata for unpublished sims. It should only be used from developer machines and phet servers, and it is _not_ appropriate for use in web browsers.  You can use it by:

1. Including the query parameter: `include-unpublished`.
2. Include the query parameter: `nonce={{some long random and unique string}}`
3. Using basic authentication.  I can send the credentials to you directly.

I think though, that since this is a React app that we are going to need a way to do this from the client, correct?  I'll need to think about the best way to do this.  It is very easy to avoid the varnish cache by including the nonce query parameter (see #2 above), but it will be more difficult to avoid the tomcat cache (which can be up to 24 hours stale).

**Comment by liammulh** [comment]
> I think though, that since this is a React app that we are going to need a way to do this from the client, correct?

We get the metadata using server-side (Node/Express) [code](https://github.com/phetsims/rosetta/blob/twosetta/src/server/translationApi/api/translatedAndUntranslatedSims.js), and then the client-side (React) code [requests it](https://github.com/phetsims/rosetta/blob/twosetta/src/client/hooks/useTranslatedAndUntranslatedSims.jsx) via an API endpoint.

> Can you describe the metadata that is required by rosetta?

To create the lists of published and unpublished sims, we first need a locale. We then iterate through the simulations in the metadata stopping at each one to ask if its `localizedSimulations` object has the locale we're interested in. If it does, we add it to the list of published sims. If it doesn't we add it to the list of unpublished sims.

We use the sim metadata in other ways too, so that isn't a comprehensive description of the metadata required by Rosetta. It's just a description of how we use the metadata to create the lists of published and unpublished sims.

@mattpen, do you need a more comprehensive description of how Rosetta uses the sim metadata?

**Comment by mattpen** [comment]
> We get the metadata using server-side (Node/Express) [code](https://github.com/phetsims/rosetta/blob/twosetta/src/server/translationApi/api/translatedAndUntranslatedSims.js), and then the client-side (React) code [requests it](https://github.com/phetsims/rosetta/blob/twosetta/src/client/hooks/useTranslatedAndUntranslatedSims.jsx) via an API endpoint.

This seems a little convoluted, why doesn't the client request it directly? But that is one way to solve the problem, just tell the server how to request it using my previous comment.


<hr/>

>To create the lists of published and unpublished sims, we first need a locale. We then iterate through the simulations in the metadata stopping at each one to ask if its localizedSimulations object has the locale we're interested in. If it does, we add it to the list of published sims. If it doesn't we add it to the list of unpublished sims.
>
>We use the sim metadata in other ways too, so that isn't a comprehensive description of the metadata required by Rosetta. It's just a description of how we use the metadata to create the lists of published and unpublished sims.

So it seems like you just need a list of the sims that includes a name and a list of locales? If we're going to make a custom endpoint we'll need a comprehensive list.

**Comment by liammulh** [comment]
> This seems a little convoluted, why doesn't the client request it directly?

I try to do the "dirty work" of manipulating data in server-side code so the client-side code's only job is to take the data it receives from the server and render it.

> But that is one way to solve the problem, just tell the server how to request it using my previous comment.

I will discuss this with @jbphet, but this sounds like the simplest solution, and probably the one we will go with.

**Comment by liammulh** [comment]
To avoid the sim metadata cache, we can either have a unique path by including the `nonce` query param or use `http://localhost:8080` as the `SERVER_URL` in production.

**Comment by liammulh** [comment]
Since the `SERVER_URL` is used for more than just getting the sim metadata (I believe it is also used for getting sim HTML, sim dependencies, etc.), I will just include the `nonce` query param.

**Comment by liammulh** [comment]
@jbphet, https://github.com/phetsims/rosetta/commit/ecadfb72b1237ec65f54323f8a93b4ac949d100c shortens the amount of time a user has to see the "(pending update)" note. It accomplishes this by using the `&nonce={{long random string}}` query parameter. This query parameter busts the website's sim metadata cache. Thus, our sim metadata is always fresh. Now the "(pending update)" note will only be shown for as long as Rosetta is configured to cache the sim metadata. In other words, we now control how long the "(pending update)" button is shown.

In https://github.com/phetsims/rosetta/commit/ecadfb72b1237ec65f54323f8a93b4ac949d100c, I noticed that several requests were being made to get the sim metadata in quick succession. (See the logs below.)

<details>
<summary>Logs</summary>

```
info: get request received for /translationReportEvents/ab?wantsUntranslated=true&isTeamMember=false
info: getting sim metadata
info: sim metadata is stale or nonexistent; getting it
info: cache-busting sim metadata url: https://phet.colorado.edu/services/metadata/1.3/simulations?format=json&type=html&include-unpublished=true&summary&nonce=ebb4f0fbc955449782f6633f152477325eafdd7adbaaca7a1c46af1320a6ee71a2e1993d8d6746ff
info: get request received for /translatedAndUntranslatedSims/ab?isTeamMember=false
info: getting locale info
info: locale info is stale or nonexistent; getting it
info: get request received for /translationReportEvents/ab?wantsUntranslated=false&isTeamMember=false
info: getting sim metadata
info: sim metadata is stale or nonexistent; getting it
info: cache-busting sim metadata url: https://phet.colorado.edu/services/metadata/1.3/simulations?format=json&type=html&include-unpublished=true&summary&nonce=54e7c0360cd3899f38aba8b4c339416aa6b1e6017f1e23badb147c6b536d335445af191485b419a5
info: get request received for /translatedAndUntranslatedSims/ab?isTeamMember=false
info: getting locale info
info: locale info is stale or nonexistent; getting it
info: get request received for /localeInfo
info: getting locale info
info: locale info is stale or nonexistent; getting it
info: get request received for /simNamesAndTitles?isTeamMember=false
info: responding with sim names and titles
info: getting sim metadata
info: sim metadata is stale or nonexistent; getting it
info: cache-busting sim metadata url: https://phet.colorado.edu/services/metadata/1.3/simulations?format=json&type=html&include-unpublished=true&summary&nonce=b1a42c7cc731837c6ed5402dad781467e0025e34cf8a85bcd31574bb21c58011399d769c1eadaa11
info: got locale info; returning it
info: getting sim metadata
info: sim metadata is stale or nonexistent; getting it
info: cache-busting sim metadata url: https://phet.colorado.edu/services/metadata/1.3/simulations?format=json&type=html&include-unpublished=true&summary&nonce=6eab4eb00be7684a07be4b8263d5754594d52c22fa9d19b341f521e79ceef6647356baa4c3e0a0a5
info: got locale info; returning it
info: responding with locale info
info: got locale info; returning it
info: getting sim metadata
info: sim metadata is stale or nonexistent; getting it
info: cache-busting sim metadata url: https://phet.colorado.edu/services/metadata/1.3/simulations?format=json&type=html&include-unpublished=true&summary&nonce=d9e1f34c6c3b444b4c58ac88269376725babd802221d789bb3b92173e545599b64d95f25aa5cb164
info: returning sim metadata
```

</details>

I'm not sure why there were multiple requests for the sim metadata being made in quick succession. It might have to do with the translation report needing the list of published sims and the list of unpublished sims. Anyway, I decided to fix the possible race condition where multiple requests for sim metadata are made in quick succession. I did this by setting a boolean variable for whether a promise exists for sim metadata. If it does, we don't try to get it until the promise is fulfilled and the boolean is set back to false.

On Friday, I'd like to review and test the code in https://github.com/phetsims/rosetta/commit/ecadfb72b1237ec65f54323f8a93b4ac949d100c. We should to test and review two things:

1. Does the "(pending update)" note depend on `VALID_METADATA_DURATION`? (That is, did we resolve this issue?)
2. Can we be reasonably sure we've fixed the race condition where multiple sims make a request for sim metadata? Does the code for fixing the race condition need to be modified?

**Comment by liammulh** [comment]
Assigning @jbphet so he can review when time permits.

**Comment by liammulh** [comment]
Today, @jbphet and I played around with the code in https://github.com/phetsims/rosetta/commit/ecadfb72b1237ec65f54323f8a93b4ac949d100c and discovered that I actually didn't fix the issue where a burst of sim metadata requests could be made, each busting the website's sim metadata cache. We want to avoid sending a burst of sim metadata requests to the website because it could tax the server.

I found and implemented a pattern in https://github.com/phetsims/rosetta/commit/27b6a1af2946dab249999381fac3b9971d5b53de that I believe solves the problem where a burst of sim metadata requests can be made. I hope to review this code with @jbphet next time we meet.

**Comment by liammulh** [comment]
To reproduce a "burst" of sim metadata requests, you had to:

1. Cold-start Rosetta using `npm start`.
2. Directly load a translation report, e.g. `http://localhost:16372/translate/ab`. (Do _not_ hit the landing page `http://localhost:16372/translate` first.)

If you follow those steps with https://github.com/phetsims/rosetta/commit/ecadfb72b1237ec65f54323f8a93b4ac949d100c checked out, you should see 5 separate requests for website sim metadata being logged.

**Comment by jbphet** [comment]
@liammulh and I reviewed his solution for this during a collaboration session today, and I'm good with it.  Unassigning.

**Comment by stemilymill** [comment]
looks good on round 3 testing
