### ISSUE TITLE
Add loading spinner to indicate test sim is loading

### ISSUE THREAD

**Issue by liammulh** [phetsims/rosetta#355]
In https://github.com/phetsims/qa/issues/878, @DianaTavares noted:

> The test button takes some seconds to open the sim

**Comment by liammulh** [comment]
I think the slow opening might be unavoidable due to the client-server architecture we have. We could put a loading spinner to indicate the test sim is loading.

**Comment by liammulh** [comment]
Loading spinner added in https://github.com/phetsims/rosetta/commit/10d892882268bedbf89a36d1a5afe020199c64de.

**Comment by liammulh** [comment]
Marking as ready for review.

**Comment by Nancy-Salpepi** [comment]
Spinner added in round 2:
<img width="681" alt="Screenshot 2023-01-20 at 9 29 34 AM" src="https://user-images.githubusercontent.com/87318828/213723405-830316fe-d90e-4ba7-92a9-ccf83921384c.png">

Closing.
