### ISSUE TITLE
Decide how to handle column width issues

### ISSUE THREAD

**Issue by liammulh** [phetsims/rosetta#356]
In https://github.com/phetsims/qa/issues/878, both @DianaTavares and @solaolateju mentioned that the width of the columns being dynamic can lead to some strange situations like string key columns taking up too much space or inputs having relatively little space. Should the columns have a static width? Should we look into having a max width and wrapping strings? Should we try to align the columns of the sim-specific and common tables? Should we try to align the columns of the published versus unpublished sims lists?

This issue is related to https://github.com/phetsims/rosetta/issues/349.

@oliver-phet, since you're the de facto designer, do you have any ideas?

**Comment by oliver-phet** [comment]
Is there a good example of this I can look at?

**Comment by liammulh** [comment]
### (1) Should the columns have a static width? Should we look into having a max width and wrapping strings?

<img src="https://user-images.githubusercontent.com/26031501/211892900-736dfd1c-48dd-4e51-949e-42fcae0673e1.png">

### (2) Should we try to align the columns of the sim-specific, shared, and common tables?

<img src="https://user-images.githubusercontent.com/18397749/211924107-b5f514cd-a8f8-415b-8653-1d0eaeab1e59.png">

### (3) Should we try to align the columns of the published versus unpublished sims lists?

<img src="https://user-images.githubusercontent.com/18397749/211923970-15eb8e23-f918-49e5-a39e-b0c19fd43674.png">

---------------

@oliver-phet, in the above screenshots I tried to illustrate each of my questions. In (1), if we had static column widths, we'd wrap the English string so it takes up more vertical space. (And the input should be a text area as we discussed in https://github.com/phetsims/rosetta/issues/349. In (2), if the column widths were static, I think the columns would line up in the different tables. Same goes for (3).

@jbphet, we have to think carefully about this because it might cause translators to insert line breaks to match the wrapped English version of the string. If they insert line breaks, I think we might need to check for them and strip them out.

**Comment by oliver-phet** [comment]
Thanks, those are super helpful. Here's what I'd like to do:

1. Can we implement a max-width to the string column? I tried 450px on the td and that help immensely (both reduces the width of long strings and ensures the copy string button is on the same line as the text entry field.
<img width="1683" alt="image" src="https://user-images.githubusercontent.com/5090275/212398788-a12c47ae-a559-4953-97ab-5f92eea4f80e.png">
2. Yes, could we use text-align: right for the table cells in the Translation column?
3. Yes, could we use text-align: right for the table cells in the Translated Strings column?

**Comment by liammulh** [comment]
Columns have max width in https://github.com/phetsims/rosetta/commit/a9c5c353ea921ae1813046ac8a6651cc1afc4322, and I think this addresses the concerns voiced by Sola and Diana.
