### ISSUE TITLE
Handle TODOs

### ISSUE THREAD

**Issue by zepumph** [phetsims/rosetta#357]
There is one TODO in this repo with an issue, https://github.com/phetsims/rosetta/blob/bc6c1cce5f108d3009231a7f640796d348c9c768/js/renderLocaleStringReport.js#L38

From https://github.com/phetsims/chipper/issues/1372

**Comment by liammulh** [comment]
Now that the Rosetta 2.0 dev branch has been merged into master, there are no longer (as of https://github.com/phetsims/rosetta/commit/35bb0b70d5586bf246c24dc23faa78dce8122f8b) TODO comments:

```
> pwd
/Users/liam/,/programs/phet/rosetta
> rg "TODO"
> 
```
