### ISSUE TITLE
Can't save strings

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/rosetta#359]
**Test device**
MacBook Air (m1 chip)

**Operating System**
13.1

**Browser**
safari 16.2

**Problem description**
For https://github.com/phetsims/qa/issues/878, translations are not saving even though the "Translation Saved" message appears on the screen. 

**Steps to reproduce**
Here is an example:
1. Select Faroese
2. Select Diffusion
3. Change some strings and press Save
4. Press "Back to Faroese Sim List"
5. Select Diffusion again -- boxes are blank

**Comment by Nancy-Salpepi** [comment]
This seems to be an issue with Shared Strings and Common Strings. 
It looks like Sim-Specific Strings are saving.

**Comment by liammulh** [comment]
That is super helpful! Thanks!

**Comment by liammulh** [comment]
I suppose the first place to look is the client-side `saveTranslation.js` module. I should log the translation to ensure it contains shared and common strings.

**Comment by liammulh** [comment]
I am not able to reproduce locally with a config that is probably different from what's on Ox-Dev. I will change my config to match Ox-Dev's as much as possible and test again.

**Comment by liammulh** [comment]
> This seems to be an issue with Shared Strings and Common Strings.
It looks like Sim-Specific Strings are saving.

I just tried to reproduce on Ox-Dev, and I am seeing that sim-specific strings are also not saving.

**Comment by liammulh** [comment]
The next step is to log the translation form data we get back from the server to verify the saved translation isn't being retrieved from the database. If it isn't we need to figure out why.

**Comment by Nancy-Salpepi** [comment]
I went back today and tried again--sim specific strings aren't saving. I must have seen my changes in the form because I had pressed publish. Sorry!

**Comment by liammulh** [comment]
I checked, and the translation form data I'm getting back from the server-side code has:

```
    "simSpecific": {
        "diffusion_DOT_title": {
            "english": "Diffusion",
            "translated": "Monday"
        }
    },
```

But in the database:

```
      simSpecific: {
        diffusion_DOT_title: { english: 'Diffusion', translated: 'Diffusion' }
      },
```

Next place to look (and probably log/debug) would be `getTranslationFormData.js`.

**Comment by liammulh** [comment]
Okay, here's an idea: What if local check-login data is different from Ox-Dev check-login data? That might explain why I'm not seeing this issue locally, and the filer (see below) might be wrong on Ox-Dev.

```js
      // Try to get saved translation in short-term storage database.
      const filter = {
        userId: userId.toString(), // The user ID should be a string since it's a string we get from website user data.
        simName: simName,
        locale: locale
      };
      const savedTranslation = await shortTermStringStorageCollection.findOne( filter );
```

**Comment by liammulh** [comment]
> Okay, here's an idea: What if local check-login data is different from Ox-Dev check-login data? That might explain why I'm not seeing this issue locally, and the filer (see below) might be wrong on Ox-Dev.

I don't think this is the case. I hit the check-login route, and my user ID was a string. Next step is to log the filter then try to use the filter to find the saved translation.

**Comment by liammulh** [comment]
Oh, this is very sad:

```
Jan 25 11:39:21 phet-server-dev.int.colorado.edu rosetta[55642]: ----------> filter = {
Jan 25 11:39:21 phet-server-dev.int.colorado.edu rosetta[55642]: "userId": "654321",
Jan 25 11:39:21 phet-server-dev.int.colorado.edu rosetta[55642]: "simName": "diffusion",
Jan 25 11:39:21 phet-server-dev.int.colorado.edu rosetta[55642]: "locale": "fo"
Jan 25 11:39:21 phet-server-dev.int.colorado.edu rosetta[55642]: }
```

654321 is from the mock website user data.

Indeed, the environment config key is set to development:

```
Jan 25 11:36:11 phet-server-dev.int.colorado.edu rosetta[55642]: info: rosetta started
Jan 25 11:36:11 phet-server-dev.int.colorado.edu rosetta[55642]: info: http://localhost:16372/translate
Jan 25 11:36:11 phet-server-dev.int.colorado.edu rosetta[55642]: info: see config below
[...]
Jan 25 11:36:11 phet-server-dev.int.colorado.edu rosetta[55642]: info:     ENVIRONMENT: development
```

Mystery solved, I think. I will set it to production and try to reproduce the problem.

**Comment by liammulh** [comment]
I switched the environment config key to production:

```
Jan 25 11:44:47 phet-server-dev.int.colorado.edu rosetta[56853]: info: rosetta started
Jan 25 11:44:47 phet-server-dev.int.colorado.edu rosetta[56853]: info: http://localhost:16372/translate
Jan 25 11:44:47 phet-server-dev.int.colorado.edu rosetta[56853]: info: see config below
[...]
Jan 25 11:44:47 phet-server-dev.int.colorado.edu rosetta[56853]: info:     ENVIRONMENT: production
```

And now I'm seeing the saved translation showing up:

```
Jan 25 11:44:59 phet-server-dev.int.colorado.edu rosetta[56853]: info: getting translation form data
Jan 25 11:44:59 phet-server-dev.int.colorado.edu rosetta[56853]: info: checking for saved translation
Jan 25 11:44:59 phet-server-dev.int.colorado.edu rosetta[56853]: ----------> filter = {
Jan 25 11:44:59 phet-server-dev.int.colorado.edu rosetta[56853]: "userId": "464468",
Jan 25 11:44:59 phet-server-dev.int.colorado.edu rosetta[56853]: "simName": "diffusion",
Jan 25 11:44:59 phet-server-dev.int.colorado.edu rosetta[56853]: "locale": "fo"
Jan 25 11:44:59 phet-server-dev.int.colorado.edu rosetta[56853]: }
Jan 25 11:44:59 phet-server-dev.int.colorado.edu rosetta[56853]: info: found saved translation; returning it
Jan 25 11:44:59 phet-server-dev.int.colorado.edu rosetta[56853]: info: responding with fo/diffusion's translation form data
```

**Comment by Nancy-Salpepi** [comment]
This looks good in round 3. Will reopen if something else comes up.
