### ISSUE TITLE
Shared strings aren't showing in the test sim

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/rosetta#361]
**Test device**
MacBook Air (m1 chip)

**Operating System**
13.1

**Browser**
safari 16.2

**Problem description**
For https://github.com/phetsims/qa/issues/878, changes to shared strings don't show up when I press Test.

**Steps to reproduce**
1. Choose Faroese
2. Select Diffusion
3. Change the name of the sim (Sim-Specific String)
4. Change some Shared Strings
5. Press Test --the change to the sim-specific string is there, but not the shared strings.

**Visuals**
<img width="1176" alt="Screenshot 2023-01-23 at 1 20 42 PM" src="https://user-images.githubusercontent.com/87318828/214124443-ef8120bd-64bb-4cd4-a73f-a99c1f8d638f.png">
<img width="307" alt="Screenshot 2023-01-23 at 1 22 38 PM" src="https://user-images.githubusercontent.com/87318828/214124480-4ef556e2-5157-4278-a1a5-d39d7400e909.png">

**Comment by liammulh** [comment]
Thanks, @Nancy-Salpepi! I wouldn't have caught this.

**Comment by liammulh** [comment]
The first thing to do would be to log the translation in the client-side `testTranslation.js` module to ensure the shared strings are being sent to the server.

**Comment by liammulh** [comment]
Well, I checked `getReplacementStringObject.js` before logging the translation on the client-side, and it seems the code there doesn't take shared strings into consideration. We'll need to add support for shared strings in `getReplacementStringObject.js`.

**Comment by liammulh** [comment]
I think done in https://github.com/phetsims/rosetta/commit/673ac578290d6335797101990f1d7ea662a97e30.

This will need thorough testing.

**Comment by stemilymill** [comment]
looks good in round 3 testing
