### ISSUE TITLE
Rosetta row is gray on CT

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#366]
I just looked at CT and noticed that Rosetta is now gray.  I've never seen this before, and I'm not sure what it means, but we should investigate.  This is likely due to switching master to contain the Rosetta 2.0 code, which was done yesterday.

I think the only thing we used to do in CT for Rosetta 1 was to run lint, so there may be some configuring necessary here.

![image](https://user-images.githubusercontent.com/3082831/217964392-60bb1352-017d-436f-9160-0c9724a53eb9.png)

**Comment by liammulh** [comment]
Original issue might be fixed in https://github.com/phetsims/rosetta/commit/30967d1c027ce37629c39a3718f851f814a4d85b. We will need to keep an eye on CTQ.

Another (possibly related?) issue has cropped up. There is now no row for Rosetta on CTQ:

<img width="846" alt="ctq-rose" src="https://user-images.githubusercontent.com/60749003/219167004-169c1a87-e191-4897-ad2d-26aeeb20929e.png">

**Comment by liammulh** [comment]
For future reference:

When I merged the Rosetta 2.0 dev branch into the master branch, I started to see issues with Rosetta's row on CTQ. One of the errors we saw in Perennial was:

```
code: 1
stdout:
Running "lint-everything" task
Fatal error: Perennial task failed:
Error: Failed to load parser '@babel/eslint-parser' declared in '../rosetta/.eslintrc.cjs': Cannot find module '@babel/eslint-parser'
Require stack:
- /data/share/phet/continuous-quick-server/rosetta/.eslintrc.cjs
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
at Function.resolve (internal/modules/cjs/helpers.js:94:19)
at Object.resolve (/data/share/phet/continuous-quick-server/chipper/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2325:46)
at ConfigArrayFactory._loadParser (/data/share/phet/continuous-quick-server/chipper/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3304:39)
at ConfigArrayFactory._normalizeObjectConfigDataBody (/data/share/phet/continuous-quick-server/chipper/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3078:43)
at _normalizeObjectConfigDataBody.next (<anonymous>)
at ConfigArrayFactory._normalizeObjectConfigData (/data/share/phet/continuous-quick-server/chipper/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3019:20)
at _normalizeObjectConfigData.next (<anonymous>)
at ConfigArrayFactory.loadInDirectory (/data/share/phet/continuous-quick-server/chipper/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2865:28)
at CascadingConfigArrayFactory._loadConfigInAncestors (/data/share/phet/continuous-quick-server/chipper/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3848:46)
Full Error details:
Error: Failed to load parser '@babel/eslint-parser' declared in '../rosetta/.eslintrc.cjs': Cannot find module '@babel/eslint-parser'
Require stack:
- /data/share/phet/continuous-quick-server/rosetta/.eslintrc.cjs
```

So Perennial's row was red, and Rosetta's row was gray.

In https://github.com/phetsims/rosetta/commit/30967d1c027ce37629c39a3718f851f814a4d85b, @samreid and I SSH'd to Bayes, ran `npm i` in Rosetta, noticed that there were two warnings, one about not having `@babel/core` and another about not having `eslint` as dependencies. We installed them, and then when we ran `grunt lint-everything` from phetsims/perennial, we no longer saw the error about not being able to find `@babel/eslint-parser`. We did however see a warning about not being able to find the `react` package.

**Comment by liammulh** [comment]
> Does the rosetta file need to be named cjs? It isn't idiomatic to our grunt files generally.

I provided an explanation for why the file extension is `.cjs` in https://github.com/phetsims/rosetta/issues/371. We could make it `.js`, but that would necessitate using CommonJS modules throughout Rosetta's Node code, which is something that we were initially doing, but @jbphet and I decided that we wanted to use ECMAScript modules because they are consistent with how we do imports/exports in client-side code and (we think) becoming the standard.

**Comment by zepumph** [comment]
Yes, I understand, in that case, I recommend adding rosetta linting to CT in this way, I don't want to hard code `.cjs` into listContinuousTests, it doesn't seem very prudent. Please review.

**Comment by liammulh** [comment]
This looks good, thank you, @zepumph! I'm now seeing a row for Rosetta:

<img width="700" alt="row" src="https://user-images.githubusercontent.com/60749003/220786436-aad0d68c-fc99-43fc-8035-00814fd678c7.png">
