### ISSUE TITLE
Add default "Select Locale" option to Select Locale dropdown

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/rosetta#367]
@liammulh when reading through your draft user guide, I realized it would be better UX to just have the Locale dropdown default to "Select Locale" (currently it defaults to "Abkhazian"). Force the user to select a locale before 'Translate' is enabled.

This should prevents/reduce the likely hood of a translator unintentionally selecting Abkhazian and forces the translator to intentionally select a locale before Translating.

**Comment by liammulh** [comment]
Done in https://github.com/phetsims/rosetta/commit/f7b81ec157ad393ddb8c1d15a1078ad6853ba3f9.
