### ISSUE TITLE
String key order in the debug info

### ISSUE THREAD

**Issue by phet-steele** [phetsims/rosetta#37]
This is mostly a non-issue, more of just something that is bugging me. The string keys aren't shown in the same order in the debug info as they are on the previous page. I translated the strings in numerical order, but after submitting they are anything but ordered. The string keys don't even look alphabetized. Is it do able, or even a good idea, to clean this up a bit so that the debug info screen matches the order of the strings I'm translating?

The awkward break in the photo is because this is actually two photos that didn't line up well:

![string order](https://cloud.githubusercontent.com/assets/5863899/9206994/297a0b34-4028-11e5-99d8-ea9c16084d77.PNG)
![string order 2](https://cloud.githubusercontent.com/assets/5863899/9207000/2f8c6364-4028-11e5-8c75-f60e55c61e8a.PNG)

**Comment by aaronsamuel137** [comment]
I think this will be fixed now that #52 is fixed. Closing for now.
