### ISSUE TITLE
screen name issue for single-screen sims

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rosetta#38]
A general issue identified by @phet-steele, and illustrated in the Concentration sim.

ConcentrationScreen gets its name from key "BEERS_LAW_LAB/tab.concentration".  That screen appears in the Concentration sim, but it's screen name is not visible because the sim is a single-screen sim, and therefore has no home screen or screen icons in the navbar.

This is a  general issue that will occur for any single-screen sim that gets its single screen from some other sim.  The screen name will appear in Rosetta, but will not appear anywhere in the sim.

Not sure who to assign this to, so I'll start with @jbphet.

**Comment by jbphet** [comment]
We've changed the handling of sim names a bit since this issue was logged, but I'm not entirely sure whether this issue has been fully addressed.  Assigning to @aaronsamuel137 to answer and, if he's not sure, he can assign back to me and I'll dig a little deeper.

**Comment by aaronsamuel137** [comment]
This is still an issue. Looks like the string is now called "screen.concentration", but it doesn't appear anywhere in the sim, and yet it is available to translate.

My thought is that we ignore this for 1.0. I'm not sure what the best way of addressing it will be. It will likely be easier to address when we add support for string metadata (#34), though we'd still need some way of knowing whether or not a sim is single screen, which I am not sure if we have.

Assigning back to @jbphet for suggestions, or maybe a "not for 1.0" label.

**Comment by jbphet** [comment]
This is what the issue looks like on the current version of the translation page (I've highlighted the 'string of concern'):

![rosetta-screen-name-issue](https://cloud.githubusercontent.com/assets/3082831/10325766/8d45b4ce-6c51-11e5-9300-013ea285a5ba.png)

This doesn't seem like a huge deal to me, and I agree that it isn't vital to address it for 1.0.  I will add the "not for 1.0" label.

As for how to address this in the long term, here is a proposal: When we add metadata for strings, we define something that can be used to identify these strings as screen titles.  If there is only one string for a given sim that is identified as a screen title, it isn't presented to the user for translation.

A more hackish way of doing it that doesn't require metadata is to require that all sims identify screen titles like ```screen.<title>```, as is done in Concentration but is not currently done in all sims.  Similar to the previous suggestion, the number of strings with the ```screen.``` prefix could be counted and, if there's only one, it wouldn't be presented for translation.

Assigning to @aaronsamuel137 to see if he has any other suggestions or critiques of the above.  After that, let's unassign until we start working on the next version.

**Comment by jbphet** [comment]
One other thought: We could also decide that it's not worth addressing at all.  It will only be an issue in cases where the single-screen sim is translated before its multi-screen "parent" sim, and translating this string will actually be a step towards full translation of the parent sim.

**Comment by pixelzoom** [comment]
+1 for not addressing at all.

**Comment by aaronsamuel137** [comment]
I agree with @pixelzoom here. Seems like such a minor issue that it's not worth complicating the code even more to fix it.

**Comment by jbphet** [comment]
Awesome.  Let's call it good then.  Closing.
