### ISSUE TITLE
Remove en_GB Unit Rates Translation

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/rosetta#385]
During a recent meeting, we noticed en_GB only has one translation (Unit Rates) and the translation is unnecessary. There is a similar en_CA translation that is the "metric" version of the sim and is linked in the teacher tips.

- [x] remove string file from babel (@liammulh please do this)
  - Done in https://github.com/phetsims/babel/commit/29b93d16fd82e846fc79b1ffe511a7a96bbf0fcd.
- [x] remove sim from website (@mattpen, can you please do this?)
- [ ] @jonathanolson there are an (insignificant) number of yotta runs for this sim - can these be cleaned up or deleted?

**Comment by oliver-phet** [comment]
(copying steps from https://github.com/phetsims/rosetta/issues/326)

**Comment by jonathanolson** [comment]
> can these be cleaned up or deleted?

Yes, I think it will be cleaned up after it is deleted AND I handle the removal on yotta's side.

Please let me know when this is deleted, and I'll handle it on the yotta side.

**Comment by jonathanolson** [comment]
Yotta updated, I'll check back in tomorrow if it's failing.

**Comment by jonathanolson** [comment]
Yotta changes worked successfully, unassigning.

**Comment by mattpen** [comment]
@jbphet @oliver-phet @jonathanolson  - Can you please let me know if you have any opinions on this comment: https://github.com/phetsims/rosetta/issues/385#issuecomment-1476670180?  If not, I'm inclined to just leave the files there.

**Comment by jonathanolson** [comment]
I don't mind having the files there.

**Comment by oliver-phet** [comment]
Fine leaving them.

**Comment by mattpen** [comment]
Ok, I think this is complete.
