### ISSUE TITLE
Commits being made where the only thing updated is the timestamp

### ISSUE THREAD

**Issue by liammulh** [phetsims/rosetta#386]
There are commits being made where the only thing updated is the timestamp. For example: https://github.com/phetsims/babel/commit/0efa03f8201ad54664776e0298fe5d17777c9001.

**Comment by liammulh** [comment]
In https://github.com/phetsims/babel/commit/0efa03f8201ad54664776e0298fe5d17777c9001, I am seeing:

```
-        "timestamp": 1678469359868,
+        "timestamp": 1678469420004,
```

I converted these times.

### Top (-) 1678469359868

Assuming that this timestamp is in milliseconds:
GMT: Friday, March 10, 2023 5:29:19.868 PM
Your time zone: Friday, March 10, 2023 10:29:19.868 AM [GMT-07:00](https://www.epochconverter.com/timezones?q=1678469359868)

### Bottom (+) 1678469420004

Assuming that this timestamp is in milliseconds:
GMT: Friday, March 10, 2023 5:30:20.004 PM
Your time zone: Friday, March 10, 2023 10:30:20.004 AM [GMT-07:00](https://www.epochconverter.com/timezones?q=1678469420004)

**Comment by liammulh** [comment]
I saved the relevant logs in my home directory on phet-server2 in a file called `386-investigation.log`.

**Comment by liammulh** [comment]
It looks like in order to reproduce this, you need to hit the publish (submit) button twice:

### First submit
```
Mar 10 10:29:23 phet-server2.int.colorado.edu rosetta[1209126]: info: post request received for /submitTranslation
Mar 10 10:29:23 phet-server2.int.colorado.edu rosetta[1209126]: info: attempting to submit translation
Mar 10 10:29:23 phet-server2.int.colorado.edu rosetta[1209126]: info: sending pl/states-of-matter-basics translation to be prepared for long-term storage
```

### Second submit
```
Mar 10 10:30:23 phet-server2.int.colorado.edu rosetta[1209126]: info: post request received for /submitTranslation
Mar 10 10:30:23 phet-server2.int.colorado.edu rosetta[1209126]: info: attempting to submit translation
Mar 10 10:30:23 phet-server2.int.colorado.edu rosetta[1209126]: info: sending pl/states-of-matter-basics translation to be prepared for long-term storage
```

**Comment by liammulh** [comment]
Try to reproduce:

- [ ] translate one string
- [ ] wait for a few seconds
- [ ] resubmit

**Comment by liammulh** [comment]
I was thinking about setting the form to dirty, but according to Formik docs:

> dirty: boolean
> Returns true if values are not deeply equal from initial values, false otherwise. dirty is a readonly computed property and _should not be mutated directly_. †

(Emphasis mine.)

† https://formik.org/docs/api/formik#dirty-boolean

**Comment by liammulh** [comment]
I just tested https://github.com/phetsims/rosetta/commit/aef51dc3b11603a2ec7847c918bd6626c9c20c9e locally with ab/chains, and it seems to be working.

**Comment by liammulh** [comment]
I just tested https://github.com/phetsims/rosetta/commit/aef51dc3b11603a2ec7847c918bd6626c9c20c9e locally with ab/chains, and it seems to be working.

**Comment by KatieWoe** [comment]
I didn't see extra commits when trying to reproduce this, but the pop-ups on the translate page still occurred.

**Comment by KatieWoe** [comment]
Discussed with @liammulh on zoom. Looks good

**Comment by liammulh** [comment]
Deployed in https://github.com/phetsims/rosetta/commit/6021626a17d44d4a05a0be5cb4a3cbf1a41ccb17 (2.0.7).
