### ISSUE TITLE
Investigate missing Azerbaijani (az) translations

### ISSUE THREAD

**Issue by liammulh** [phetsims/rosetta#389]
@solaolateju told me the Azerbaijani translators are missing some of their translations. When I look at the commits to phetsims/babel (using `git log --pretty=format:"%h%x09%an%x09%ad%x09%s" | grep "locale az" | less`), here are the most recent commits:

```
7cb6f90ec       phet-dev        Wed Aug 10 22:46:42 2022 -0600  automated commit from rosetta for sim/lib area-model-common, locale az
2a6a6dc25       phet-dev        Wed Aug 10 22:46:41 2022 -0600  automated commit from rosetta for sim/lib area-model-introduction, locale az
44e8f4fa6       phet-dev        Tue Aug 9 06:08:32 2022 -0600   automated commit from rosetta for sim/lib arithmetic, locale az
266b32fb1       phet-dev        Tue Aug 9 05:57:06 2022 -0600   automated commit from rosetta for sim/lib area-model-common, locale az
```

The most recent commit was August 10, 2022. Are the Azerbaijani translators unable to submit their translations, @solaolateju? That is, are they able to click the publish button?

**Comment by solaolateju** [comment]
Could this be published sims only? 
They are a team of 4+ translators who have been working since last year until 3 weeks ago. Recent translation efforts were saved not published. 
Are you able to check where saved work is stored? I am of the opinion it is to a different database.

**Comment by solaolateju** [comment]
@liammulh 
Could @mattpen be of help with this? Should I ask for his help with probing? It would help to know if there are SAVED translated strings stored elsewhere between September 2022 - February 2023.

**Comment by mattpen** [comment]
@solaolateju - @liammulh is the owner for the rosetta code and would best be able to answer questions about saved translations.  I can help if there are questions about missing credits on the website.

**Comment by liammulh** [comment]
> I am of the opinion it is to a different database.

I think you are right, @solaolateju. When we started Rosetta 2.0, we started using a new short-term storage database as well. So I think we still have their translations, but they are in our old short-term storage database.

Getting the translations out of the old short-term storage database and into Rosetta 2.0 is going to be hard, and (as of this writing) I don't have any PhET hours left for the month of March. (I work on two different projects at CU — PhET and a different one in the math department.)

So, @solaolateju, please tell the translators I am sorry about this, but please also tell them that in the future they should publish their translations as soon as possible rather than saving them to the short-term storage database.

**Comment by jbphet** [comment]
@mattpen extracted the data from the DB table used for short-term storage in Rosetta 1.  I have started writing a script to process this data, but have a ways to go before I'll be ready to commit it.

**Comment by jbphet** [comment]
I've just processed the data in the DB, and it looks like the Azerbaijani translators had quite a bit of unsubmitted work.  For reference, here is the list of modified and new files that will be committed into the strings repo (babel) as part of the recovery effort:

- Modified string files:
  - balancing-act/balancing-act-strings_az.json
  - circuit-construction-kit-common/circuit-construction-kit-common-strings_az.json
  - circuit-construction-kit-dc/circuit-construction-kit-dc-strings_az.json
  - color-vision/color-vision-strings_az.json
  - gravity-and-orbits/gravity-and-orbits-strings_az.json
  - gravity-force-lab/gravity-force-lab-strings_az.json
  - inverse-square-law-common/inverse-square-law-common-strings_az.json
  - joist/joist-strings_az.json
  - scenery-phet/scenery-phet-strings_az.json
  - states-of-matter/states-of-matter-strings_az.json
  - vegas/vegas-strings_az.json
  - wave-interference/wave-interference-strings_az.json

- Added string files:
  - beers-law-lab/beers-law-lab-strings_az.json
  - build-a-fraction/build-a-fraction-strings_az.json
  - circuit-construction-kit-ac-virtual-lab/circuit-construction-kit-ac-virtual-lab-strings_az.json
  - circuit-construction-kit-ac/circuit-construction-kit-ac-strings_az.json
  - collision-lab/collision-lab-strings_az.json
  - curve-fitting/curve-fitting-strings_az.json
  - diffusion/diffusion-strings_az.json
  - energy-forms-and-changes/energy-forms-and-changes-strings_az.json
  - energy-skate-park/energy-skate-park-strings_az.json
  - equality-explorer-basics/equality-explorer-basics-strings_az.json
  - equality-explorer-two-variables/equality-explorer-two-variables-strings_az.json
  - equality-explorer/equality-explorer-strings_az.json
  - expression-exchange/expression-exchange-strings_az.json
  - fraction-matcher/fraction-matcher-strings_az.json
  - fractions-common/fractions-common-strings_az.json
  - fractions-equality/fractions-equality-strings_az.json
  - fractions-intro/fractions-intro-strings_az.json
  - fractions-mixed-numbers/fractions-mixed-numbers-strings_az.json
  - function-builder-basics/function-builder-basics-strings_az.json
  - function-builder/function-builder-strings_az.json
  - gas-properties/gas-properties-strings_az.json
  - gene-expression-essentials/gene-expression-essentials-strings_az.json
  - geometric-optics/geometric-optics-strings_az.json
  - graphing-lines/graphing-lines-strings_az.json
  - graphing-quadratics/graphing-quadratics-strings_az.json
  - graphing-slope-intercept/graphing-slope-intercept-strings_az.json
  - gravity-force-lab-basics/gravity-force-lab-basics-strings_az.json
  - greenhouse-effect/greenhouse-effect-strings_az.json
  - make-a-ten/make-a-ten-strings_az.json
  - molecules-and-light/molecules-and-light-strings_az.json
  - natural-selection/natural-selection-strings_az.json
  - neuron/neuron-strings_az.json
  - normal-modes/normal-modes-strings_az.json
  - number-line-common/number-line-common-strings_az.json
  - number-line-distance/number-line-distance-strings_az.json
  - number-line-integers/number-line-integers-strings_az.json
  - number-line-operations/number-line-operations-strings_az.json
  - proportion-playground/proportion-playground-strings_az.json
  - ratio-and-proportion/ratio-and-proportion-strings_az.json
  - tangible/tangible-strings_az.json
  - trig-tour/trig-tour-strings_az.json
  - unit-rates/unit-rates-strings_az.json
  - vector-addition-equations/vector-addition-equations-strings_az.json
  - waves-intro/waves-intro-strings_az.json

**Comment by jbphet** [comment]
I ran a script overnight to build all of the `az` translations.  It didn't quite complete (I think because my laptop went to sleep), but it resumed in the morning and finished around 10 or 11 AM today.  I just spot checked several `az` translations, and they are new available on the website.  I think the bulk of the work is done here, but I'll follow up with @RVieyra and @solaolateju before closing this issue.

**Comment by jbphet** [comment]
Cool, sounds like our work here is done.  Closing.
