### ISSUE TITLE
The utility loses sim context and makes it more difficult to translate similar words differently

### ISSUE THREAD

**Issue by phet-steele** [phetsims/rosetta#39]
While translating Concentration, the utility asks the user to translate the word "Concentration" three separate times due to the sim using three different string keys for that word (one of which shouldn't be there, see #38). @pixelzoom informed me that at times this is done on purpose to allow translators to translate the same word differently in different contexts of the sim, say a screen name vs. a slider label. However, in the utility's current state, this context is completely lost while translating. A translator doesn't know for instance which "Concentration" he is translating except by trial and error of using the "Test" button.

@jbphet says this is known, somewhat, and hopefully somewhere in the future this issue will be slightly remedied. This ticket will serve then as a reminder and place for discussion.

**Comment by pixelzoom** [comment]
Adding support for metadata (e.g., a description of where a string is used) in the JSON string files would be a step in the right direction.  Choosing descriptive string keys would also be helpful, especially if we had some conventions for this.  Eg, something like "screen.concentration", "screen.beersLawLab" for the 2 screens in beers-law-lab.

**Comment by liammulh** [comment]
> Choosing descriptive string keys would also be helpful, especially if we had some conventions for this. Eg, something like "screen.concentration", "screen.beersLawLab" for the 2 screens in beers-law-lab.

I believe this is common practice for sim devs creating string keys for a long time now. I think translators are used to dealing with this sort of thing at this point. I am going to close this issue.

In a future version of Rosetta, what would be really nice is if you could view the sim while translating it. So you'd click on a string, and a little text area modal would pop up for you to enter your translation.
