### ISSUE TITLE
Shared string count in Concentration

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/rosetta#390]
> I'm using new translation utility on PhET, however the statistics number of translated strings on some simulations are strange and wrong.  Like this one:
> https://phet.colorado.edu/translate/zh_TW/concentration

@liammulh I'm still not fully grasping how shared strings are handled. There are 31 shared strings available to translate when viewing Concentration, but the statistics (zh_TW) says "Shared Strings: 88% (38 of 43)"

This is confusing to translators as well. Is there an issue counting the shared strings correctly? Or are some hidden?

**Comment by liammulh** [comment]
There are 31 shared string in Concentration coming from Beers Law Lab. In BLL, there are 43 strings.

When writing the code, I thought that if sim A and sim B share strings, and if we already got the shared string stats for sim A, then those stats could be used for sim B. What I didn't realize at the time was that sim B might only use a strict subset of sim A's strings.

Here is the relevant code:

https://github.com/phetsims/rosetta/blob/a3629a72bc161c0ef6ed136bf338f8e9df05c725/src/server/translationApi/translationReport/getTranslationReportObject.js#L122-L127

**Comment by liammulh** [comment]
There is another problem with the way shared strings are computed. The number of shared strings for a sim is simply `categorizedStringKeys.shared.length` (just the string keys in the sim). It is being incorrectly set:

https://github.com/phetsims/rosetta/blob/a3629a72bc161c0ef6ed136bf338f8e9df05c725/src/server/translationApi/translationReport/getTranslationReportObject.js#L146-L148

The above code sets `numSharedStrings` for the last sim in the `sharedSims` array that we loop over here:

https://github.com/phetsims/rosetta/blob/a3629a72bc161c0ef6ed136bf338f8e9df05c725/src/server/translationApi/translationReport/getTranslationReportObject.js#L120

Thus, for Concentration, the number of shared strings is 43 regardless of whether we remove the `cachedSharedObject` conditional I linked to in https://github.com/phetsims/rosetta/issues/390#issuecomment-1496298745.

**Comment by liammulh** [comment]
I have a patch that removes the conditional linked in https://github.com/phetsims/rosetta/issues/390#issuecomment-1496298745 and fixes the problem with the computation of `numSharedStrings` as described in https://github.com/phetsims/rosetta/issues/390#issuecomment-1496444463. I believe it is correctly counting the shared strings now:

<img width="600" alt="concentration" src="https://user-images.githubusercontent.com/60749003/230177746-c1ece69c-63fb-411a-858a-8eedbd23bbae.png">

<img width="600" alt="bll" src="https://user-images.githubusercontent.com/60749003/230177788-97fdfdef-4ed5-486f-896e-9aef9cca68a8.png">

**Comment by liammulh** [comment]
Another few test cases:

- Child / Parent
- Atomic Interactions / States of Matter
- States of Matter: Basics / States of Matter
- Molecules and Light / Greenhouse Effect

**Comment by liammulh** [comment]
I'm going to do a bit more testing before deploy.

**Comment by liammulh** [comment]
When I downloaded the HTML files, here are the stats:

- Child / Parent
- Atomic Interactions, shared = 27 / States of Matter, sim-specific = 52
- States of Matter: Basics, shared = 33 / States of Matter, sim-specific = 52

When I looked at the patched translation utility:

- Child / Parent
- Atomic Interactions, shared = 27 / States of Matter, sim-specific = 52
- States of Matter: Basics, shared = 33 / States of Matter, sim-specific = 52

(MAL and Greenhouse seemingly don't share strings.)

**Comment by liammulh** [comment]
@oliver-phet, this fix is live. Please thank the translator and close this issue when you are done.

**Comment by oliver-phet** [comment]
@liammulh the zh_TW translator is still seeing the same issue on 3 sims:
Masses and Springs: Basics
Molecule Shapes: Basics
Molecule Shapes

All 3 seem to have 2 shared strings that aren't available to translate, but are included in the info statistics (all strings are translated).
![Screenshot_20230408_081345](https://user-images.githubusercontent.com/5090275/230928617-d298e5de-15b4-499b-934b-b6b08b91f2df.png)

**Comment by liammulh** [comment]
This is done. See https://github.com/phetsims/molecule-shapes/issues/252.
