### ISSUE TITLE
Nothing is being translated for "Concentration" sim

### ISSUE THREAD

**Issue by phet-steele** [phetsims/rosetta#40]
The only thing that correctly updates is "concentration.name" (the last Concentration string in the list), which I believe is the only string that comes from the Concentration repo.

**Comment by pixelzoom** [comment]
Correct that "concentration.name" is the only key in concentration-strings_en.json (it's the sim title).  All other strings come from beers-law-lab, or possibly from common-code repos.

**Comment by phet-steele** [comment]
This was fixed at some point in the past, Concentration translates correctly.
