### ISSUE TITLE
Figure out why dev script isn't working

### ISSUE THREAD

**Issue by liammulh** [phetsims/rosetta#409]
If you `npm run dev`, and then you go to the URL, (http://localhost:5173/, as of this writing), you will see Rosetta is having some sort of issue with CORS:

```
[Error] Origin http://localhost:5173 is not allowed by Access-Control-Allow-Origin. Status code: 200
[Error] XMLHttpRequest cannot load http://localhost:16372/services/check-login due to access control checks.
[Error] Failed to load resource: Origin http://localhost:5173 is not allowed by Access-Control-Allow-Origin. Status code: 200 (check-login, line 0)
```

This doesn't make a ton of sense to me, as I'm pretty sure I already dealt with this:

https://github.com/phetsims/rosetta/blob/cc791109a0a6a3c39c94368825b5345ff55e0c23/src/server/app.js#L37-L48

**Comment by jbphet** [comment]
I am using the `dev` script and not seeing the problems that are described above.  I recent made a number of changes to the `dev` script for #435 - perhaps that fixed things.  At any rate, this is no longer repeatable or problematic, so I'm going to close it.
