### ISSUE TITLE
Common strings can become empty unintentionally

### ISSUE THREAD

**Issue by phet-steele** [phetsims/rosetta#41]
An interesting issue where common strings can be deleted:

1. I went to the translation utility and selected the sim "Chains" and language "Czech (cs)".

2. Scrolling down to common strings, I inputted my translation for adapted\nfrom (string key: adaptedFrom).
3. I submitted the translation and had the resulting commit: https://github.com/phetsims/babel/commit/d596de5db53c530fde06ce8c3f067b12d87511a9

4. I then switched the sim I was translating to Molecules & Light, while remaining in the Czech locale.
5. Without inputting any translations I clicked on submit and it resulted in this commit: https://github.com/phetsims/babel/commit/31e322761dbffe7d3505703ce8afce8d3e3fa90c

My hunch here as to why the second commit deleted my translation for adaptedFrom is because Molecules & Light did not have this string available to translate. So when I submitted the second time, it treated that as me placing an empty value in adaptedFrom.

Here is the string in Chains:
![chains common](https://cloud.githubusercontent.com/assets/5863899/9210976/67d4e6ce-403c-11e5-9886-8de763c60834.PNG)

But is not an option in Molecules & Light:
![m l common](https://cloud.githubusercontent.com/assets/5863899/9210997/876ec234-403c-11e5-868e-f6b1b20eaac7.PNG)

The other strings that are not shared between the two sims exhibit the same issue. Also, the debug info said nothing about the second commit.

**Comment by aaronsamuel137** [comment]
I think the more general issue here is this:

Rosetta currently doesn't handle a case where different sims contain different subsets of the strings from a given repo. This issue came up because I accidentally publish MAL on phet-dev as "adapted-from-phet" brand instead of "phet". Because of this, MAL uses a different subset of joist strings than a phet branded sim will. In this case, the strings not present in a translation will get deleted from babel.

**Comment by aaronsamuel137** [comment]
Let me know if this is working for you now @phet-steele

**Comment by phet-steele** [comment]
Not yet.

**Comment by aaronsamuel137** [comment]
Let me know if it is working for you now, @phet-steele.

**Comment by phet-steele** [comment]
Yep, this time it is.
