### ISSUE TITLE
Add validation for sim title

### ISSUE THREAD

**Issue by chrisklus** [phetsims/rosetta#419]
From https://github.com/phetsims/perennial/issues/326 and discussion with @jbphet and @zepumph:

The build process requires a title for any language it's building, but rosetta allows a translation to be submitted without a title. This would require a large maintenance release to fix on the chipper side, so we agreed to add some validation in rosetta. @jbphet is up for this, thanks! I'm happy to review the UX when you're finished if you'd like a tester.

**Comment by jbphet** [comment]
I've added validation of the sim title, essentially just requiring it to be filled in.  The `InputErrorMessage` component that shows the error message also included a button for additional information, and the only additional information currently supported was for the curly braces.  It looks like this:

![image](https://github.com/user-attachments/assets/8b0fc45c-114e-461c-a6cd-f578811739c8)

...and the dialog that comes up when the button is pressed looks like this:

![image](https://github.com/user-attachments/assets/39d2e085-9456-4722-9801-b8c7e5e73acb)

I modified the code to require the title and to omit the button for that case, and it looks like this:

![image](https://github.com/user-attachments/assets/8c8a1374-b6a5-44a0-9fca-e10eaadbba37)

The code has been tested in my local environment, but not yet deployed for the live version.  I'm about to head out for a vacation, so I'll test this a bit more and deploy it once I'm back.

**Comment by jbphet** [comment]
I've now tested this on ox-dev and deployed it to the main server (phet-server2).  I did some in situ testing of the behavior for the `ab` locale for the Chains sim, and it seems to be working correctly.  I think we can call this complete, closing.
