### ISSUE TITLE
Rosetta repo needs a license

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/rosetta#425]
Rosetta needs to have a license added to it. @jbphet - let's chat and add one this week!

**Comment by jbphet** [comment]
The 1.0 version had a license, so it's likely that it didn't get copied over when we cut the code base over to the 2.0 version.  It's a basic MIT license, and you can see it at https://github.com/phetsims/rosetta/blob/1.0/LICENSE.  Is this acceptable?

**Comment by kathy-phet** [comment]
Yes

**Comment by jbphet** [comment]
License added, closing.
