### ISSUE TITLE
Investigate and possibly change direction of Pushto locale

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#427]
I received the following this morning from @solaolateju over Slack:

> @solaolateju 
> Hello @jbphet
> Trust you are doing great.
> We have a new team working on Pushto.
> According to them, Pusto is a right-to-left language. It is current writing as left-to-right.
> Is it possible to change?

I told @solaolateju that I'd investigate and get back to him.

@mattpen - Tagging you on this in case it impacts website translation.  I'll assign you also, but feel free to unassign once you've evaluated whether the website needs anything done for this.

**Comment by jbphet** [comment]
Quote from https://celcar.indiana.edu/materials/language-portal/pashto/index.html:

> The Pashto Alphabet is based on the Perso-Arabic alphabet as used for Persian (Farsi and Dari). Like all Perso-Arabic scripts, Pashto is written and read from right to left[.]

I'm looking in our `localeInfo.json` file, and it is designated at `ltr`, meaning left-to-right, so it looks like it is incorrectly configured in our system.

**Comment by jbphet** [comment]
I updated the entry in `localeInfo.json` to reflect that this is a right-to-left language and restarted Rosetta.  It looks like it is now showing things in RTL format.  Here is a screenshot:

![image](https://github.com/phetsims/rosetta/assets/3082831/123cb8dc-7a4e-4013-9c43-ff8255de792e)

**Comment by jbphet** [comment]
@solaolateju - Can you please have the new team check this change and close the issue if all looks good?  Thanks.

**Comment by mattpen** [comment]
@jbphet - should we also update localeInfo.js and localeInfoModule.js?  The website is now derived from chipper, but I do need to run a process to update it (I did this morning).

**Comment by solaolateju** [comment]
@jbphet I will let you know once I hear back from the Pushto translation team.

**Comment by solaolateju** [comment]
Qudratullah from the Pushto translation team has confirmed the text direction issue has been resolved. Thank you @jbphet

**Comment by mattpen** [comment]
@solaolateju - this is fixed in rosetta, but probably isn't fixed elsewhere.  Keeping this open to propogate the change throughout the project.

**Comment by jbphet** [comment]
@mattpen - I'm going to unassign myself from this one.  Feel free to add me back if anything else is needed on my end.  It might be a good idea to set up a separate issue on this for the website.

**Comment by mattpen** [comment]
The pushto changes were propogated to localeInfo.json with the new update process, so this should be available in rosetta now too.  Closing.
