### ISSUE TITLE
Community Contribution sims aren't appearing in Translation Utility

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/rosetta#432]
This was reported by our _ht Haitian Creole translator.

Rosetta isn't currently displaying Sound Waves or Normal Modes (Community Contribution sims). 

Curiously, Sound Waves and Normal Modes currently have several translations. I _believe_ when these were tagged as "prototypes" they were translatable, but when the website was updated with Release Type, these two sims were re-tagged as Community Contributions.

**Comment by oliver-phet** [comment]
Adding that our Dari translator also asked about this bug - so it is certainly blocking translation of these community sims.

**Comment by jbphet** [comment]
It looks like a new flag was added to the metadata recently.  The flag is `isCommunity`, and I briefly searched through the website issues and maybe this one - https://github.com/phetsims/website-meteor/issues/608 - is where and when it was added.

Regardless, I wasn't aware of this change, so the Rosetta code didn't handle it.  I've added handling for it now and will test it out on phet-server-dev and, if everything looks good, I'll deploy in the live version.

**Comment by jbphet** [comment]
For reference, this is the SHA where `isCommunity` was added to the metadata: https://github.com/phetsims/website/commit/7d29f625d560e282688f4569bac1929df75c02e1.

**Comment by jbphet** [comment]
This should now be fixed and deployed to the live version of Rosetta.  For my reference, the SHA which was deployed is 6d8dce20edd10a3de52549cd4a4c83197e9b85ff.

@oliver-phet - Can you please double check that the previously missing sims are now available?  Also feel free to assign @solaolateju if we'd like him to verify as well.

**Comment by oliver-phet** [comment]
Looks good to me (I checked Dari, Haitian, and Abkhazian)

**Comment by jbphet** [comment]
Cool, thanks for checking it.  Closing.
