### ISSUE TITLE
Update version of NodeJS being used by Rosetta on the main server

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#438]
In #405 the version of NodeJS used on the test server - phet-server-dev - was updated.  We should also update the version being used on the main server.

The version currently in use on phet-sever-dev is the latest Long Term Support (LTS) version, which is 20.16.0.  I'll plan to target that version on the live version (which runs on phet-server2) too.

As of this moment, and according to the service file `/etc/systemd/system/rosetta.service` on phet-server2, the version of NodeJS in use there is v16.14.2.

**Comment by jbphet** [comment]
@zepumph and I just worked on this for a bit since he had been working on updating the Node version for the build server recently.  We attempted to update the version that Rosetta is using to v20.18.0, but ran into problems and had to revert.  We essentially just modified the service file to point to v20.18.0 in the two paths that include the node version in them, did the daemon reload, and tried the systemctl restart, but it didn't work.  There were several errors in the service log.  We subsequently tried updating the SE Linux permissions for several of the node-related commands (e.g. npm) using some commands that @zepumph had used recently, but that didn't seem to do the trick either.  I pinged @mattpen about it, and he said he is available this Friday, so I'll set something up to work with him on it.

**Comment by mattpen** [comment]
```
Oct 29 15:43:49 phet-server2.int.colorado.edu setroubleshoot[587292]: SELinux is preventing /usr/lib/systemd/systemd from execute access on the file npm-cli.js. For complete SELinux messages run: sealert>
Oct 29 15:43:49 phet-server2.int.colorado.edu setroubleshoot[587292]: SELinux is preventing /usr/lib/systemd/systemd from execute access on the file npm-cli.js.
                                                                      
                                                                      *****  Plugin file (73.6 confidence) suggests   ******************************
                                                                      
                                                                      If you think this is caused by a badly mislabeled machine.
                                                                      Then you need to fully relabel.
                                                                      Do
                                                                      touch /.autorelabel; reboot
                                                                      
                                                                      *****  Plugin file (73.6 confidence) suggests   ******************************
                                                                      
                                                                      If you think this is caused by a badly mislabeled machine.
                                                                      Then you need to fully relabel.
                                                                      Do
                                                                      touch /.autorelabel; reboot
                                                                      
                                                                      *****  Plugin catchall (2.93 confidence) suggests   **************************
                                                                      
                                                                      If you believe that systemd should be allowed execute access on the npm-cli.js file by default.
                                                                      Then you should report this as a bug.
                                                                      You can generate a local policy module to allow this access.
                                                                      Do
                                                                      allow this access for now by executing:
                                                                      # ausearch -c '(node)' --raw | audit2allow -M my-node
                                                                      # semodule -X 300 -i my-node.pp
                                                                      ```
I think this is the problem. And I think the third suggested solution should solve it, but I'm not sure what you tried when you say "We subsequently tried updating the SE Linux permissions for several of the node-related commands (e.g. npm)".  It looks like they are all bin_t type, which I think is correct, but maybe there is some other reason for the AVC denial.

**Comment by zepumph** [comment]
Adding bin_t to all runnables in v20.18.0/bin/ is all we did. We then gave up when that still didn't work.


Can you post the command you did to view those logs again?

**Comment by zepumph** [comment]
I'm not really sure how to proceed. I don't believe that updating these runnables are correct, aren't these just symlinked to from the top level bin? I also really didn't understand the above command (how does it know what my-node` is when I don't?)


```
[phet-admin@phet-server2 v20.18.0]$ ls -lZ ./lib/node_modules/npm/bin
total 36
drwxr-xr-x. 2 phet-admin phet-admin unconfined_u:object_r:unlabeled_t:s0   42 Oct  3 02:30 node-gyp-bin
-rwxr-xr-x. 1 phet-admin phet-admin unconfined_u:object_r:unlabeled_t:s0 2073 Apr 11  2024 npm
-rwxr-xr-x. 1 phet-admin phet-admin unconfined_u:object_r:unlabeled_t:s0   54 Oct 11  2022 npm-cli.js
-rwxr-xr-x. 1 phet-admin phet-admin unconfined_u:object_r:unlabeled_t:s0  538 Apr 11  2024 npm.cmd
-rwxr-xr-x. 1 phet-admin phet-admin unconfined_u:object_r:unlabeled_t:s0  834 Jul  8 06:20 npm-prefix.js
-rw-r--r--. 1 phet-admin phet-admin unconfined_u:object_r:unlabeled_t:s0  763 May  9 04:00 npm.ps1
-rwxr-xr-x. 1 phet-admin phet-admin unconfined_u:object_r:unlabeled_t:s0 2073 Apr 11  2024 npx
-rwxr-xr-x. 1 phet-admin phet-admin unconfined_u:object_r:unlabeled_t:s0 2921 May  9 04:00 npx-cli.js
-rwxr-xr-x. 1 phet-admin phet-admin unconfined_u:object_r:unlabeled_t:s0  538 Apr 11  2024 npx.cmd
-rw-r--r--. 1 phet-admin phet-admin unconfined_u:object_r:unlabeled_t:s0  763 May  9 04:00 npx.ps1

```

**Comment by zepumph** [comment]
@mattpen and I spoke, and it does look like we should add bin_t to the above runnable, the links in ./bin that point to ./lib/node_modules/npm/bin/ don't propagate those permissions.

**Comment by zepumph** [comment]
Ok. I followed steps to update executable selinux permissions for runnables in `/home/phet-admin/.nvm/versions/node/v20.18.0/lib/node_modules/npm/bin/`. 

I followed these steps:
* Checked rosetta logs to see if anyone was using them (no)
* Restarted rosetta into maintenance mode (is enabled:false)
* edited rosetta.service file to point to node v20.18.0 and saved (needed sudo)
* Run these commands: `sudo semanage fcontext -a -t bin_t /home/phet-admin/.nvm/versions/node/v20.18.0/lib/node_modules/npm/bin/* && sudo restorecon -v /home/phet-admin/.nvm/versions/node/v20.18.0/lib/node_modules/npm/bin/*`.
* restart rosetta while looking at the logs, all went well.
* In the browser see that we are successfully still in the maintenance mode
* change rosetta out of maintenance mode
* restart rosetta. 

All looks to be working for me. @jbphet can you give things a spot check?

**Comment by jbphet** [comment]
I've verified that Rosetta is indeed running with the updated NodeJS version based on this entry in its log on phet-server2:

```
Oct 31 16:22:35 phet-server2.int.colorado.edu rosetta[2613210]: info:     NodeJS Version: 20.18.0
```

Next I checked out the main translation page at https://phet.colorado.edu/translate/ to make sure it was looking good, and it is.

The next step is to see if there has been a successful submission of a new or updated translation.  I checked the logs and found this:

```
Nov 01 08:47:06 phet-server2.int.colorado.edu rosetta[2613210]: info: build request object 1 of 3:
Nov 01 08:47:06 phet-server2.int.colorado.edu rosetta[2613210]: info:   api: 2.0
Nov 01 08:47:06 phet-server2.int.colorado.edu rosetta[2613210]: info:   simName: greenhouse-effect
Nov 01 08:47:06 phet-server2.int.colorado.edu rosetta[2613210]: info:   version: 1.3.3
Nov 01 08:47:06 phet-server2.int.colorado.edu rosetta[2613210]: info:   locales: sk
Nov 01 08:47:06 phet-server2.int.colorado.edu rosetta[2613210]: info:   servers: production
Nov 01 08:47:06 phet-server2.int.colorado.edu rosetta[2613210]: info:   brands: phet,phet-io
```

The `sk` locale is for Slovak, so I then checked the main website for the latest Slovak translation of Greenhouse Effect.  It's there, and generally looks reasonable (as far as I can tell given that I don't read Slovak).  The "About..." dialog shows the following build information:

![image](https://github.com/user-attachments/assets/bb4e68e9-3194-440f-a611-a9ff98d08416)

14:50 is 8:50 AM local time, which matches up with the log info.

So, it looks like we're good to go here.  Thanks for fixing things up @zepumph!  Closing.
