### ISSUE TITLE
Translators can change version number and the names of who is credited

### ISSUE THREAD

**Issue by phet-steele** [phetsims/rosetta#44]
Using the below strings as examples, it's very easy to just type in a new name and version number (or delete them):

![i made it all](https://cloud.githubusercontent.com/assets/5863899/9338904/7ecf129c-45a4-11e5-9860-08da9d3251f8.PNG)

And then have them show up like so in the sim:

![i made it all 2](https://cloud.githubusercontent.com/assets/5863899/9339005/02e631a0-45a5-11e5-8336-3fd647003983.PNG)

Translators should not be allowed to change these things.

**Comment by pixelzoom** [comment]
If the English string is a MessagFormat pattern, then the translated string should be too, with the same number of placeholders.

**Comment by jbphet** [comment]
@pixelzoom suggested enforcing that if the English version is a pattern, then the translated version must be too.  @aaronsamuel137 said that this could be done with a reasonable amount of effort, assigning to him.

**Comment by pixelzoom** [comment]
This is in the territory of Rosetta making decisions by examining the English string. We were going to try to avoid doing that, and rely on metadata.  Might be ok to do this as a shorterm solution.

**Comment by aaronsamuel137** [comment]
I've added validation for patterns and tested locally. Closing.

**Comment by aaronsamuel137** [comment]
@phet-steele pointed out we want to allow empty strings for patterns too.

**Comment by aaronsamuel137** [comment]
I think this is working now. @phet-steele, will you verify?

**Comment by pixelzoom** [comment]
I don't see this as being fixed. See https://github.com/phetsims/rosetta/issues/59

**Comment by pixelzoom** [comment]
When is the validation occurring? For English "{0} {1}", I'm able to enter "{0}". I get no immediate feedback in the Rosetta UI (see #59), and no feedback when I run the sim using the "Test" button.

**Comment by phet-steele** [comment]
@pixelzoom the validation occurs after pressing "Submit". The user is presented with an error message and the problem entries are outlined in red, in the same way our website works when registering an account. @aaronsamuel137 yes, empty strings are being allowed.

**Comment by pixelzoom** [comment]
Validating on "Submit" is way too late in the process.

**Comment by aaronsamuel137** [comment]
Closing here, tracked in #59
