### ISSUE TITLE
Pre-commit hooks are failing in rosetta.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rosetta#445]
After a pull-all, pre-commit hooks were failing for me with:

> ../../../../rosetta/src/server/app.ts:16:21 - error TS7016: Could not find a declaration file for module ‘express’. ‘/Users/cmalley/PhET/GitHub/rosetta/node_modules/express/index.js’ implicitly has an ‘any’ type.
  Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module ‘express’;`
16 import express from ‘express’;
>                     ~~~~~~~~~
> ../../../../rosetta/src/server/app.ts:21:26 - error TS2307: Cannot find module ‘../common/publicConfig.js’ or its corresponding type declarations.
21 import publicConfig from ‘../common/publicConfig.js’;
>                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../../../../rosetta/src/server/app.ts:44:14 - error TS7006: Parameter ‘req’ implicitly has an ‘any’ type.
44   app.use( ( req, res, next ) => {

In Slack#dev-public, @samreid said::

> Did you npm install there?
My rosetta problem is:
~/phet/root/rosetta$ grunt type-check
Running "type-check" task
(Forwarding task to perennial-alias)
Running "type-check" task
src/server/app.ts:21:26 - error TS2307: Cannot find module '../common/publicConfig.js' or its corresponding type declarations.
> 
> 21 import publicConfig from '../common/publicConfig.js';
>                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~
> Found 1 error.
> 
> Done.

@zepumph and @jbphet are apparently working on making rosetta TypeScript capable, and this is related.

I pointed out that having to `npm install` in a repo that is not related to build tools is not something that is expected. And it was not announced.  

After doing `cd rosetta; npm install` as suggested, I'm still getting the failure that @samreid noted above.  I find no file named publicConfig.js. Is it something new that was not checked in?

**Comment by jbphet** [comment]
I have reverted `app.ts` back to `app.js`, so it is now passing lint.  I just checked CT, and rosetta is now green.  I think it's now safe to close this, and we will pick things up again under https://github.com/phetsims/rosetta/issues/311 when we have time to do so.
