### ISSUE TITLE
Line break is not occuring while using the Test button, but is occuring after submitting

### ISSUE THREAD

**Issue by phet-steele** [phetsims/rosetta#45]
Mostly this is a question. When I type in a value for the strings "SpectrumWindow.ultravioletBandLabel" and "SpectrumWindow.gammaRayBandLabel", the two strings in MAL that support a line break, it works correctly after submitting to the website:

I typed in "Ultra-\nindigo" and "Gamma\nbeam"
![correct break](https://cloud.githubusercontent.com/assets/5863899/9339823/65f6bf5e-45a9-11e5-900e-dcb0ba7b6232.PNG)

But before submitting and instead just clicking the Test button, the sim shows the gamma ray label as not broken. Where is this difference coming from @aaronsamuel137?
![incorrect break](https://cloud.githubusercontent.com/assets/5863899/9339868/a8a3df30-45a9-11e5-8f83-e511a7f69fd4.PNG)

**Comment by aaronsamuel137** [comment]
I can't reproduce this @phet-steele. When I test, the line break is there as it should be. If it isn't, then there is a bug there. Can you try again and see what happens? Or tell me how to reproduce?

**Comment by phet-steele** [comment]
Fixed after above commit.
