### ISSUE TITLE
Empty strings do not return a default value

### ISSUE THREAD

**Issue by phet-steele** [phetsims/rosetta#46]
This is already an issue known by @aaronsamuel137. Deleting values for previously translated strings does not return the strings to their default, english values. They instead just become empty:

![empty sim](https://cloud.githubusercontent.com/assets/5863899/9340139/5e862406-45ab-11e5-8680-9e2e2fa47eed.PNG)

**Comment by aaronsamuel137** [comment]
This appears to be working for me now. Is it working for you @phet-steele? Feel free to close if so.

**Comment by phet-steele** [comment]
Doesn't look fixed for me yet. It did, however work when testing, but now after submitting.

**Comment by aaronsamuel137** [comment]
What about this doesn't look fixed. I just looked at the translation you just deployed http://phet-dev.colorado.edu/sims/html/molecule-shapes/latest/molecule-shapes_ay.html and it inherits the english strings just fine.

**Comment by phet-steele** [comment]
I was testing something else with that deploy, the one i tested this issue with is here https://phet-dev.colorado.edu/sims/html/molecules-and-light/latest/molecules-and-light_nd.html

**Comment by aaronsamuel137** [comment]
OK I am pretty sure this is fixed now. Can you verify @phet-steele?

**Comment by phet-steele** [comment]
Things are looking good on my end :smile:!
