### ISSUE TITLE
issue with hyphenated string key

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/rosetta#47]
Looks like the string key in joist "third-party.credits.link" was shortened to "third" by rosetta, presumably because of the hyphen, but I'll need to look into this more to be sure. See https://github.com/phetsims/babel/blob/tests/joist/joist-strings_cs.json#L339.

Two issues here:
1. We should probably change the string key in joist since our convention is camelCase.
2. Investigate why this shortening happens in rosetta, and determine if anything needs to be done after addressing issue 1.

**Comment by aaronsamuel137** [comment]
I've updated the string key, but I can't find why this happened in the first place.

@phet-steele, did you ever translate a string "Third-party Credits"? I can't seem to get it to come up in Rosetta.

**Comment by aaronsamuel137** [comment]
Closing for now, I see no further issues happening here.

**Comment by phet-steele** [comment]
Sorry never saw your comment @aaronsamuel137. No, there was never a string for "Third-party Credits", and translating "third" did absolutely nothing in the sim (it left Third-party Credits untranslated).

**Comment by aaronsamuel137** [comment]
Was there a string that was just "third" in rosetta to translate? I never saw this either.

**Comment by phet-steele** [comment]
Yes, it was just presented as third.

**Comment by phet-steele** [comment]
Here's another one for Atomic Interactions.
It's title string key "atomic-interactions.name" is just presented as "atomic"

**Comment by aaronsamuel137** [comment]
The issue here was the regex that extracts the strings... it didn't allow hyphens previously, probably because I assumed all of our string keys where camelCase. Should be fixed now.

**Comment by aaronsamuel137** [comment]
Closing
