### ISSUE TITLE
Unused strings are available to translate

### ISSUE THREAD

**Issue by phet-steele** [phetsims/rosetta#48]
Disscussed with @jbphet, when Rosetta decides what string keys a sim should use, in the case of a sim like Atomic Interactions who takes basically all its strings from a separate repo, Rosetta cannot distinguish between a string that is used in the Atomic Interactions' parent repo and a string that is actually used in the AI sim. For example, the string key "AtomsAndMolecules" is used in SoM as a title above the atom selection panel:

![somi](https://cloud.githubusercontent.com/assets/5863899/9498720/6ba5686c-4bd8-11e5-95cc-aa88e563b5c9.PNG)

But no such thing is used in AI, even thought the string is still present in Rosetta to translate:

![aii](https://cloud.githubusercontent.com/assets/5863899/9498741/9217b734-4bd8-11e5-8e57-04dcb7afef3f.PNG)

As a more serious example, the string key "distanceBetweenMolecules" is used in SoM on a completely different screen than the one AI is mirroring, but still shows up in Rosetta and is available to translate.

**Comment by pixelzoom** [comment]
8/27/15 dev meeting consensus:
• assign to @ariel-phet (who doesn't think we need to address it)
• address this issue via documentation

**Comment by ariel-phet** [comment]
This issue has been addressed by documentation, but should be left open to consider longer term solutions

**Comment by liammulh** [comment]
Right now, the way this works is that if a string is in a sim's `window.phet.chipper.strings` object, then it is presented for translation. `window.phet.chipper.strings` is Rosetta's single source of truth for what strings are in a simulation. If there are strings in that object that aren't in the simulation and therefore shouldn't be presented for translation, the sim developer needs to remove them.
