### ISSUE TITLE
Pull the information in TranslatableSimInfo out into a separate JSON file

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#5]
For some initial prototyping of the translation utility behavior, a JavaScript type was created that contained simulation-specific information needed by the translation utility, such as which simulations were available for translation and where to go to get a link to the sim.  This information was hard coded into the object.  This object's API should be retained, but the information should be moved into a separate JSON data file.  For now, it is okay to only read the file upon initialization (as opposed to reading it each time it is accessed).

At some point, we may want to move this into a database.  If the person who implements this has the expertise to set this up and do it using something like MongoDB initially, we should discuss it.  Otherwise, using a file should suffice for now.

**Comment by aaronsamuel137** [comment]
@jbphet, what do you think about using MongoDB vs a json file? @BrianNewsom has some experience with MongoDB and is comfortable going that route if that is a better long-term solution.

**Comment by jbphet** [comment]
The idea of using MongoDB was discussed at the 3/13/2015 translation meeting, and we decided against it for now.  The main reasons are:
+ If we consider doing this, we should weigh it against the alternative of adding a new DB to the PostgreSQL database that is being used for the main site.  Might be simpler to just have one DB server.
+ Lack of experience with MongoDB

We may well change our minds in the future, but for now let's just keep it simple and go with a file.

**Comment by BrianNewsom** [comment]
@jbphet I just moved the data into a JSON file, pretty simple and quick.  Let me know if this is not what you intended or if there's a better way to do this.  Thanks!

**Comment by BrianNewsom** [comment]
@aaronsamuel137 Assigning to you, if you get a chance to check over it.

**Comment by aaronsamuel137** [comment]
This looks good to me. Closing.
