### ISSUE TITLE
Empty strings in Rosetta

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/rosetta#50]
I have noticed that Molecule Shapes has some empty string values. Should these appear in Rosetta, or should we adopt a behavior where strings with empty values in English don't show up?

Assigning to @jonathanolson for a recommendation since I don't understand what these empty strings are for in Molecule Shapes.

**Comment by aaronsamuel137** [comment]
How empty strings appear in Rosetta currently:

<img width="577" alt="screen shot 2015-08-28 at 9 48 52 am" src="https://cloud.githubusercontent.com/assets/3193912/9550690/0fc00ca8-4d6a-11e5-9201-0913b61b49c8.png">

**Comment by jonathanolson** [comment]
shape.empty and geometry.empty are used if a translator wants to provide a label for a molecule with only a central atom. They are blank in the English translation.

I'd say we'd want them to show up in Rosetta.

**Comment by aaronsamuel137** [comment]
OK, leaving them in rosetta for now. Closing.
