### ISSUE TITLE
sort the strings by English value

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#52]
@pixelzoom has suggested sorting the strings by their English value to group related strings together and to make it easier to find a particular string.  This seems reasonable, and @aaronsamuel137 says that it wouldn't require too much work.

**Comment by phet-steele** [comment]
Related to #37. If the strings are re-ordered by their English value, it would be nice to have the same order in the debug info, and if we go ahead with #51 it would make even more sense to have both screens match.

**Comment by aaronsamuel137** [comment]
Addressed. Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
:+1: Closing.
