### ISSUE TITLE
use same font size for English and translated strings

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rosetta#53]
On the browers that I've tested (Mac + Safari, Chrome) the text fields where you enter translated strings are using a much smaller font than is used to display the English strings.  Recommended to make them the same size font. It's very difficult to get a feel for relative string length when the fonts are different sizes.

**Comment by aaronsamuel137** [comment]
Addressed in a69d550b870297bc03816c6e184eae834d42ab36.

Sorry to address so many issues in one commit, I was looking at a lot of formatting stuff at once.

**Comment by aaronsamuel137** [comment]
Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
Looks great. Closing.
