### ISSUE TITLE
fixed-length text fields make it frustrating to translate long strings

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rosetta#55]
The text fields for the translated strings look like they're uniformly sized.   That's frustrating if I'm trying to translate a long string, or if my translated string is significantly longer than the English string. 

Partial screen from translating "Concentration", in the "Common Strings" section:

![screenshot_589](https://cloud.githubusercontent.com/assets/3046552/9613169/068d509c-50a7-11e5-9339-e84c5a05a711.png)

Trying to translate the longer strings (e.g., "There is a new version available: {0}.") in this tiny text field is very frustrating. I can never see the entire translation, and I need to resort to manually shifting the cursor around in the field.

In the Java Translation Utility, the text field widths were constrained to be uniform, but if a string got longer than the width, it would wrap to a new line.  Example:

![screenshot_590](https://cloud.githubusercontent.com/assets/3046552/9613328/e5440542-50a7-11e5-9a8d-da3a0a25c582.png)

**Comment by pixelzoom** [comment]
Another screenshot below to demonstrate the problem with fixed-width text fields. Note the "translation.credits" field.  It contains html markup, with tags that must be matched. Imaging trying to do this in a single-line text field that only shows you a max of N chars.

![screenshot_591](https://cloud.githubusercontent.com/assets/3046552/9613554/53ccf3d8-50a9-11e5-937e-a568273c5595.png)

**Comment by aaronsamuel137** [comment]
Text fields now wrap around and grow. This was slightly complicated to implement, I had to use contenteditable divs and a hidden input to submit the value.

Also, pressing enter to create a new line is disable, since I am not sure how Rosetta should interpret that.

Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
Awesome. Closing.
