### ISSUE TITLE
show the font that's being used?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rosetta#56]
The Java Translation Utility showed the names of the fonts that it was using. For example, see the top of this screenshot ("font: LucidaGrande"):

![screenshot_590](https://cloud.githubusercontent.com/assets/3046552/9613374/2d59d8a2-50a8-11e5-82d3-6e187aaeaa2e.png)

This was important because we frequently had issues with fonts not properly displaying the glyphs for a locale, and we needed to troubleshoot and/or identify a preferred font.  

Is this something that we'll also encounter with HTML5 sims?  How will we know what font is being used when a problem is reported?

**Comment by jbphet** [comment]
Discussed in the 9/3/2015 meeting and decided to do two things in the short term:
+ set up a task to test translation of some of the languages that required users to specify preferred fonts for Java sim
+ continue discussion at next dev meeting when @pixelzoom is available

**Comment by pixelzoom** [comment]
9/8/15 dev meeting:
• JO: It may be a security issue to detect exactly which font they're using.
• SR: According to StackOverflow, only detectable by using dev tools.
• Close this for now. Deal with it if/when it occurs.
