### ISSUE TITLE
Help button?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rosetta#57]
How will translators find the documentation being prepared in https://github.com/phetsims/tasks/issues/335? Should Rosetta's UI have a Help button, like the Java version did?

**Comment by aaronsamuel137** [comment]
Added a help button with @dawsonbotsford. Feel free to give feedback about the look, placement, etc. My main concern with this placement is that it might overlap with the CU logo on narrower screens. But perhaps it is fine for version 1.0.

Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
I never would have looked in the upper-right corner for the Help button.  Why not put it next to the other buttons? (Test, Save, Submit, Help)

**Comment by pixelzoom** [comment]
I hate to keep pointing to the Java version, but here's a screenshot. The Help button is with the other buttons, not buried in the menubar or someplace else.

![screenshot_607](https://cloud.githubusercontent.com/assets/3046552/9770047/0c93c9cc-56eb-11e5-9b99-a8a7bb59ce96.png)

**Comment by aaronsamuel137** [comment]
Help button moved. Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
:+1: Closing.
