### ISSUE TITLE
identify the sim being translated

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rosetta#58]
I had a couple of sims open in Rosetta. I went to lunch, came back, and discovered that I didn't know what sim was loaded.   The name of the sim doesn't appear in Rosetta's UI, see screenshot below.  I finally noticed that it's in the URL.  But shouldn't the sim name appear somewhere in the UI?  Maybe instead of "Sim Strings" it should say "Sim Strings (Concentration)"?

![screenshot_592](https://cloud.githubusercontent.com/assets/3046552/9613691/3354c030-50aa-11e5-879b-63eddb1f7355.png)

**Comment by aaronsamuel137** [comment]
Addressed when taking care of #63. Closing
