### ISSUE TITLE
Create utility for extracting string usage info from built sim

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#6]
The translation utility will need to be able to determine exactly which common code strings are in use within a given simulation.  In support of this, we will need a utility that takes the URL of a published simulation (or any simulation, for that matter) and returns a JavaScript object that lists the used strings.  This can be done be scanning the file for all occurrences of "string!<project-name>/<stringKey>", for example, "string!JOIST/credits.title".  This utility object should return an array of objects that indicate the string keys used, and it should be formatted as shown in the following example.  Note that the project names in the string directives are upper case and use underscores instead of hyphens as a separator.  These will need to be converted.

Example output:
```js
[ 
  {
    projectName: area-builder,
    stringKeys: [ 'level', 'title' ]
  },
  {
    projectName: joist,
    stringKeys: [ 'credits.title', 'credits.team' ]
  },
  {
    projectName: vegas,
    stringKeys: [ 'check', 'keepTrying' ]
  }
]
```

**Comment by pixelzoom** [comment]
@jbphet wrote:
> Note that the project names in the string directives are upper case and use underscores instead of hyphens as a separator. These will need to be converted.

So for example, 'PHET_CORE' to 'phet-core'. I'm a little nervous about doing this by mapping to lowercase and changing '_' to '-', because it assumes that the convention will be followed unvaryingly in config.js.  And that hasn't been the case (e.g., https://github.com/phetsims/build-a-molecule/issues/69). It would be safer to read config.js, but perhaps not worth the hassle. I guess we can try to the easier approach, and use it as a "hammer" for enforcing the convention in config.js.

**Comment by jbphet** [comment]
Agreed - I'm a little nervous about it too, and had the same thought: This rather forces us to be consistent in our naming conventions within the config files.  We may want to add some enforcement of this to the build tools.

**Comment by aaronsamuel137** [comment]
I've added this as a route for now just so you can run it and see the output easily from rosetta. Not sure where it should go ultimately.

Take a look at /extractStrings for an example.

Assigning to @jbphet for review.

**Comment by jbphet** [comment]
Generally looks good.  A couple of comments:
+ Let's leave it on a route for now, but pull the utility into a separate class - TranslationUtils seems like a good name for now but feel free to go with something else.
+ Please have it take just the URL as the input parameter.  You can assemble it as you did in the route, but I'd like to be able to pull it from anywhere, i.e. from phet.colorado.edu even while running on phet-dev or localhost.
+ I changed the route to be /translate/extractStrings, since without the /translate/ portion the request won't get routed to this utility when running on phet or phet-dev.

Assigning back to @aaronsamuel137.

**Comment by aaronsamuel137** [comment]
OK I think I've fixed these issues. I've moved extractStrings to a file TranslationUtils - but I am still importing into in rosetta.js via routes, so all the routes come from the same place.

```js
module.exports.extractStrings = TranslationUtils.extractStrings;
```

I'd be fine to import it directly into rosetta.js from TranslationUtils if that is preferable.

**Comment by aaronsamuel137** [comment]
Assigning to @jbphet for review

**Comment by aaronsamuel137** [comment]
This is working fine, so closing. @jbphet can address any outstanding issues during his code review.
