### ISSUE TITLE
differentiate between HTLM5 and Java/Flash translation utilities?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rosetta#62]
The title at the top of https://phet-dev.colorado.edu/translate/ is "PhET Translation Utility".  Is there any need to differentiate this from the Java/Flash translation utility?  Is the Java version being taken down?

**Comment by pixelzoom** [comment]
If the Java/Flash translation utility is going to continue to co-exist, then perhaps label this something like "PhET Translation Utility (HTML5)".

**Comment by aaronsamuel137** [comment]
Added (HTML5) to title. Closing.
