### ISSUE TITLE
dependency on other sims is hidden

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rosetta#63]
Translating "Concentration", I see that all of the strings from the concentration and beers-law-lab repositories are combined under the "Sim Strings" heading.

How will the user going to know that these 2 sims are related, and that by changing strings here, they are affecting another sim?  There's a warning about this for common strings, but no such warning here.

I'm also curious... How does Rosetta differentiates beers-law-lab from other dependencies, and know to include its strings under "Sim Strings"?

**Comment by pixelzoom** [comment]
Not sure of the best way to resolve this... But I think we need to identify (1) the sim(s) that a sim is dependent on, and (2) which strings will affect other sim(s) if their translations are changed.

Note that I said "sim(s)" above.  We currently have tried to limit sim-to-sim dependencies.  But there is no firm policy (that I'm aware of) that says a sim can't have dependencies on >1 sim.  That could easily change in the future. And I don't think we want to design Rosetta based on that constraint.

**Comment by aaronsamuel137** [comment]
Rosetta can already identify both items without very many code changes, and it will handle the case of >1 dependency already. The question here is, what do we do with this information? Do we mark each string from a different sim with a different color? Make a new section for each sim dependency? Something else?

**Comment by jbphet** [comment]
Do we really need to address this for v1?  I've added the developer-meeting label so that we can discuss.

**Comment by pixelzoom** [comment]
There are currently 2 headings: "Sim String" and "Common Strings".   To use Concentration as an example... I don't think that beers-law-lab strings should be mixed in with "Sim Strings".  Recommend to (1) relabel "Sim Strings" to indicate the sim title (e.g. "Concentration"), and (2) show strings from other sims under separate headings, with a warning similar to "Common Strings".  Here's how this might looks: 

```
Concentration

concentration.name   Concentration    ___________

Beers Law Lab

WARNING: Changing these strings will affect the Beer's Law Lab simulation, as well as any other simulations that depend on it.

...

Common Strings

WARNING: Translating common strings will effect all simulations that use these strings.

...

```

**Comment by jbphet** [comment]
Discussed in the 9/3/2015 meeting.  We agreed to implement some rudimentary handling of this for v1, and make it look like this:

**Concentration**

concentration.name...

**Shared Strings (will affect Beers Law Lab)**

solute...

**Common Strings (will affect multiple simulations)**

version...

*However,* this will only work in the case where the user is translating a sim that gets its strings from another simulation.  The other direction, i.e. the case where the "parent" sim is being translated and it affects other sims (e.g. Beers Law Lab is being tranlated, and it affects the Concentration sim) is harder to detect and we are deciding to punt on this until v2.

**Comment by aaronsamuel137** [comment]
Implemented to suggestion in https://github.com/phetsims/rosetta/issues/63#issuecomment-137538586. Note that rosetta doesn't have easy access to the title of sim dependencies (since they are not in the compiled sim), so it currently reads:

**Shared Strings (will affect beers-law-lab)**

and not

**Shared Strings (will affect Beers Law Lab)**

Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
Using repo name (e.g., beers-law-lab) instead of title (e.g. "Beer's Law Lab") is OK with me for beta, to see how it's interpreted by translators. 


If a sim is dependent on >1 other repo in active-sims, will there be 2 headings labeled "Shared Strings"?

**Comment by aaronsamuel137** [comment]
Yes, it should handle the case of >1 other repos in active sims, though it hasn't been tested.

Okay to close this?

**Comment by pixelzoom** [comment]
So the UI will look like what's shown below. It seems odd to have 2 sections title "Shared Strings", doesn't it?

**Concentration**

concentration.name...

**Shared Strings (will affect beers-law-lab)**

solute...

**Shared Strings (will affect some-other-sim)**

...

**Common Strings (will affect multiple simulations)**

version...

**Comment by aaronsamuel137** [comment]
No, it would look like this:

**Concentration**

concentration.name...

**Shared Strings (will affect beers-law-lab, some-other-sim)**

solute...

**Common Strings (will affect multiple simulations)**

version...

**Comment by pixelzoom** [comment]
Thanks for clarifying. I think that works for beta. Closing.
