### ISSUE TITLE
change "Sim Strings" to "Simulation Strings"?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rosetta#64]
"Sim" is an internal abbreviation for "simulation", and it's not used on the PhET website.  English is probably also not the first language of Rosetta users.  So probably shouldn't use "sim" here either.

**Comment by pixelzoom** [comment]
Also currently inconsistent... Combo box on the first Rosetta page is labeled "Select Simulation".

**Comment by aaronsamuel137** [comment]
This was changed to read "[Sim Title] Strings" in #63, so is no longer relevant. Closing
