### ISSUE TITLE
sort order for "Select Simulation" combo box?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rosetta#65]
There are currently only 2 sims in the combo box, but the order is "Molecules and Light", followed by "Concentration".  So I'm guessing that the list is not being sorted alphabetically.

**Comment by aaronsamuel137** [comment]
Combo box is now in sorted order. Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
:+1: Closing.
