### ISSUE TITLE
HTML strings should show markup, not be interpreted

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/rosetta#67]
I noticed in chains, that the English string is:

>Turning *left* on red is a **bold** move

and not:

```html
Turning <i>left</i> on red is a <b>bold</b> move.
```

I assume we should be showing the actual markup here.

**Comment by pixelzoom** [comment]
Yes, should be showing HTML markup.

**Comment by aaronsamuel137** [comment]
This used to work but was broken by changes to the code that marks up \n and {0}. Fixed now.
