### ISSUE TITLE
strings from "other sims"

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rosetta#7]
This was mentioned at a design meeting, but wanted to make sure that it doesn't slip through the cracks. We've been speaking of "sim" strings and "common" strings.  But in the case of sims that depend on other sims (e.g., concentration depends on beers-law-lab), there is a 3rd category, call it "other sim" strings.  

Questions:
How do we know which repos is pheLibs are other sims? 
How are "other sim" strings identified in the GUI?
When a translation is submitted, are the other sim(s) published?

**Comment by aaronsamuel137** [comment]
We need to test this case. Assigning to myself.

**Comment by aaronsamuel137** [comment]
Current behavior:

- Strings from "other sims" show up under the sim strings section, not the common strings.
- The user has no way of knowing that these strings are coming from two different sims
- The other sim is not published.

**Comment by aaronsamuel137** [comment]
Discussed on 7/14/15. Current behavior looks good. Closing
