### ISSUE TITLE
add documentation on how to manage rosetta

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#74]
We should probably have some good, clear documentation about how to start, shut down, check status of, and so forth for the translation utility so that we can handle things that come up when @aaronsamuel137 is not available.  A markdown (.md) file in the root github directory would probably be a good place for this, and could be referenced from the README.md file.

This may include some very PhET-specific things, such as where this is run on the servers, so we will need to decide if we're comfortable with this or if we want to look at making the repo private.

**Comment by aaronsamuel137** [comment]
I've added a little bit to the README in this commit: feef2c2b3903e0b5ffa75ccd2262c05446872a79

Should I add more documentation about how rosetta is handled, such as what directory it is stored in, etc., or do we want this somewhere private?

**Comment by aaronsamuel137** [comment]
Added to developer meeting to discuss

**Comment by aaronsamuel137** [comment]
Added more documentation to README. Assigning to @jbphet for review.

**Comment by jbphet** [comment]
Looks decent.  We may feel like adding more once we have some experience in managing this.  Closing.
