### ISSUE TITLE
missing copyright notices in many of the HTML template files

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#76]
In html/views, the ```error.html``` and ```translation-submit.html``` files have copyright notices, the other files don't seem to have them.  They probably should be there.

**Comment by pixelzoom** [comment]
@aaronsamuel137 Do you have a copyright profile set up in IntelliJ IDEA? Preferences > Copyright > Copyright Profiles.  Mine looks like this:

![screenshot_16](https://cloud.githubusercontent.com/assets/3046552/10144356/7e792296-65da-11e5-91e5-2e27feea93c9.png)

**Comment by aaronsamuel137** [comment]
Added copyright notices. Thanks for the Intellij tip @pixelzoom, I have added a copyright profile now.

Assigning to @jbphet for review.

**Comment by jbphet** [comment]
Headers look good, thanks.  Closing.
