### ISSUE TITLE
is simInfoArray.json still used?

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#77]
There is a file in the data subdirectory called simInfoArray.json.  It's an empty array in github.  It appears to be used in several places by the source code, so I thought it might be something that is populated only on the server.  I checked it out on the server, and it appears to be empty there also.  Is it still used?  If it is, but is dynamic, does it really need to be maintained on GitHub?

**Comment by aaronsamuel137** [comment]
Currently, build-server commits to this file automatically when a sim is deployed. That was rosetta will know what sims are translatable. To remove it from github will require changes to build server and setting up some kind of database with this information. I recommend against it. It will eventually be removed once all sims are translatable.

**Comment by jbphet** [comment]
And it is empty now because no sims are translatable?

**Comment by aaronsamuel137** [comment]
Actually, it isn't empty, I reverted my commit to empty it out as I am still using those sims for testing build-server on phet-dev.

However, once testing it done, it will be empty until any of our SR-redeploys are up on the live site. They will be added automatically if deployed using build-server.

**Comment by aaronsamuel137** [comment]
OK to close this, or is there more to do here?

Assigning to @jbphet.

**Comment by jbphet** [comment]
Thanks for the explanation, it makes sense.  Closing.
