### ISSUE TITLE
document using branches for testing (or remove comment)

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#78]
The following line was found in constants.js:

```js
module.exports.BRANCH = 'master'; // branch of babel to commit to, should be changed to master when testing is finished
```

This is a little confusing since the value is currently set to 'master'.  It would be good to document whether this can be switched to some alternative value to enable testing, or whether is should always be set to 'master' from now on.  And, if it was something used to enable testing and is no longer useful, perhaps it should now just be in-lined in the code.

**Comment by aaronsamuel137** [comment]
I've updated the comments here, and added an assertion for the possible values of BRANCH.

Assigning to @jbphet for review.

**Comment by jbphet** [comment]
Looks good, closing.
