### ISSUE TITLE
sortedLocalInfoArray should be a value or a getter

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#79]
LocaleInfo.js exports the following:

```js
  sortedLocaleInfoArray: function() {
    return sortedLocales;
  },
```

For clarity, it should either be getSortedLocaleInfoArray (since it's a function) or should just be assigned to be the value of the sortedLocales array or an ES5 getter, if possible.

**Comment by aaronsamuel137** [comment]
Fixed this, and the field for localeInfo, and clarified the types of each.

Assigning to @jbphet for review.

**Comment by jbphet** [comment]
Changes look good, closing.
