### ISSUE TITLE
Error handling should be added for case where string extraction fails

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#81]
routes.js includes the following code:

```js
      var result = TranslationUtils.extractStrings( body, simName );
      var extractedStrings = result.extractedStrings;
      var simSha = result.sha; // sha of the sim at the time of publication, or 'master' if no sha is found
      winston.log( 'info', 'sim sha: ' + simSha );
```

and TranslationUtils.js includes the following in the extractStrings method:

```js
  // if no matches are found, it probably means the sim url was not correct
  if ( matches === null ) {
    return;
  }
```

It appears that it is legitimate for TranslationUtils.extractStrings to return ```null```, but there doesn't appear to be any handling of that case in routes.js.  Such handling should be added, probably something like just displaying the error page.

**Comment by aaronsamuel137** [comment]
Good catch. An error page should be rendered if this returns null. Fixed. Assigning to @jbphet for review.

**Comment by jbphet** [comment]
I tried testing this by modifying TranslationUtils.extractStrings to always return ```null```, and this causes Rosetta to crash when I select a sim and language and press the "Go" button.  A quick look at the stack trace leads me to believe that the code tries to show the error message but then continue execution.  Does there need to be a return statement or something after showing the error page?

**Comment by aaronsamuel137** [comment]
Good catch. It did need a return statement, and another small fix.

Assigning to @jbphet for review.

**Comment by jbphet** [comment]
Much better - thanks.  Changes look good, testing succeeded.  Closing.
