### ISSUE TITLE
Session security

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/rosetta#82]
We should move the session secret to the build-local.json file and change it. And look into other steps to make sure Rosetta is secure.

**Comment by aaronsamuel137** [comment]
Added a secure secret in build-local.json. Right now it is only required on linux, so that people don't need to worry about setting it up when testing locally. Of course, this is not a great test since it assumes linux = production. Do you have any other suggestions about how to do this @jbphet?

**Comment by jbphet** [comment]
@aaronsamuel137 and I discussed this and decided that it would be better to have the "secure secret" value in the build-local.json file.  He will make this change and will add an assertion that will let anyone who is trying to test locally know what to do if they run into this.

**Comment by aaronsamuel137** [comment]
I've made this change. Assigning to @jbphet for review.

**Comment by jbphet** [comment]
Looks good.  The error message seems clear and should serve to let people know what they need to do to make it run locally.  Closing.
