### ISSUE TITLE
code structure counts on timing of responses to HTTP requests

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#86]
I'm seeing the following code in routes.js:

```js
      request( GITHUB_URL_BASE + activeSimsPath, function( error, response, body ) {
        if ( !error && response.statusCode === 200 ) {
          winston.log( 'info', 'request from ' + GITHUB_URL_BASE + activeSimsPath + ' returned successfully' );
          sims = body.toString().split( '\n' );
        }
        else {
          winston.log( 'error', error );
        }

        // finished will not be defined if extractStrings fails
        if ( finished ) {
          finished();
        }
      } );
```

At the point where this code is executed, the ```finished``` function is not yet defined - it is defined a bit later in the code flow.  I don't know a ton about how Node.js works, but it seems like there is a small possibility that the response could come back before ```finished``` was done being defined.  Why not have this request occur *after* the definition of ```finished```?

**Comment by aaronsamuel137** [comment]
Good point. This is also a remnant from an old version of the code. Fixed.

Assigning to @jbphet for review.

**Comment by jbphet** [comment]
Looks good, thanks.  Closing.
