### ISSUE TITLE
Logs should be compressed and archived periodically

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#89]
So that the log files don't get unwieldy, they should probably be compressed and archived periodically.  I discussed this with @aaronsamuel137, and he said that he'd worked with OIT to set up something similar to handle the Tomcat logs.

**Comment by aaronsamuel137** [comment]
Probably won't worry about this until after #90

**Comment by jbphet** [comment]
@mattpen - this issue was logged before the switch to the new phet-server and systemctl.  Is this being done for these logs now?

**Comment by mattpen** [comment]
Rosetta output is now being sent to `/var/log/messages` and is rotated by rsyslog.  I do not believe the logs are being archived, so we only have access to about 2 months worth.

@jbphet - Is this acceptable or do we need to keep the history preserved in the peta library?

**Comment by jbphet** [comment]
I think 2 months of logging info should be enough.  Let's go with that for now and we can revisit if we ever decide that more would be useful.
