### ISSUE TITLE
can't check status using /etc/init.d/rosetta status

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#91]
If I try to use ```sudo /etc/init.d/rosetta status``` to check whether the translation utility is up and running, I get an error that says I don't have permissions.  Other options, such as ```restart```, work fine.  We should work with OIT to set things up so that anyone in the phet group can easily check the status.

**Comment by aaronsamuel137** [comment]
Realized you can check the status, just not with sudo. I'll add this to the readme. Closing
