### ISSUE TITLE
we should set up a process monitor to notify us if Rosetta crashes

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#92]
Currently the only way we are likely to know if Rosetta crashes is if a user notifies us.  I imagine that there is some sort of a 'process monitor' capability in Linux that OIT could set up for us that would send out email notifications if there is a crash.  I discussed this with @aaronsamuel137 and he said he would work with OIT to investigate.

**Comment by aaronsamuel137** [comment]
Email sent to OIT, waiting to hear back.

**Comment by aaronsamuel137** [comment]
OIT set this up. Apparently they set it up using the same monitoring as for the website, so the people currently who will be notified on crash are: @jonathanolson, @samreid, @kathy-phet, and @aaronsamuel137 (same as for website issue notifications).

To get added to this list requires sending an email to OIT.

Assigning to @jbphet to close or comment.

**Comment by jbphet** [comment]
Discussed this with @aaronsamuel137 and decided that we should test it out.

Also, I'm going to request that I be put on the notifications list.

**Comment by jbphet** [comment]
@aaronsamuel137 tested this by killing rosetta, and said the following (over Skype):

> Aaron Davis: got the email about 10 mins later
> seems to work as expected, and I also got a recovery email when I restarted it

Looks like this is taken care of.  I've requested that OIT add me to the list of those notified on a crash.  Work completed, closing.  Thanks @aaronsamuel137!
