### ISSUE TITLE
add header doc to init.sql

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#95]
I saw init.sql in the repo, but couldn't find any references to it.  I asked @aaronsamuel137 about it, and he said it is used to set up the database when installing Rosetta on a new machine.  There should be some documentation in the file to make this clear, and we may want to consider having it in a 'tools' or 'setup' subdirectory.

**Comment by aaronsamuel137** [comment]
Added some docs. Let me know if anything is not clear.

Assigning to @jbphet for review.

**Comment by jbphet** [comment]
Docs should help, thanks.  Closing.
