### ISSUE TITLE
Website and rosetta session IDs not in sync

### ISSUE THREAD

**Issue by phet-steele** [phetsims/rosetta#96]
1. Log in with whoever, pick a sim (probably stick with M&L since that's where I first saw this), and pick a locale
   1. Enter all your strings and press submit. You should probably, to be safe, translate at least one common and one sim string (or all of them!).
2. On the debug info screen is where I logged out. I just changed the url to phet-dev.colorado.edu/translate/ while making sure I deleted the s off of "https" so it was just "http"
3. Log in as someone else, go back to the same sim and locale
4. Change some sim strings around and submit the changes (probably best not to touch common strings yet at this point).
5. This is where babel should have a commit showing this submission was from the previous user.

**Comment by aaronsamuel137** [comment]
Addressed in 201e61bbf39cebd884808f46dbbe3a26838f42b9

Can you verify if this is fixed @phet-steele?

**Comment by phet-steele** [comment]
@aaronsamuel137 nope, this didn't work.

**Comment by aaronsamuel137** [comment]
OK I've made one more change. Now the actual email address displayed in the browser should update too. It seems to work for me when I test. Can you test again and verify? If it doesn't work, let me know exactly what you are doing and I can look into it more.

**Comment by aaronsamuel137** [comment]
I think this will handle the case of logging out and in as a separate user, but it won't handle the case of just re-logging into phet-dev as a new user without formally logging out. In the second case, the cookie from Tomcat doesn't change, so Rosetta has no way of knowing the that user changed.

I think you are right that there are some more issues to be resolved here, but perhaps these can be put off until later versions, since it is unlikely to be a use case for our translators now.

**Comment by jbphet** [comment]
@phet-steele - is this still an issue?  If so, it doesn't seem to me like it would be something to put on the list for chipper:2.0, but please let me know if you disagree.

**Comment by lmulhall-phet** [comment]
I don't think @phet-steele's steps can be followed anymore. I'm pretty sure @mattpen did something with http vs. https. Tried submitting a Wolof (?) translation of M&L and waiting > 30 minutes, but I have yet to see it.

**Comment by lmulhall-phet** [comment]
@jbphet and @mattpen should I investigate further?

**Comment by mattpen** [comment]
If this was related to switching between http/s, it's probably not possible anymore. I'd say it's safe to close this, as it seems very unlikely that a single device would be used by more than one translator.
