### ISSUE TITLE
Adding a "Log Out" button

### ISSUE THREAD

**Issue by phet-steele** [phetsims/rosetta#98]
@aaronsamuel137 and I have been discussing a way on how to rectify #96, and I suggested adding a log out button. This would be a way of directly telling Rosetta that the session ID of the website has changed (maybe?), instead of relying on Rosetta constantly comparing the two IDs (which hasn't worked out quite well yet).
For the sake of consistency, it would also just "feel" better to have a log out button like most other websites, including our own. Right now the way to log out is pretty roundabout having to delete the "s" off of "https" and reload the utility, and a log out button would streamline this. It could also function in a way as a security feature, say if a translator was working on a public computer. It would be a pretty simple way of ensuring some one other than a trusted translator doesn't submit translations to the website.

Up to @ariel-phet to decide if this is a reasonable argument (keeping in mind it might help with #96 and possibly #97 as well), and if its even for 1.0.

**Comment by ariel-phet** [comment]
This seems like a good suggestion @phet-steele 

@aaronsamuel137 is this something @phetsims/matt-p could work on?

**Comment by aaronsamuel137** [comment]
He could, but it would probably be more efficient to just do it myself since he is not familiar with nodeJS or the Rosetta code.

I'll just do this myself and leave him to work on the help center and other website issues.

**Comment by ariel-phet** [comment]
Sounds good

**Comment by aaronsamuel137** [comment]
I've added a basic log out button. The confusing thing about this is that is destroys your rosetta session, but doesn't log you out of the phet website entirely, so if you go right back to rosetta, you will still seem to be logged in.

I could look into making this log the user off the main site too if that would be better behavior. Does this do what you have been wanting @phet-steele?

**Comment by ariel-phet** [comment]
@aaronsamuel137 maybe label it..."end session" Or "end translation session" or such to clarify?

**Comment by phet-steele** [comment]
@aaronsamuel137 when you say "you will still seem to be logged in", do you mean that when I go back to rosetta that I actually *will* be logged in or it will be some sort of trick like I'm not actually logged in even though it shows I am? And if it's the latter case, why not have the button log you out of both rosetta and the website? This would match how say...Google...handles logging out of a single account across multiple tabs. And if they decided on that behaviour, they must have had a good reason for it :smile:!

**Comment by aaronsamuel137** [comment]
I think you're right @phet-steele. The log out button should log you out of both sites. I have made this change. Let me know if there is anything else needed here.

**Comment by ariel-phet** [comment]
This seems good, and translators have been successfully using rosetta with no apparent complaints about this issue. Closing.
